(function(g){var window=this;'use strict';var y1=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},z1=function(a){return g.iC(a)&&!a.K("web_player_i_see_captions_3_killswitch")},JVa=function(a,b){var c,d,e;
return g.B(function(f){if(1==f.j)return c=a+"|"+b,g.A(f,g.Ms(),2);if(3!=f.j){d=f.u;if(!d)throw g.ls("gct");return g.A(f,g.RC(d),3)}e=f.u;return f.return(e.get("captions",c))})},KVa=function(a,b){var c=new g.UC;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},LVa=function(a,b,c){JVa(a,b).then(function(d){d&&c(d.trackData,new g.UC(d.metadata))})},A1=function(){this.segments=[]},MVa=function(a,b){var c=g.fc(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.Vb(a.segments,c),g.Vb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.cc(a.segments,c,0,b),g.cc(a.segments,c+1,0,b)))},B1=function(a,b,c,d,e,f){g.G.call(this);
this.policy=a;this.player=b;this.W=c;this.N=d;this.D=e;this.V=f;this.U=this.player.S();this.C=new A1;this.I=-1;this.B=this.u=this.j=null;this.J=new g.K(this.SO,1E3,this);this.events=new g.Dz(this);g.H(this,this.J);g.H(this,this.events);this.events.P(b,"SEEK_COMPLETE",this.DC);this.DC();this.SO()},NVa=function(a){return a.j&&a.j.C?a.j.C+a.player.wd()<a.player.getCurrentTime():!1},OVa=function(a,b){var c=g.Cy(g.Zy(b,a.policy,{})),d={format:"RAW",
withCredentials:!0};a.D&&(d.responseType="arraybuffer");a.B=g.Rq(c,d,3,100).then(function(e){a:{e=e.xhr;a.isDisposed();if(a.u){var f=!(a.D?e.response:e.responseText)||400<=e.status,h=g.xta(e);if(h){e=g.Zy(a.u,a.policy,{});a.u.Jk(e,h);OVa(a,a.u);break a}f?a.player.qa("capfail",{status:e.status}):(h=a.u.j[0].Ga,null!=a.N&&a.I!==h&&(f=a.u.j[0],a.D?a.N(e.response,1E3*(f.startTime+a.player.wd())):a.N(e.responseText,1E3*(f.startTime+a.player.wd())),a.I=h))}a.u=null;a.B=null}}).Hi(function(e){a.u=null;
a.B=null;var f;a.player.qa("capfail",{status:null==(f=e.xhr)?void 0:f.status})});
a.u=b;MVa(a.C,a.u.j[0].Ga)},C1=function(a,b){g.oJ.call(this,b.S());
this.j=a;this.G=b;this.B=null;this.D=!1;this.I=g.kC(this.G.S())&&!this.j.isManifestless},QVa=function(a,b){var c=[],d;
for(d in a.j.j)if(a.j.j.hasOwnProperty(d)){var e=a.j.j[d];if(g.qJ(e,b||null)){var f=e.info.id,h=f,l="."+f,m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;else{e=f;var n=g.aUa.get(e);null==n&&(n=PVa[e]||PVa[e.replace(/-/g,"_")],g.aUa.set(e,n));h=n||h}c.push(new g.UC({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},RVa=function(a,b){return null!=b&&b in a.j.j?a.j.j[b]:null},SVa=function(a,b,c){var d=
[],e;
for(e in a.j.j)if(a.j.j.hasOwnProperty(e)){var f=a.j.j[e];if(g.qJ(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},D1=function(a){if(!TVa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(UVa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},E1=function(a,b,c,d,e,f,h,l){var m={};
Object.assign(m,b);Object.assign(m,a.params);Object.assign(m,c);var n={};Object.assign(n,b.Rd);a.params.Rd&&Object.assign(n,a.params.Rd);Object.assign(n,c.Rd);m.Rd=n;g.V.call(this,{F:"div",L:"caption-window",T:{id:"caption-window-"+a.id,dir:1===m.Pg?"rtl":"ltr",tabindex:"0",lang:m.lang},R:[{F:"span",L:"captions-text",T:{style:"word-wrap: normal; display: block;"}}]});this.D=[];this.ma=!1;this.u=a;this.Da=this.va=null;this.playerWidth=f;this.playerHeight=h;this.I=null;this.maxWidth=.96*f;this.Sa=.96*
h;this.j=m;this.Kb=c;this.Fa=b;this.C=this.ya("captions-text");this.jb=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");this.W=e/360*16;!l.fb("web_player_scale_font_size_for_shorts_killswitch")&&e>=d&&(this.W=f/640*16);this.type=0;this.Ua=this.W*VVa(n);a=new g.Iu(this.element,!0);g.H(this,a);a.subscribe("dragstart",this.rU,this);a.subscribe("dragmove",this.qU,this);a.subscribe("dragend",this.pU,this);this.eb=this.bb=0;b=
"";this.j.windowOpacity&&(a=D1(this.j.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");a={"background-color":b,display:!1===this.j.isVisible?"none":"","text-align":WVa[this.j.textAlign]};this.jb&&(a["border-radius"]=b?this.Ua/8+"px":"");if(this.B=2===this.u.params.Pg||3===this.u.params.Pg)b=this.element,c="vertical-rl",1===this.j.EJ&&(c="vertical-lr"),g.Dc&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.Pl(b,"-o-writing-mode",c),g.Pl(b,"-webkit-writing-mode",c),g.Pl(b,"writing-mode",
c),g.Pl(b,"text-orientation","upright"),g.Uo(b,"ytp-vertical-caption"),3===this.u.params.Pg&&(g.Pl(b,"text-orientation",""),g.Pl(b,"transform","rotate(180deg)"));g.Pl(this.element,a);switch(this.j.sj){case 0:case 1:case 2:g.Uo(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Uo(this.element,"ytp-caption-window-bottom")}},VVa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},XVa=function(a,b){var c={},d=b.background?b.background:a.j.Rd.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.Rd.backgroundOpacity;d=D1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.jb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Ua/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.W*VVa(b)+"px";d=1;e=b.color||a.j.Rd.color;if(b.color||null!=b.textOpacity)e=D1(e),d=null==b.textOpacity?a.j.Rd.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.AF&&(h=e=b.AF);var l=a.W/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.ar()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.Rd.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Mk&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.ZW&&(c.visibility="hidden");1===b.lO&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.pC||g.js,3===a.u.params.Pg?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.fl||2===b.fl||3===b.fl||4===b.fl||5===b.fl)if(g.pC)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.fl){case 4:case 3:c["text-emphasis-position"]="under left";
c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},YVa=function(a){a.I=g.th("SPAN");
g.Pl(a.I,{display:"block"});g.Uo(a.I,"caption-visual-line");a.C.appendChild(a.I)},ZVa=function(a,b){var c=g.th("SPAN");
g.Pl(c,{display:"inline-block","white-space":"pre-wrap"});g.Pl(c,XVa(a,b));c.classList.add("ytp-caption-segment");a.I.appendChild(c);c.previousElementSibling&&(g.Pl(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Pl(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},$Va=function(a,b,c){a.ma=a.ma||!!c;
var d={};Object.assign(d,a.j.Rd);Object.assign(d,c||b.j);Object.assign(d,a.Kb.Rd);(c=!a.I)&&YVa(a);for(var e=a.va&&a.Da&&g.Of(d,a.Da)?a.va:ZVa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(YVa(a),e=ZVa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.uh(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.pC||!g.$l(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.$l(n.children[2],"text-emphasis-position")&&(m=
a.B?"padding-left":"padding-bottom"),g.vf?g.Pl(e,m,"1em"):g.Pl(e,m,"0.5em")))}a.Da=d;a.va=e;a.D.push(b)},F1=function(a,b,c,d){g.oJ.call(this,a);
this.videoData=b;this.audioTrack=c;this.Qa=d;this.C=b.ax},G1=function(a,b,c,d,e,f,h,l){E1.call(this,a,b,c,d,e,f,h,l);
this.type=1},H1=function(a,b,c,d,e,f,h,l){E1.call(this,a,b,c,d,e,f,h,l);
this.type=2;this.J=[];this.V=this.N=this.Ha=0;this.Y=NaN;this.gb=0;this.Ib=null;this.Oa=new g.K(this.WZ,433,this);g.Uo(this.element,"ytp-caption-window-rollup");g.H(this,this.Oa);g.Pl(this.element,"overflow","hidden")},aWa=function(a,b){if(!b)return"";
a.B&&1!==a.u.params.EJ&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},bWa=function(a){a.J=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.ao,c=0,d=0,e=a.J.length-1;c<b&&-1<e;){var f=a.J[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.J.length<b&&(d*=b/a.J.length);a.N=d;b=Math;c=b.max;isNaN(a.Y)&&((d=a.j.To)?(e=g.th("SPAN"),g.Ah(e,"\u2013".repeat(d)),g.Pl(e,XVa(a,a.j.Rd)),a.C.appendChild(e),a.Y=e.offsetWidth,a.C.removeChild(e)):a.Y=0);d=a.C;a.V=c.call(b,a.Y,a.gb,(a.B?d.offsetHeight:d.offsetWidth)+1)},cWa=function(a,b){bWa(a);
var c=a.J.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.N-c;if(c!==a.Ha){var d=0<c&&0===a.Ha;b||isNaN(c)||d||(g.Uo(a.element,"ytp-rollup-mode"),g.No(a.Oa));g.Pl(a.C,"transform",aWa(a,c));a.Ha=c}bWa(a)},I1=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.bw.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},J1=function(a,b,c,d,e){g.bw.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},dWa=function(a){var b="_"+K1++;
return new J1(0,0x8000000000000,0,b,a)},fWa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Ze){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=eWa(l.textContent,n.textContent,p.textContent,f.textContent,h);return new I1(a,b,e,c,l,d,m)}switch(m.Ze){case 9:case 10:m.fl=1;break;case 11:m.fl=2;break;case 12:m.fl=3;break;case 13:m.fl=4;break;case 14:m.fl=5}return new I1(a,b,e,c,l.textContent||"",d,m)},eWa=function(a,b,c,d,e){var f=g.ar(),h=
f?g.th("DIV"):g.th("RUBY"),l=g.th("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.th("DIV"):g.th("RP");a.textContent=b;h.appendChild(a);b=f?g.th("DIV"):g.th("RT");b.textContent=c;h.appendChild(b);c=e.Ze;if(10===c||11===c||12===c||13===c||14===c)if(g.Pl(b,"text-emphasis-style","filled circle"),g.Pl(b,"text-emphasis-color","currentcolor"),g.Pl(b,"webkit-text-emphasis","filled circle"),11===e.Ze||13===e.Ze)g.Pl(b,"webkit-text-emphasis-position","under left"),g.Pl(b,"text-emphasis-position","under left");c=!0;if(4===e.Ze||7===e.Ze||12===e.Ze||
14===e.Ze)g.Pl(h,"ruby-position","over"),g.Pl(h,"-webkit-ruby-position","before");else if(5===e.Ze||6===e.Ze||11===e.Ze||13===e.Ze)g.Pl(h,"ruby-position","under"),g.Pl(h,"-webkit-ruby-position","after"),c=!1;e=f?g.th("DIV"):g.th("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.Pl(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.Pl(f,"display","none"),f=f.nextElementSibling,g.Pl(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Pl(h.lastElementChild,"display","none"),d?(g.Pl(h,"padding-top","0.6em"),g.Pl(f,"top","0")):(g.Pl(h,"padding-bottom","0.6em"),g.Pl(f,"bottom","0")));return h},L1=function(){g.G.apply(this,arguments)},M1=function(a){L1.call(this);
this.C=a;this.pens={};this.N={};this.V={};this.D="_"+K1++;this.J={};this.B=this.j=null;this.I=!0},N1=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},O1=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},P1=function(a,b){a=N1(a,b);
return void 0!==a?a:null},R1=function(a,b){a=a.getAttribute(b);
if(null!=a)return Q1.test(a),a},gWa=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.V[d]:a.C);a=P1(b,"mh");null!=a&&(c.bv=a);a=P1(b,"ju");null!=a&&(c.textAlign=a);a=P1(b,"pd");null!=a&&(c.Pg=a);a=P1(b,"sd");null!=a&&(c.EJ=a);a=R1(b,"wfc");null!=a&&(c.windowColor=a);b=N1(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},hWa=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.N[d]);a=P1(b,"ap");null!=a&&(c.sj=a);a=N1(b,"cc");null!=a&&(c.To=a);a=N1(b,"ah");null!=a&&(c.wi=a);a=N1(b,"rc");null!=a&&(c.ao=a);b=N1(b,"av");null!=b&&(c.il=b);return c},iWa=function(a,b,c,d){var e={};
Object.assign(e,hWa(a,b));Object.assign(e,gWa(a,b));d?g.Of(e,a.C)?(d=a.D,e=a.C):d="_"+K1++:d=b.getAttribute("id")||"_"+K1++;a=N1(b,"t")+c;b=N1(b,"d")||0x8000000000000;if(2===e.Pg||3===e.Pg)c=e.ao,e.ao=e.To,e.To=c;return new J1(a,b,0,d,e)},S1=function(a){L1.call(this);
this.I=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},T1=function(a){a=g.Mg(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},jWa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.ao=a);b=b.ccColCount;void 0!==b&&(f.To=b);if(2===f.Pg||3===f.Pg)b=f.ao,f.ao=f.To,f.To=b;return new J1(c,d,0,e,f)},V1=function(){this.B=this.time=this.mode=this.u=0;
this.C=new U1(this);this.D=new U1(this);this.j=[];this.clear()},lWa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Vq:a,
Qo:b,result:0};a=kWa[a];b=kWa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Qo===d;if(d)return{Vq:a,Qo:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Vq:a,Qo:b,result:2};return{Vq:a,Qo:b,result:3}},nWa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.B&&a.reset(),a.C.u.clear(),a.D.u.clear()):(a.B=0,mWa(a.C,b,c,d))},oWa=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.r(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?nWa(a,d.LM,d.MM,b):1===d.type&&a.u&496&&mWa(a.D,d.LM,d.MM,b);a.j.length=0},W1=function(){this.type=0},X1=function(){this.state=this.Qo=this.Vq=0},pWa=function(){this.timestamp=this.j=0},Y1=function(a){this.D=a;
this.B=[];this.j=this.u=this.row=0;this.style=new W1;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new pWa}},Z1=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var t=q.timestamp;t<e&&(e=t);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.j||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.j,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===q)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},uWa=function(a,b){switch(a){case 0:return qWa[(b&127)-32];
case 1:return rWa[b&15];case 2:return sWa[b&31];case 3:return tWa[b&31]}return 0},$1=function(a){return a.B[a.row][a.u]},a2=function(a,b,c){2<=b&&1<a.u&&(--a.u,$1(a).j=0);
var d=$1(a);d.timestamp=a.D.time+0;d.j=uWa(b,c);32>a.u&&a.u++},vWa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},b2=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},c2=function(a){a.row=0<a.j?a.j:1;
a.u=1;b2(a,0,15)},d2=function(a){this.B=a;
this.D=0;this.style=new W1;this.I=new Y1(this.B);this.J=new Y1(this.B);this.text=new Y1(this.B);this.u=this.I;this.C=this.J;this.j=this.u},e2=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(Z1(d,c),c2(a.u),c2(a.C),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.B.mode=1<<d.C;e?d.u=1:d.j!==b&&(d.j>b?(Z1(d,c),b2(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},wWa=function(a){a.style.set(1);
a.j=a.C;a.j.j=0;a.j.style=a.style;a.B.mode=1<<a.j.C},xWa=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.B.mode=1<<a.j.C},U1=function(a){this.j=a;
this.D=0;this.B=new d2(this.j);this.I=new d2(this.j);this.u=new X1;this.C=this.B},mWa=function(a,b,c,d){a.u.update();
b=lWa(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Vq;c=b.Qo;if(32<=e||!e)a.j.mode&a.j.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.j,b&96&&a2(a,0,b),c&96&&a2(a,0,c),0!==b&&0!==c&&3===a.style.type&&Z1(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.Vq=e,b.Qo=c,b.state=2,b=e&8?a.I:a.B,a.C=b,a.j.mode=1<<(a.D<<2)+(b.D<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.D<<2)+(b.D<<1)+(4!==b.style.type?1:0))&a.j.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;vWa(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));b2(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:a2(b.j,0,32);break a;case 48:57===c?(d=b.j,$1(d).j=0,32>d.u&&d.u++):a2(b.j,1,c&15)}break;case 2:c&32&&a2(b.j,2,c&31);break;case 3:c&32&&a2(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:wWa(b);
break;case 33:d=b.j;1<d.u&&(--d.u,$1(d).j=0);break;case 36:d=b.j;b=$1(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:e2(b,2,d);break;case 38:e2(b,3,d);break;case 39:e2(b,4,d);break;case 40:a2(b.j,0,32);break;case 41:b.style.set(2);b.j=b.u;b.j.j=0;b.j.style=b.style;b.B.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);c2(d);xWa(b);break;case 43:xWa(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:Z1(a,d)}b2(a,
0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;Z1(a,d);vWa(a,b,b+1,a.j-1);b2(a,a.row,1)}break;case 46:b2(b.C,0,15);break;case 47:Z1(b.u,d),b.C.updateTime(b.B.time+0),d=b.C,b.C=b.u,b.u=d,wWa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.u+=c&3)&&(d.u=32)}}},yWa=function(){},f2=function(a,b,c){this.trackData=a;
this.I=c;this.version=this.D=this.B=this.byteOffset=0;this.j=new DataView(this.trackData);this.u=[]},g2=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},h2=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},i2=function(a,b){L1.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.j=new V1;this.j.u=1<<this.track},j2=function(a){if("string"===typeof a)return!1;
a=new f2(a,8,0);return zWa(a)},zWa=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==h2(a))return!1;
a.version=g2(a);if(1<a.version)return!1;g2(a);g2(a);g2(a);return!0},k2=function(){L1.call(this)},AWa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.Mk=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new I1(b,c,d,e.id,p.nodeValue,f||0<n,g.Jf(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);AWa(a,b,c,d,e,!0,p,q,m)}}},l2=function(a){var b=a.split(":");
a=0;b=g.r(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},BWa=function(a,b,c,d){d=Object.assign({bv:0},d);
return new J1(a,b,c,"_"+K1++,d)},m2=function(a,b){g.G.call(this);
this.G=a;this.U=b;this.j=null;this.u=this.G.xB()},HWa=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.u&&b){var f=e,h=CWa(a,b,d),l=[];try{for(var m=g.r(h),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,t=p.vJ;l="string"!==typeof q?l.concat(DWa(a,c,q,t,f)):"WEBVTT"===q.substring(0,6)?l.concat(EWa(a,q,t)):l.concat(FWa(a,c,q,t))}var v=l}catch(x){g.R(x),a.clear(),v=[]}if(0!==v.length)return v}b=GWa(b);if(!b)return[];try{return"string"!==typeof b?DWa(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?EWa(a,b,d):FWa(a,c,b,d)}catch(x){return g.R(x),a.clear(),[]}},GWa=function(a){if("string"===
typeof a||j2(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.cy(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.Px(a)},CWa=function(a,b,c){if("string"===typeof b||j2(b))return[{trackData:b,
vJ:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.lsa(d);if(a.u&&e){var f=g.esa(e);e=e.j;f&&e&&a.u.Tz(e,f)}f=g.ly(d,1835295092);if(!f||!f.length||!f[0].size)return[];a=[];f=g.r(f.entries());for(e=f.next();!e.done;e=f.next()){var h=g.r(e.value);e=h.next().value;h=h.next().value;h=new Uint8Array(b,h.dataOffset,h.size-(h.dataOffset-h.offset));h=g.Px(h);a.push({trackData:h,vJ:c+1E3*e})}IWa(d,a,c);return a=a.filter(function(l){return!!l.trackData})},IWa=function(a,
b,c){var d=g.cy(a,0,1836476516),e=9E4;
d&&(e=g.dy(d)||9E4);d=0;var f=g.ly(a,1836019558);f=g.r(f.entries());for(var h=f.next();!h.done;h=f.next()){var l=g.r(h.value);h=l.next().value;l=l.next().value;h<b.length&&(l=g.cy(a,l.dataOffset,1953653094))&&(l=g.cy(a,l.dataOffset,1952867444))&&(l=g.jy(l)/e*1E3,0===h&&(d=l),b[h].vJ=l-d+c||c*h*1E3)}},DWa=function(a,b,c,d,e){if(!j2(c))throw Error("Invalid binary caption track data");
a.j||(a.j=new i2(e,b));return a.j.u(c,d)},EWa=function(a,b,c){a.j||(a.j=new k2);
a=a.j.u(b,c);.01>Math.random()&&g.Wu(Error("Deprecated subtitles format in web player: WebVTT"));return a},FWa=function(a,b,c,d){if("{"===c[0])try{return a.j||(a.j=new S1(JWa(b))),a.j.u(c,d)}catch(f){return g.R(f),[]}var e=g.PZ(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.j||(a.j=new M1(JWa(b),a.U)),a.j.u(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},JWa=function(a){var b=
{};
if(a=g.XC(a))b.lang=a,g.sSa.test(a)&&(b.Pg=1);return b},p2=function(a){g.lJ.call(this,a);
var b=this;this.G=a;this.U=this.G.S();this.videoData=this.G.getVideoData();this.eb=this.G.Wa();this.C={Rd:{}};this.D={Rd:{}};this.oa=[];this.N={};this.Fa={};this.W=!1;this.Kb=g.VD(this.videoData);this.Ua=g.lCa(this.videoData,this.G);this.Ib=!!this.videoData.captionTracks.length;this.Zb=!!this.videoData.Jc;this.Ha="3"===this.U.controlsType;this.u=this.I=this.J=this.Da=this.bb=null;this.Oa=new m2(this.G,this.U);this.j=null;this.Y=new g.Dz(this);this.Sa=new g.V({F:"div",L:"ytp-caption-window-container",
T:{id:"ytp-caption-window-container"}});var c=null,d=g.Bp("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.pp(d));this.storage=c;var e;this.gb=!(null==(e=a.Jd())||!e.Mz());this.B=KWa(this);this.V=!this.B&&this.Ha&&this.gb&&this.Ua;g.H(this,this.Oa);this.B?this.va=this.ma=null:(this.ma=new g.Lo(this.XJ,void 0,this),g.H(this,this.ma),this.va=new g.K(this.q0,2E3,this),g.H(this,this.va));g.H(this,this.Y);this.U.K("caption_window_container_killswitch")||g.YI(this.player,this.Sa.element,4);g.H(this,
this.Sa);this.B||this.Y.P(a,"resize",this.ZJ);(this.jb=!g.xu()&&!this.G.isFullscreen()&&!this.B&&!this.V&&!this.U.K("switch_captions_to_track_tag_when_fullscreen_api_unavailable_killswitch"))&&this.Y.P(a,"resize",this.gZ);this.Y.P(a,"onPlaybackAudioChange",this.uY);this.Y.P(a,g.dw("captions"),function(f){b.onCueRangeEnter(f)});
this.Y.P(a,g.ew("captions"),function(f){b.onCueRangeExit(f)});
n2(this,o2(this)||{})},NWa=function(a){if(1===a.U.bb||1===a.videoData.pw||"alwayson"===g.FD(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.player.getAudioTrack().u;if(2===a.U.bb){var c;g.mC(a.U)?c=LWa(a):c=MWa(a,"module-enabled");if(null!=c)return!!c}c=y1(a.player.getAudioTrack(),z1(a.U));var d=g.FD(a.videoData,"yt:cc");if(void 0===q2(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===b||"on"===g.FD(a.videoData,"yt:cc")},r2=function(a,b){if(a.j&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.j||"FORCED_ON"===a.u},q2=function(a){var b=void 0,c=g.Fr(g.Er.getInstance(),65);
if(g.mC(a.U)&&null!=c){if(null!=LWa(a))return!1;b=!c}return b},OWa=function(a){var b;
a.Kb?b=new F1(a.U,a.videoData,a.player.getAudioTrack(),a.player):a.Ua?b=new C1(a.videoData.j,a.player):a.Ib?b=new g.pJ(a.U,a.videoData,a.player.getAudioTrack()):b=new g.rJ(a.U,a.videoData.Jc,a.videoData.videoId,g.bxa(a.videoData),a.videoData.wl);return b},t2=function(a,b){if(a.u){if(a.I&&a.I.C)return a.I.C;
b||(b=a.Zb?!1:a.Ib?!1:!0);b=g.mJ(a.u.u,b);for(var c=[a.videoData.captionsLanguagePreference,a.U.captionsLanguagePreference,g.FD(a.videoData,"yt:cc_default_lang")],d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(g.XC(b[e])===c[d])return b[e];return a.I&&a.I.B?a.I.B:(c=b.find(function(f){return f.isDefault}))?c:b[0]||s2(a)}return null},s2=function(a){return a.I&&a.I.j},u2=function(a){var b=s2(a);
return!!b&&a.j===b},PWa=function(a){var b=y1(a.player.getAudioTrack(),z1(a.U)),c;
"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=t2(a,a.W):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&r2(a)?c=s2(a):q2(a)||a.W||NWa(a)?c=t2(a,a.W):r2(a)&&(c=s2(a));if(a.B||a.V){var d=g.mJ(a.u.u,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.th("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.VC(f));h.setAttribute("srclang",g.XC(f));h.setAttribute("id",f.toString());a.V||h.setAttribute("src",a.u.Br(f,"vtt"));f===c&&h.setAttribute("default","1");b.push(h)}c=a.G.Jd();c.hx(b);c=c.nf();
a.gb&&a.Y.P(c.textTracks,"change",a.D_)}else!a.j&&c&&v2(a,c),a.player.Ma("onCaptionsTrackListChanged"),a.player.Ma("onApiChange")},QWa=function(a,b){var c=a.G.Jd().nf().textTracks;
a=a.j.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},v2=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.W=c,a.W&&(g.mC(a.U)?w2(a,!!b):x2(a,"module-enabled",!!b)));a.j=b;r2(a)&&(a.j=s2(a));a.load()},SWa=function(a,b){if(b instanceof J1){var c=a.N[b.id];
c&&c.u!==b&&(c.dispose(),delete a.N[b.id],c=null);c||(c=RWa(a,b))&&(a.N[b.id]=c)}else c=b.windowId,a.Fa[c]||(a.Fa[c]=[]),a.Fa[c].push(b)},TWa=function(a,b){a.U.K("caption_window_container_killswitch")?g.YI(a.player,b,4):a.Sa.element.appendChild(b)},RWa=function(a,b){var c=a.eb.getVideoContentRect(!0).height,d=a.eb.getVideoContentRect(!0).width;
if(!c||!d)return null;var e=a.j?g.XC(a.j):null;e&&g.sSa.test(e)&&(b.params.Pg=1);e=a.eb.getPlayerSize();switch(null!=b.params.bv?b.params.bv:1<b.j.length?1:0){case 1:return new G1(b,a.C,a.D,d,c,e.width,e.height,a.U.experiments);case 2:return new H1(b,a.C,a.D,d,c,e.width,e.height,a.U.experiments);default:return new E1(b,a.C,a.D,d,c,e.width,e.height,a.U.experiments)}},n2=function(a,b,c){c=void 0===c?!1:c;
var d=y2.Rd;a.C={};Object.assign(a.C,y2);a.C.Rd={};Object.assign(a.C.Rd,d);a.D={Rd:{}};var e=b.backgroundOverride?a.D:a.C,f=b.background||d.background;Q1.test(f);e.Rd.background=f;e=b.colorOverride?a.D:a.C;f=b.color||d.color;Q1.test(f);e.Rd.color=f;e=b.windowColorOverride?a.D:a.C;f=b.windowColor||y2.windowColor;Q1.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.C;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Rd.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.D:a.C;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.Rd.fontSizeIncrement=f;f=b.fontStyleOverride?a.D:a.C;e=b.fontStyle;null==e&&(e=d.bold&&d.Mk?3:d.bold?1:d.Mk?2:0);f=f.Rd;switch(e){case 1:f.bold=!0;delete f.Mk;break;case 2:delete f.bold;f.Mk=!0;break;case 3:f.bold=!0;f.Mk=!0;break;default:delete f.bold,delete f.Mk}e=b.textOpacityOverride?a.D:a.C;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Rd.textOpacity=f;e=b.windowOpacityOverride?a.D:a.C;f=b.windowOpacity;null==f&&(f=y2.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.D:a.C;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Rd.charEdgeStyle=f;e=b.fontFamilyOverride?a.D:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Rd.fontFamily=f;a.loaded&&a.ZJ();c&&(a.U.K("web_player_local_storage_for_captions_setting_killswitch")?x2(a,"display-settings",b):g.Bv("yt-player-caption-display-settings",b,2592E3))},z2=function(a,b,c){b&&!a.J?(b=dWa({Pg:0,
lang:"en-GB"}),a.J=[b,new I1(b.start,b.end-b.start,0,b.id,null!=c?c:"Captions look like this")],a.player.Yd(a.J)):!b&&a.J&&(UWa(a,a.J),a.J=null)},UWa=function(a,b){a.player.Og(b);
b=g.r(b);for(var c=b.next();!c.done;c=b.next())g.Wb(a.oa,c.value);g.Mo(a.ma)},MWa=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},x2=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}},w2=function(a,b){a.G.isInline()||g.Bv("yt-player-sticky-caption",b,2592E3)},LWa=function(a){if(!a.G.isInline())return g.Cv("yt-player-sticky-caption")},o2=function(a){return a.U.K("web_player_local_storage_for_captions_setting_killswitch")?MWa(a,"display-settings"):g.Cv("yt-player-caption-display-settings")},KWa=function(a){var b,c=!(null==(b=a.G.Jd())||!b.Lz());
return a.Ha&&c&&!a.Ua};
g.bO.prototype.Nx=g.ca(29,function(a){var b=2;this.Fa.has(a)?b=0:g.vFa(this,a)&&(b=1);return b});
g.LQ.prototype.Nx=g.ca(28,function(a){return this.qd.Nx(a)});
g.bO.prototype.Tz=g.ca(27,function(a,b){this.Da.set(a,b)});
g.LQ.prototype.Tz=g.ca(26,function(a,b){this.qd.Tz(a,b)});
g.GJ.prototype.au=g.ca(25,function(){for(var a=g.mh(document,"track",void 0,this.j),b=0;b<a.length;b++)g.xh(a[b])});
g.MN.prototype.au=g.ca(24,function(){this.mediaElement.au()});
g.GJ.prototype.Mz=g.ca(23,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.MN.prototype.Mz=g.ca(22,function(){return this.mediaElement.Mz()});
g.GJ.prototype.Lz=g.ca(21,function(){return!!this.j.textTracks});
g.MN.prototype.Lz=g.ca(20,function(){return this.mediaElement.Lz()});
g.GJ.prototype.hx=g.ca(19,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.MN.prototype.hx=g.ca(18,function(a){this.mediaElement.hx(a)});
g.oJ.prototype.CI=g.ca(17,function(){return!1});
g.oJ.prototype.Kp=g.ca(16,function(){});
g.pJ.prototype.Kp=g.ca(15,function(a,b,c){var d=this;this.isDisposed();b=this.Br(a,b);this.Bo();this.j=g.Oq(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.rJ.prototype.Kp=g.ca(14,function(a,b,c){var d=this;this.isDisposed();b=this.Br(a,b);this.Bo();this.j=g.Oq(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
var PVa={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",
as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgn:"Western Balochi",bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",
bla:"Siksika",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",
chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",
dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fulah",
ff_Adlm:"Fulah (Adlam)",ff_Latn:"Fulah (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",
grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",
io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",
km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Lahnda",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",
lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",
mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",
nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",
pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Sakha",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",
sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",
smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",
tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",
uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",
zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};A1.prototype.contains=function(a){a=g.fc(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
A1.prototype.length=function(){return this.segments.length/2};
g.w(B1,g.G);g.k=B1.prototype;g.k.ea=function(){g.G.prototype.ea.call(this);this.B&&this.B.cancel()};
g.k.DC=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.wd();var b=this.j;this.j=g.Nb(this.W.Cn(a).j);b!==this.j&&this.V&&this.V()};
g.k.reset=function(){this.C=new A1;this.I=-1;this.B&&(this.B.cancel(),this.B=null)};
g.k.SO=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.Ko(a);if(a&&!this.B&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.Gw(a);var b;if(null==(b=this.player.getVideoData())?0:b.enableServerStitchedDai){var c=this.player.xB();if(c){var d=a.j[0].Ga;if(b=c.zj(a.j[0].B,d,a.j[0].j.info.id,3))if(c=c.Nx(d),0===c)b&&(a.B=new g.tx(b));else if(2===c){this.J.start();NVa(this)&&this.seekTo(this.player.getCurrentTime());return}}}a.j[0].duration?(this.C.contains(a.j[0].Ga)||
OVa(this,a),this.j=g.Nb(a.j)):!this.U.K("force_caption_seek_for_live_killswitch")&&NVa(this)&&this.seekTo(this.player.getCurrentTime())}this.J.start()};
g.w(C1,g.oJ);g.k=C1.prototype;g.k.Kp=function(a,b,c){var d=this;this.Bo();b=RVa(this,a.getId());b||(b=a.languageCode,b=this.j.isManifestless?SVa(this,b,"386"):SVa(this,b));if(b){var e=1E3*(b.index.getStartTimeInPeriod(b.index.getFirstSegmentNumber())-b.index.getStartTime(b.index.getFirstSegmentNumber())),f=new g.jCa(this.U);this.B=new B1(f,this.G,b,function(h,l){c(h,a,l,e)},this.I||g.mz(b.info),function(){d.B&&d.B.reset();
d.D=!0})}};
g.k.CI=function(){var a=this.D;this.D=!1;return a};
g.k.Vu=function(a){var b=this.I?[new g.UC({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.UC({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.j.isManifestless?QVa(this,"386"):QVa(this);b=g.r(b);for(var c=b.next();!c.done;c=b.next())g.nJ(this.u,c.value);a()};
g.k.Bo=function(){this.B&&(this.B.dispose(),this.B=null)};
g.k.Br=function(){return""};
var Q1=/^#(?:[0-9a-f]{3}){1,2}$/i,UVa=/#(.)(.)(.)/,TVa=/^#(?:[0-9a-f]{3}){1,2}$/i;var WVa=["left","right","center","justify"];g.w(E1,g.V);g.k=E1.prototype;g.k.rU=function(a,b){var c=g.gm(this.element,this.element.parentElement);this.bb=a-c.x;this.eb=b-c.y;g.Uo(this.element,"ytp-dragging")};
g.k.qU=function(a,b){var c=g.im(this.element);a=a-this.bb-.02*this.playerWidth;var d=b-this.eb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.Mg(e,0,2));var f=(d+c.height/2)/this.Sa*3;f=Math.floor(g.Mg(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.Mg(a,0,1);c=(d+f/2*c.height)/this.Sa;c=100*g.Mg(c,0,1);this.u.params.sj=b;this.u.params.il=c;this.u.params.wi=a;this.j.sj=b;this.j.il=c;this.j.wi=a;this.Fa.sj=b;this.Fa.il=c;this.Fa.wi=a;this.SQ()};
g.k.pU=function(){g.Wo(this.element,"ytp-dragging")};
g.k.SQ=function(){this.Mv(this.D)};
g.k.getType=function(){return this.type};
g.k.Mv=function(a){var b=Math.min(this.IN(),this.maxWidth),c=this.HN(),d="";3===this.u.params.Pg&&(d="rotate(180deg)");g.Pl(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.lF(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.j.wi+2;d=this.j.sj;switch(d){case 0:case 3:case 6:(b=this.j.Rd.fontSizeIncrement)&&0<b&&2!==this.j.Pg&&3!==
this.j.Pg&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.j.il+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Pl(this.element,
a)};
g.k.lF=function(a){var b;for(b=0;b<a.length&&a[b]===this.D[b];b++);if(this.ma||this.D.length>b)b=0,this.ma=!1,this.D=[],this.I=this.Da=this.va=null,g.vh(this.C);for(;b<a.length;b++)$Va(this,a[b])};
g.k.IN=function(){return 0};
g.k.HN=function(){return 0};
g.k.toString=function(){return g.V.prototype.toString.call(this)};g.w(F1,g.oJ);F1.prototype.Kp=function(a,b,c){LVa(this.videoData.videoId,a.vssId,c)};
F1.prototype.Vu=function(a){if(this.audioTrack)for(var b=g.r(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.nJ(this.u,c.value);a()};g.w(G1,E1);G1.prototype.lF=function(a){var b=this.u.j;E1.prototype.lF.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,VWa);var e=c.j;var f=d}$Va(this,c,d)}};
var VWa={ZW:!0};g.w(H1,E1);g.k=H1.prototype;g.k.SQ=function(){g.Oo(this.Oa)};
g.k.WZ=function(){g.Wo(this.element,"ytp-rollup-mode");this.Mv(this.Ib,!0)};
g.k.HN=function(){return this.B?this.V:this.N};
g.k.IN=function(){return this.B?this.N:this.V};
g.k.Mv=function(a,b){this.Ib=a;if(this.u.params.ao){for(var c=0,d=0;d<this.D.length&&c<a.length;d++)this.D[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.D.concat(a.slice(c)));this.gb=this.V;this.N=this.V=0;E1.prototype.Mv.call(this,a);cWa(this,b)}E1.prototype.Mv.call(this,a)};g.w(I1,g.bw);I1.prototype.toString=function(){return g.bw.prototype.toString.call(this)};g.w(J1,g.bw);J1.prototype.toString=function(){return g.bw.prototype.toString.call(this)};
var K1=0;g.w(L1,g.G);L1.prototype.u=function(){return[]};
L1.prototype.reset=function(){};g.w(M1,L1);M1.prototype.reset=function(){this.J={};this.B=this.j=null;this.I=!0};
M1.prototype.u=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.r(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.r(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=O1(a,"b");
null!=l&&(h.bold=l);l=O1(a,"i");null!=l&&(h.Mk=l);l=O1(a,"u");null!=l&&(h.underline=l);l=P1(a,"et");null!=l&&(h.charEdgeStyle=l);l=P1(a,"of");null!=l&&(h.offset=l);l=R1(a,"bc");null!=l&&(h.background=l);l=R1(a,"ec");null!=l&&(h.AF=l);l=R1(a,"fc");null!=l&&(h.color=l);l=P1(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=N1(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=N1(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=N1(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=P1(a,"rb");null!=l&&10!==l&&0!==
l&&(h.Ze=10<l?l-1:l);a=P1(a,"hg");null!=a&&(h.lO=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.V[c]=gWa(this,a);break;case "wp":c=a.getAttribute("id"),this.N[c]=hWa(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.r(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=iWa(this,a,b,!1);(a=this.J[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.J[this.j.id]=this.j;d.push(this.j);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.D;h=
!!O1(a,"a");l=(N1(a,"t")||0)+l;var m=N1(a,"d")||5E3;h||(!this.I&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var q=Array.from(a.childNodes);q.length&&(this.I=null!=a.getAttribute("d"));for(var t=0;t<q.length;t++){var v=q[t],x=void 0;0<t&&(h=!0);var y=void 0;1===v.nodeType&&(y=v);if(y&&"s"===y.tagName){if((v=(v=y.getAttribute("p"))?this.pens[v]:null)&&v.Ze&&(1===v.Ze?(v=q.slice(t,t+4),
4===v.length&&(x=fWa(l,m,f,h,n,v,this.pens),t+=3)):x=fWa(l,m,f,h,n,[y],this.pens)),!x){var z=y;x=l;y=m;v=f;var E=h,I=n,J=z.textContent?z.textContent:"",L=z.getAttribute("p");L=L?this.pens[L]:null;z=N1(z,"t")||0;x=new I1(x+z,y-z,I,v,J,E,L)}}else x=new I1(l,m,n,f,v.textContent||"",h,p);c.push(x);this.B=x}if(0<c.length)for(c[0].windowId===this.D&&(this.j=iWa(this,a,b,!0),d.push(this.j)),a=g.r(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];return b};var WWa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.w(S1,L1);S1.prototype.reset=function(){this.B.clear()};
S1.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.r(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.Mk=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.AF=T1(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=T1(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=T1(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.Ze=10<h?h-1:h,f.fl=WWa.get(f.Ze));e.hgHorizGroup&&(f.lO=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.r(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.I),void 0!==e.mhModeHint&&(f.bv=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Pg=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.EJ=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=T1(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.r(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),void 0!==e.ahHorPos&&
(f.wi=e.ahHorPos),void 0!==e.apPoint&&(f.sj=e.apPoint),void 0!==e.avVerPos&&(f.il=e.avVerPos),void 0!==e.ccCols&&(f.To=e.ccCols),void 0!==e.rcRows&&(f.ao=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.r(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=jWa(this,l,d,e,f),a.push(d),this.B.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+K1++,h=jWa(this,l,d,e,f),a.push(h),this.B.set(f,h));0===e&&(e=5E3);h=this.B.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,q=null;l.pPenId&&(q=this.j.get(l.pPenId));for(l=0;l<p.length;l++){var t=p[l],v=t.utf8;if(v){var x=t.tOffsetMs||0,y=null;t.pPenId&&(y=this.j.get(t.pPenId));if(2===(null!=h.params.bv?h.params.bv:1<h.j.length?1:0)&&m&&"\n"===v)continue;if(t=y&&1===y.Ze)if(t=l,t+3>=p.length||!p[t+1].pPenId||!p[t+2].pPenId||!p[t+3].pPenId)t=!1;else{var z=p[t+1].pPenId;(z=this.j.get(z))&&z.Ze&&2===z.Ze?(z=p[t+2].pPenId,z=this.j.get(z),!z||!z.Ze||3>z.Ze?t=!1:(z=p[t+3].pPenId,t=(z=this.j.get(z))&&
z.Ze&&2===z.Ze?!0:!1)):t=!1}if(t){x=p[l+1].utf8;t=p[l+3].utf8;z=p[l+2].utf8;var E=this.j.get(p[l+2].pPenId);v=eWa(v,x,z,t,E);m=new I1(d,e,n,f,v,m,y);l+=3}else m=new I1(d+x,e-x,n,h.id,v,m,y||q);m&&(a.push(m),h.j.push(m))}m=!0}}}b=a}else b=[];return b};V1.prototype.clear=function(){this.B=this.time=this.mode=0;this.j=[];this.reset()};
V1.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var kWa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];W1.prototype.set=function(a){this.type=a};
W1.prototype.get=function(){return this.type};
X1.prototype.clear=function(){this.state=0};
X1.prototype.update=function(){this.state=2===this.state?1:0};
X1.prototype.isValid=function(){return 0!==this.state};
X1.prototype.matches=function(a,b){return this.isValid()&&a===this.Vq&&b===this.Qo};
pWa.prototype.reset=function(){this.timestamp=this.j=0};
Y1.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
Y1.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
Y1.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.u=this.row=1};
var qWa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],rWa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],sWa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],tWa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];d2.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.u=this.I;this.C=this.J;this.j=this.u;var c=(a<<2)+(b<<1);this.I.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
U1.prototype.reset=function(a){this.D=a;this.u.clear();this.C=this.B;this.B.reset(a,0);this.I.reset(a,1)};yWa.prototype.C=function(){};g.w(f2,yWa);f2.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+K1++;c=c/1E3-this.I;d=d/1E3-this.I;a=new J1(c,d-c,5,f,{textAlign:0,sj:0,wi:2.5*b,il:5.33*a});e=new I1(c,d-c,5,f,e);this.u.push(a);this.u.push(e)}};
g.w(i2,L1);i2.prototype.u=function(a){a=new f2(a,a.byteLength,this.B);if(zWa(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.B=h2(a)*(1E3/45):1===a.version&&(a.B=4294967296*h2(a)+h2(a)),a.D=g2(a);0<a.D;a.D--){var b=g2(a),c=g2(a),d=g2(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.B,type:this.track,LM:c,MM:d,order:b.j.length}))}oWa(this.j,a);return a.u}return[]};
i2.prototype.reset=function(){this.j.clear()};g.w(k2,L1);
k2.prototype.u=function(a,b){var c=[];a=a.split(XWa);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!YWa.test(e)){var h=A2.exec(e);if(h&&4<=h.length){var l=l2(h[1]),m=l2(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var t=null,v="";n=g.r(n);for(var x=n.next();!x.done;x=n.next())if(x=x.value.split(":"),2===x.length){var y=x[1];switch(x[0]){case "line":x=y.split(",");x[0].endsWith("%")&&(p=x[0],h.il=Number.parseInt(p,10),2===x.length&&(q=x[1].trim()));break;case "position":x=
y.split(",");t=x[0];h.wi=Number.parseInt(t,10);2===x.length&&(v=x[1].trim());break;case "align":switch(y){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!t)switch(h.textAlign){case 0:h.wi=0;break;case 1:h.wi=100;break;case 2:h.wi=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(v){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.sj=q}e=e.substring(A2.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");v=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=BWa(l,m,5,v),m=new I1(l,m,5,f.id,h,!1,g.Jf(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(ZWa),1===q.length?(h=5,v=BWa(l,m,h,v)):(p=h=6,v=Object.assign({To:32},v),v=new J1(l,m,p,"_"+K1++,v)),c.push(v),p=l,t=0;t<q.length;t++)n=q[t],0===t%2?(x=g.PZ("<html>"+n+"</html>"),x.getElementsByTagName("parsererror").length?
(y=x.createElement("span"),y.appendChild(x.createTextNode(n))):y=x.firstChild,AWa(this,p,m-(p-l),h,v,0<t,y,e,c)):p=l2(n)+f}A2.lastIndex=0}}return c};
var YWa=/^NOTE/,XWa=/(?:\r\n|\r|\n){2,}/,A2=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),ZWa=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.ON.SB(k2,{u:"wvppt"});g.w(m2,g.G);m2.prototype.clear=function(){this.j&&this.j.dispose();this.j=null};
m2.prototype.reset=function(){this.j&&this.j.reset()};
m2.prototype.ea=function(){g.G.prototype.ea.call(this);this.clear()};var y2={windowColor:"#080808",windowOpacity:0,textAlign:2,sj:7,wi:50,il:100,Rd:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.w(p2,g.lJ);g.k=p2.prototype;g.k.ea=function(){if(this.B||this.V){var a=this.G.Jd();a&&!a.isDisposed()&&a.au()}else z2(this,!1);g.lJ.prototype.ea.call(this)};
g.k.Ls=function(){if(this.Ha)return this.B||this.V;var a=y1(this.player.getAudioTrack(),z1(this.U));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?r2(this):q2(this)||r2(this)?!0:NWa(this)};
g.k.load=function(){var a=this;g.lJ.prototype.load.call(this);var b=!this.U.K("web_player_captions_track_list_changed_killswitch");this.I=this.player.getAudioTrack();this.u?(this.j&&(this.Oa.clear(),this.B?QWa(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.Kp(this.j,"json3",function(c,d,e,f){c&&(a.u.CI()&&(a.oa=[],a.G.Mf("captions"),g.Mo(a.ma),a.Oa.reset()),c=HWa(a.Oa,c,d,e,f),a.player.Yd(c,void 0,a.Ua),!a.W||a.V||u2(a)||g.$B(a.U)||g.RB(a.U)||(g.Po(a.va),c=dWa({sj:0,wi:5,il:5,ao:2,textAlign:0,
Pg:0,lang:"en-GB"}),a.Da=[c],d=["Click "," for settings"],a.bb||(e=new g.pG(g.GG()),g.H(a,e),a.bb=e.element),e=c.end-c.start,(f=g.VC(a.j))&&a.Da.push(new I1(c.start,e,0,c.id,f)),a.Da.push(new I1(c.start,e,0,c.id,d[0]),new I1(c.start,e,0,c.id,a.bb,!0),new I1(c.start,e,0,c.id,d[1],!0)),a.player.Yd(a.Da),g.No(a.va)),!a.W||a.V||u2(a)||(g.mC(a.U)?w2(a,!0):x2(a,"module-enabled",!0),a.I&&(a.I.C=a.j),a.player.Xs()),a.W=!1)}),!b||this.B||this.V||u2(this)||this.player.Ma("captionschanged",g.WC(this.j))),b||
(this.j&&!u2(this)?this.player.Ma("captionschanged",g.WC(this.j)):this.player.Ma("onCaptionsTrackListChanged"))):(this.u=OWa(this),g.H(this,this.u),this.u.Vu(function(){PWa(a)}))};
g.k.unload=function(){this.B&&this.j?QWa(this,!1):(this.va&&g.Po(this.va),this.player.Mf("captions"),this.oa=[],this.u&&this.u.Bo(),this.Oa.clear(),this.J&&this.player.Yd(this.J),this.ZJ());g.lJ.prototype.unload.call(this);this.player.Xs();this.player.Ma("captionschanged",{})};
g.k.create=function(){this.Ls()&&this.load()};
g.k.D_=function(){for(var a=this.G.Jd().nf().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=g.mJ(this.u.u,!0);for(var d=0;d<b.length;d++)if(b[d].toString()===a[c].id){b=b[d];break a}b=null}(this.loaded?this.j:null)!==b&&v2(this,b,!0)};
g.k.u1=function(){!this.j&&this.B||this.unload()};
g.k.onCueRangeEnter=function(a){this.oa.push(a);g.Mo(this.ma)};
g.k.onCueRangeExit=function(a){g.Wb(this.oa,a);this.u instanceof C1&&this.u.I&&this.player.Og([a]);g.Mo(this.ma)};
g.k.getCaptionWindowContainerId=function(){return this.Sa.element.id};
g.k.q0=function(){UWa(this,this.Da);this.Da=null};
g.k.XJ=function(){var a=this;if(!this.jb||!this.B){this.ma.stop();g.eba(this.Fa);this.oa.sort(g.cw);var b=this.oa;if(this.J){var c=g.Zm(b,function(f){return-1===this.J.indexOf(f)},this);
c.length&&(b=c)}b=g.r(b);for(c=b.next();!c.done;c=b.next())SWa(this,c.value);b={};c=g.r(Object.entries(this.N));for(var d=c.next();!d.done;b={uq:b.uq,lk:b.lk},d=c.next()){var e=g.r(d.value);d=e.next().value;e=e.next().value;b.uq=d;b.lk=e;this.Fa[b.uq]?(b.lk.element.parentNode||(b.lk instanceof H1||b.lk instanceof G1||g.Cf(this.N,function(f){return function(h,l){l!==f.uq&&h.u.params.sj===f.lk.u.params.sj&&h.u.params.wi===f.lk.u.params.wi&&h.u.params.il===f.lk.u.params.il&&(h.dispose(),delete a.N[l]);
return l===f.uq}}(b),this),TWa(this,b.lk.element)),b.lk.Mv(this.Fa[b.uq])):(b.lk.dispose(),delete this.N[b.uq])}}};
g.k.u0=function(){n2(this,{},!0);this.U.K("web_player_disable_publish_captions_settings_changed_on_reset")||this.player.Ma("captionssettingschanged")};
g.k.uW=function(){var a=y2.Rd;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Mk?3:a.bold?1:a.Mk?2:0,textOpacity:a.textOpacity,windowColor:y2.windowColor,windowOpacity:y2.windowOpacity};var b=o2(this)||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&(a.backgroundOpacity=
b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&(a.fontSizeIncrement=
b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);null!=b.windowOpacity&&
(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.VR=function(a,b){var c={};Object.assign(c,o2(this));Object.assign(c,a);n2(this,c,b);this.player.Ma("captionssettingschanged")};
g.k.ZJ=function(){!this.B&&this.loaded&&(g.zf(this.N,function(a,b){a.dispose();delete this.N[b]},this),this.XJ())};
g.k.ag=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Mg(b,-2,4);this.VR({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&v2(this,this.j,!0);break;case "stickyLoading":void 0!==b&&this.U.B&&(g.mC(this.U)?w2(this,!!b):x2(this,"module-enabled",!!b));break;case "track":if(!this.u)return{};if(b){if(this.B)break;if(!g.Oa(b))break;if(g.Jf(b)){v2(this,null,!0);break}a=g.mJ(this.u.u,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&e.languageName!==
b.languageName||(c=b.translationLanguage?KVa(e,b.translationLanguage):e)}!c||c===this.j&&this.loaded||(b=g.fua(),a=g.XC(c),b.length&&a===b[b.length-1]||(b.push(a),g.Bv("yt-player-caption-language-preferences",b)),v2(this,c,!0))}else return this.loaded&&this.j&&!u2(this)?g.WC(this.j):{};return"";case "tracklist":return this.u?g.fl(g.mJ(this.u.u,!(!b||!b.includeAsr)),function(f){return g.WC(f)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.B||void 0===b||z2(this,!!b);break;case "sampleSubtitlesCustomized":this.B||z2(this,!!b,b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.U.B&&a.push("stickyLoading");return a};
g.k.DG=function(){var a=this.j;if(a){var b=a.vssId;a.translationLanguage&&b&&!this.U.K("auto_translation_logging_killswitch")&&(b="t"+b+"."+g.XC(a));return{cc:b}}return{}};
g.k.f1=function(){this.loaded&&this.j&&!u2(this)?(g.mC(this.U)?w2(this,!1):x2(this,"module-enabled",!1),this.unload(),r2(this,!0)&&v2(this,s2(this),!1)):this.CR()};
g.k.CR=function(){this.loaded&&this.j&&!u2(this)||v2(this,u2(this)||!this.j?t2(this,!0):this.j,!0)};
g.k.uY=function(){var a=u2(this);r2(this,a)?v2(this,this.player.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Ls()&&(a?v2(this,t2(this),!1):this.load()))};
g.k.gZ=function(){var a=this.G.Jd();a&&!a.isDisposed()&&a.au();this.G.isFullscreen()?(this.B=this.Ha=!0,this.loaded&&PWa(this)):(this.Ha="3"===this.U.controlsType,this.B=KWa(this));v2(this,this.j)};
g.ON.SB(p2,{XJ:"smucd"});g.kJ("captions",p2);})(_yt_player);
