(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var y0=function(a){a.X("cardstatechange",a.Qh()&&a.Pl()?1:0)},z0=function(a,b){var c=g.Na(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},pUa=function(a){var b=g.fm(a);
a=g.im(a);return new g.Ml(b.x,b.y,a.width,a.height)},qUa=function(a){return Math.pow(a,3)},rUa=function(a){return 3*a*a-2*a*a*a},C0=function(a){a=g.Qa(a);
delete A0[a];g.Jf(A0)&&B0&&B0.stop()},tUa=function(){B0||(B0=new g.K(function(){sUa()},20));
var a=B0;a.isActive()||a.start()},sUa=function(){var a=g.Ta();
g.zf(A0,function(b){uUa(b,a)});
g.Jf(A0)||tUa()},D0=function(a,b,c,d){g.ep.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.N=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.D=null},uUa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.D);a.D=b;vUa(a,a.progress);1==a.progress?(a.j=0,C0(a),a.onFinish(),a.Vy()):a.Lc()&&a.HE()},vUa=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.N[c]-a.u[c])*b+a.u[c]},wUa=function(a,b){g.tf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},E0=function(a,b,c,d,e){D0.call(this,b,c,d,e);
this.element=a},F0=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
E0.call(this,a,b,c,d,e)},G0=function(a){g.G.call(this);
this.u=a||window;this.j=[]},H0=function(a){return a.baseUrl||null},I0=function(a,b){return g.Zm(g.fl(a,b),function(c){return!!c})},xUa=function(a,b,c){function d(Ca){var Ha=Ca.hovercardButton;
if(!Ha)return null;Ha=Ha.subscribeButtonRenderer;if(!Ha)return null;var ub=f(Ha.unsubscribedButtonText),mc=f(Ha.subscribedButtonText);if(Ha.subscribed){var ld=f(Ha.subscriberCountWithUnsubscribeText);var Lb=f(Ha.subscriberCountText)}else ld=f(Ha.subscriberCountText),Lb=f(Ha.subscriberCountWithSubscribeText);var vd=null;if(Ca.signinEndpoint){vd=z0(Ca,"signinEndpoint","webNavigationEndpointData","url");if(!vd){var wc,Oc,ne;vd=null==(wc=Ha.signInEndpoint)?void 0:null==(Oc=wc.commandMetadata)?void 0:
null==(ne=Oc.webCommandMetadata)?void 0:ne.url}if(!vd)return null}return ub&&(mc||vd)?{subscribed:Ha.subscribed,subscribeText:ub,subscribeCount:ld,unsubscribeText:mc,unsubscribeCount:Lb,enabled:Ha.enabled,signinUrl:vd,classic:Ca.useClassicSubscribeButton}:null}
function e(Ca){if(Ca){var Ha=[],ub=Ca.videoId;ub&&Ha.push("v="+ub);(ub=Ca.playlistId)&&Ha.push("list="+ub);(Ca=Ca.startTimeSeconds)&&Ha.push("t="+Ca);return"/watch?"+Ha.join("&")}}
function f(Ca){if(!Ca)return null;var Ha=Ca.simpleText;return Ha?Ha:Ca.runs?g.fl(Ca.runs,function(ub){return ub.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,t=null,v=null,x=null,y=!1,z=null,E=null,I=null,J=null,L=null,ea=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:(ea=l.watchEndpoint,m=e(ea)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,t=f(p.text),p="LIVE"===p.style):t=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:(ea=l.watchEndpoint,m=e(ea)),n=!1,q=a,v=f(b.playlistLength);
else if("CHANNEL"===h){if(y=z0(l,"browseEndpoint","browseId"))x=y,m="/channel/"+x;n=!1;q="new";(y=!!b.isSubscribe)?z=d(b):E=f(b.subscribersText)}else"WEBSITE"===h?((I=z0(l,"urlEndpoint","url"))&&(m=I),n=!0,q="new",I=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(J=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=z0(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=z0(b,"title","accessibility","accessibilityData","label");var N=b.endpoint?b.endpoint.clickTrackingParams:
null,za="";if(b.metadata){var Z=f(b.metadata);Z&&(za=Z)}return{id:"element-"+c,type:h,title:f(b.title),metadata:za,callToAction:f(b.callToAction),lN:b.image,iconUrl:I,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:t,isLiveVideo:p,playlistLength:v,channelId:x,subscribeButton:z,subscribersText:E,isSubscribe:y,targetUrl:m||null,lX:n,sessionData:N?{itct:N}:null,V0:q,ex:a?
a:null,isPlaceholder:b.isPlaceholder,impressionUrls:I0(b.impressionUrls||[],H0),aX:I0(b.hovercardShowUrls||[],H0),clickUrls:I0(l.loggingUrls||[],H0),visualElement:g.Zu(b.trackingParams),productPrice:J,additionalFeesText:L,watchEndpoint:ea||null}},J0=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:I0(a.impressionUrls||[],H0),elements:I0(a.elements||[],function(d,e){return xUa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Zu(a.trackingParams));return c},K0=function(a){g.lJ.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.J=[];this.V=!0;this.I=0;a=a.S();this.N=g.PB(a)||g.TB(a);this.events=new g.Dz(this);g.H(this,this.events);this.events.P(this.player,g.dw("creatorendscreen"),this.onCueRangeEnter);this.events.P(this.player,g.ew("creatorendscreen"),this.onCueRangeExit);this.events.P(this.player,"resize",this.vb);this.events.P(window,"focus",this.Q_);this.load();var b=g.th("STYLE");(g.lh("HEAD")[0]||document.body).appendChild(b);g.sf(this,function(){g.xh(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},yUa=function(a){return a.player.getVideoData().D?"current":a.N?"new":"current"},L0=function(a){return"creator-endscreen-editor"===a.player.S().playerStyle},zUa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=J0(f,yUa(a))));M0(a,f)},
urlParams:{v:c},withCredentials:!0};a.N&&(c.urlParams.ptype="embedded");var d=b.Kq;d&&(c.postParams={ad_tracking:d});if(b=g.Vwa(b))if(b=g.xg(b),b=g.wg(b))a.B=g.Oq(b,c)},M0=function(a,b,c){c=void 0===c?!0:c;
a.player.Mf("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.r(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&AUa(a);c=[];d=new g.bw(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.S().isMobile||(a.u=new g.V({F:"div",L:"ytp-ce-shadow"}),g.YI(a.player,a.u.element,4),a.C=new g.dH(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=BUa(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.YI(a.player,f.element,4);var h=new g.bw(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);CUa(a,
f,e)}else g.Wu(new g.bs("buildEndscreenElement null",e))}a.player.Yd(c);a.vb()}},AUa=function(a){var b=g.ev(),c=g.fv();
c&&b&&a.endscreen.visualElement&&g.jv(void 0,c,b,[a.endscreen.visualElement])},BUa=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={F:"div",Ba:["ytp-ce-element","ytp-ce-video"],T:{tabindex:"0","aria-label":b.ex||"","aria-hidden":"true"},R:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-covering-image",T:N0(b)},{F:"div",L:"ytp-ce-covering-shadow-top"},{F:"a",L:"ytp-ce-covering-overlay",T:{href:O0(a,b.targetUrl),tabindex:"-1"},R:[{F:"div",Ba:["ytp-ce-video-title","ytp-webkit-ellipsis"],T:{dir:g.ip(b.title||"")},Z:b.title},{F:"div",L:b.isLiveVideo?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
Z:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":a={F:"div",Ba:["ytp-ce-element","ytp-ce-playlist"],T:{tabindex:"0","aria-label":b.ex||"","aria-hidden":"true"},R:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-covering-image",T:N0(b)},{F:"div",L:"ytp-ce-covering-shadow-top"},{F:"a",L:"ytp-ce-covering-overlay",T:{href:O0(a,b.targetUrl),tabindex:"-1"},R:[{F:"div",Ba:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],T:{dir:g.ip(b.title||"")},Z:b.title},{F:"div",L:"ytp-ce-playlist-count",
R:[{F:"div",L:"ytp-ce-playlist-icon"},{F:"div",L:"ytp-ce-playlist-count-text",Z:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={F:"div",Ba:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],T:{tabindex:"0","aria-label":b.ex||"","aria-hidden":"true"},R:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-expanding-overlay",R:[{F:"div",L:"ytp-ce-expanding-overlay-hider"},{F:"div",L:"ytp-ce-expanding-overlay-background"},{F:"div",L:"ytp-ce-expanding-overlay-content",
R:[{F:"div",L:"ytp-ce-expanding-overlay-body",R:[{F:"div",L:"ytp-ce-expanding-overlay-body-padding",R:[{F:"a",Ba:["ytp-ce-channel-title","ytp-ce-link"],T:{href:O0(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.ip(b.title||"")},Z:b.title},b.subscribeButton?{F:"div",L:"ytp-ce-subscribe-container",R:[{F:"div",L:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{F:"div",L:"ytp-ce-channel-subscribers-text",Z:b.subscribersText}:"",b.metadata?{F:"div",Ba:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],Z:b.metadata}:""]}]}]}]},{F:"div",L:"ytp-ce-expanding-image",T:N0(b)}]};c=new g.V(c);var d=g.mh(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Uo(d,"ytp-ce-subscribe-button");if(a.player.S().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.DK(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,
!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={F:"div",Ba:["ytp-ce-element","ytp-ce-website"],T:{tabindex:"0","aria-label":b.ex||"","aria-hidden":"true"},R:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-expanding-overlay",R:[{F:"div",L:"ytp-ce-expanding-overlay-hider"},{F:"div",L:"ytp-ce-expanding-overlay-background"},{F:"div",L:"ytp-ce-expanding-overlay-content",
R:[{F:"div",L:"ytp-ce-expanding-overlay-body",R:[{F:"div",L:"ytp-ce-expanding-overlay-body-padding",R:[{F:"div",L:"ytp-ce-website-title",T:{dir:g.ip(b.title||"")},Z:b.title},{F:"div",L:"ytp-ce-website-metadata",Z:b.metadata},{F:"a",Ba:["ytp-ce-website-goto","ytp-ce-link"],T:{href:O0(a,b.targetUrl),target:"_blank",tabindex:"-1"},Z:b.callToAction}]}]}]}]},{F:"div",L:"ytp-ce-expanding-image",T:N0(b)},{F:"div",L:"ytp-ce-expanding-icon",T:DUa(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c=
"",b.productPrice&&(c={F:"div",L:"ytp-ce-merchandise-price-container",R:[{F:"div",L:"ytp-ce-merchandise-price",Z:b.productPrice}]},b.additionalFeesText&&c.R.push({F:"div",L:"ytp-ce-merchandise-additional-fees",Z:b.additionalFeesText})),a={F:"div",Ba:["ytp-ce-element","ytp-ce-merchandise"],T:{tabindex:"0","aria-label":b.ex||"","aria-hidden":"true"},R:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-expanding-overlay",R:[{F:"div",L:"ytp-ce-expanding-overlay-hider"},{F:"div",L:"ytp-ce-expanding-overlay-background"},
{F:"div",L:"ytp-ce-expanding-overlay-content",R:[{F:"div",L:"ytp-ce-expanding-overlay-body",R:[{F:"div",L:"ytp-ce-expanding-overlay-body-padding",R:[{F:"div",L:"ytp-ce-merchandise-title",T:{dir:g.ip(b.title||"")},Z:b.title},c,{F:"div",L:"ytp-ce-merchandise-metadata",Z:b.metadata},{F:"a",Ba:["ytp-ce-merchandise-goto","ytp-ce-link"],T:{href:O0(a,b.targetUrl),target:"_blank",tabindex:"-1"},Z:b.callToAction}]}]}]}]},{F:"div",L:"ytp-ce-expanding-image",T:N0(b)},{F:"div",L:"ytp-ce-merchandise-invideo-cta-container",
R:[{F:"div",L:"ytp-ce-merchandise-invideo-cta",Z:b.callToAction||void 0}]}]},c=new g.V(a)}b.isPlaceholder&&g.Uo(c.element,"ytp-ce-placeholder");return c},N0=function(a){if(a.lN)var b=a.lN.thumbnails;
return DUa(b?b[b.length-1].url:null)},DUa=function(a){return a?{style:"background-image: url("+a+")"}:{}},CUa=function(a,b,c){function d(m){m&&(b.La("blur",function(){"none"!=m.style.display&&a.V&&m.focus()}),b.P(m,"focus",f),b.P(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.Uo(b.element,"ytp-ce-force-expand"),P0(a,c.id,!0)):(g.Wo(b.element,"ytp-ce-force-expand"),g.Wo(b.element,"ytp-ce-element-hover"),P0(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.La("mouseenter",function(){Q0(a,b,c)});
b.La("mouseleave",function(){R0(a,b,c)});
a.player.S().isMobile||b.La("click",function(){g.Uo(b.element,"ytp-ce-element-hover")});
b.La("click",function(m){EUa(a,c,m)});
b.La("keypress",function(m){EUa(a,c,m)});
b.La("focus",function(){Q0(a,b,c)});
b.La("blur",function(){R0(a,b,c)});
b.La("touchstart",function(){Q0(a,b,c)});
var l=g.oh("ytp-ce-expanding-overlay-hider",b.element);l&&b.P(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.Wo(b.element,"ytp-ce-element-hover");g.Wo(b.element,"ytp-ce-force-expand")});
b.La("keydown",function(m){a.V=9===m.keyCode&&!m.shiftKey});
d(g.oh("ytp-sb-subscribe",b.element));d(g.oh("ytp-sb-unsubscribe",b.element));b.La("focus",f);b.La("blur",h)},EUa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.To(d,"ytp-ce-element");){g.To(d,"subscribe-label")&&S0(a,b);
if(g.To(d,"ytp-ce-channel-subscribe"))return;d=g.yh(d)}if(!d||g.To(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])R0(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.V0)S0(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.xg(O0(a,b.targetUrl)),g.DH(g.wg(c),void 0,b.sessionData);else{var e=g.iC(a.player.S())||a.player.getVideoData().D,f=function(){var h=O0(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.yq(h);e&&n&&(n.v||n.list)?
a.player.ul(n.v,l,n.list,!1,void 0,m||void 0):g.CH(h,l)};
S0(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},O0=function(a,b){a=a.player.S();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.tC(a)+b}else return"";return b},Q0=function(a,b,c){g.To(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.Uo(b.element,"ytp-ce-element-hover"):a.player.S().isMobile?(new g.K(function(){g.Uo(b.element,"ytp-ce-element-hover")},200)).start():g.Uo(b.element,"ytp-ce-element-hover"),T0(a,c.aX),P0(a,c.id,!0))},R0=function(a,b,c){g.Wo(b.element,"ytp-ce-element-hover");
g.Wo(b.element,"ytp-ce-force-expand");P0(a,c.id,!1)},P0=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.r(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.M(a.j[e].element,"ytp-ce-element-shadow-show",c)},T0=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||L0(a))c&&c();else{b=FUa(a,b);var e=0,f=!1,h=new g.K(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.ft(b[a],d)}},S0=function(a,b,c){T0(a,b.clickUrls,c);
(a=g.fv())&&b.lX&&g.xv(a,b.visualElement)},FUa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(GUa(b[d],c));return a},GUa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},HUa=function(a){return"string"===typeof a?a:""},U0=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},IUa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},V0=function(a){return a.value?a.value:null},W0=function(a){if(!a)return null;
var b=g.xg(HUa(a.value));b=g.wg(b);if(!b)return null;var c=U0(a.target,JUa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new IUa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},KUa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},NUa=function(a){if(!a)return null;
var b=U0(a.type,LUa),c=U0(a.trigger,MUa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=W0(a?a:null);return b?new KUa(b,c,a):null},OUa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},QUa=function(a){return(a=PUa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},PUa=function(a,b){return g.Pb(a.action,b)},RUa=function(a,b){this.context=a;
this.j=b},Y0=function(a){return a.customMessage?X0("div","iv-card-message",a.customMessage):""},Z0=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{F:"div",L:"iv-card-image",T:{style:a},R:c}},$0=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.r(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(X0("li","",c.value));return{F:"ul",L:"iv-card-meta-info",R:b}},X0=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.ip(c);return{F:a,T:b,Z:c}},SUa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.nx&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.nx+");");c.dir=g.ip(a.customMessage);var d=[{F:"span",Z:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({F:"span",L:"iv-card-link-icon"}));return{F:"div",Ba:b,T:c,R:d}},a1=function(a,b,c,d){if(d){b=g.r(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},TUa=function(a,b){this.merchant=a;
this.price=b},UUa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},VUa=function(a,b){return b?b:UUa(a)?"current":"new"},b1=function(a,b){g.G.call(this);
var c=this;this.element=a;this.context=b;this.gb=!1;this.Sa=new Map;this.Ua=new Map;this.context.G.addEventListener(g.dw("annotations_module"),function(d){(d=c.Sa.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.ew("annotations_module"),function(d){(d=c.Ua.get(d))&&d.apply(c)})},c1=function(a,b,c,d,e,f,h){a.context.j.La(b,"click",function(l){a.IE(c,d,e,f||[],h||0,l)});
a.context.j.La(b,"touchstart",function(){a.gb=!1});
a.context.j.La(b,"touchmove",function(){a.gb=!0})},WUa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},d1=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
wR:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
uD:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},g1=function(a,b,c){b1.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.Ha=this.Kb=this.B=this.isInitialized=!1;this.ma=null;this.cards=[];this.jb=this.N=this.Fa=this.D=this.Oa=this.j=null;this.W=[];this.Y=this.J=this.kf=this.Da=null;this.I=0;this.va=new g.K(function(){},c.U.cf?4E3:3E3);
g.H(this,this.va);this.eb=new g.K(function(){});
g.H(this,this.eb);this.oa=new RUa(c,function(e,f,h,l,m,n){c1(d,e,f,h,l,m,n)});
this.V=new g.V({F:"div",L:"iv-drawer",T:{id:"iv-drawer"},R:[{F:"div",L:"iv-drawer-header",T:{"aria-role":"heading"},R:[{F:"span",L:"iv-drawer-header-text"},{F:"button",Ba:["iv-drawer-close-button","ytp-button"],T:{"aria-label":"Hide cards",tabindex:"0"}}]},{F:"div",L:"iv-drawer-content"}]});g.H(this,this.V);this.C=this.V.element;this.bb=new g.dH(this.V,330);g.H(this,this.bb);this.Ib=g.oh("iv-drawer-header-text",this.C);this.u=g.oh("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Kb&&e1(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Kb=d.B)&&f1(d)});
this.G.addEventListener("videodatachange",this.Bp.bind(this))},XUa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){e1(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){f1(a)});
var c=b.headerText;g.Ah(a.Ib,c);a.N&&a.N.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Da=g.Zu(b.trackingParams);a.J=g.Zu(b.closeTrackingParams);a.kf=g.Zu(b.iconTrackingParams)},YUa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.G.S().experiments.fb("enable_error_corrections_infocard");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){d=b.teaser.simpleCardTeaserRenderer;var e=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.iw(d.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,tracking:{},Ql:null,dj:d.trackingParams?g.Zu(d.trackingParams):null,kf:e&&e.trackingParams?g.Zu(e.trackingParams):null,imageUrl:"",displayDomain:null,
showLinkIcon:!1,nx:null,title:"",customMessage:"",url:null,onClickCommand:d.onTapCommand||null};h1(a,b)}else if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.iw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:i1(a,
c,b,d),sponsored:!1,tracking:d1(d,e,d.command),Ql:d.trackingParams?g.Zu(d.trackingParams):null,dj:e.trackingParams?g.Zu(e.trackingParams):null,kf:f&&f.trackingParams?g.Zu(f.trackingParams):null,imageUrl:j1(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.iw(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,nx:null,title:d.title?g.iw(d.title):"",customMessage:d.callToAction?g.iw(d.callToAction):"",url:d.command.urlEndpoint.url?W0({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:d.command.urlEndpoint.url}):null,onClickCommand:null};h1(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.iw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:i1(a,
c,b,d),sponsored:!1,tracking:d1(d,e,d.endpoint),Ql:d.trackingParams?g.Zu(d.trackingParams):null,dj:e.trackingParams?g.Zu(e.trackingParams):null,kf:f&&f.trackingParams?g.Zu(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.iw(d.customText):null,profileImageUrl:j1(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.iw(d.channelName):"",metaInfo:[d.subscriberCountText?g.iw(d.subscriberCountText):""],url:W0({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId}),onClickCommand:null};h1(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.iw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:i1(a,c,b,d),sponsored:!1,tracking:d1(d,e,d.action),Ql:d.trackingParams?g.Zu(d.trackingParams):null,dj:e.trackingParams?g.Zu(e.trackingParams):null,kf:f&&f.trackingParams?g.Zu(f.trackingParams):null,Pz:j1(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.iw(d.customMessage):null,playlistVideoCount:g.iw(d.playlistVideoCount),title:d.playlistTitle?g.iw(d.playlistTitle):"",metaInfo:[d.channelName?
g.iw(d.channelName):"",d.videoCountText?g.iw(d.videoCountText):""],url:W0({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:WUa(d.action)}),onClickCommand:null};h1(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.iw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:i1(a,c,b,d),sponsored:!1,tracking:d1(d,e,d.action),Ql:d.trackingParams?g.Zu(d.trackingParams):null,dj:e.trackingParams?g.Zu(e.trackingParams):null,kf:f&&f.trackingParams?g.Zu(f.trackingParams):null,Pz:j1(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.iw(d.lengthString):null,customMessage:d.customMessage?g.iw(d.customMessage):null,title:d.videoTitle?g.iw(d.videoTitle):"",metaInfo:[d.channelName?
g.iw(d.channelName):"",d.viewCountText?g.iw(d.viewCountText):""],isLiveNow:!!d.badge,url:W0({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:WUa(d.action)}),onClickCommand:null};h1(a,b)}a.I++},j1=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},i1=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},$Ua=function(a,b){if(b=ZUa(a,b))b===a.j&&(a.j=null),a.G.removeCueRange(b.card.id),g.xh(b.yF),g.Wb(a.cards,b),a.LA(),k1(a)},e1=function(a,b,c){if(!a.B){a.bb.show();
a.Oa=new g.K(function(){g.Uo(a.context.G.getRootNode(),g.NO.IV_DRAWER_OPEN)},0);
a.Oa.start();a.ma=g.Kt(a.u,"mousewheel",function(h){a.va.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.fv();d&&a.Da&&a.J&&g.nv(d,[a.Da,a.J]);b={TRIGGER_TYPE:b};for(var e=g.r(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.WO||(f.WO=!0,aVa(a.context.logger,f.card.tracking.impression,b)),d&&g.nv(d,[f.card.Ql]);y0(a.G);c&&(a.D=new g.K(function(){a.Fa=a.N;a.jb.focus()},330),a.D.start())}},f1=function(a){a.B&&(a.bb.hide(),g.Lt(a.ma),a.ma=null,g.Wo(a.context.G.getRootNode(),g.NO.IV_DRAWER_OPEN),a.B=!1,y0(a.G),a.D&&a.D.stop(),a.D=new g.K(function(){a.Fa&&(a.Fa.focus(),a.Fa=null)},330),a.D.start())},
cVa=function(a){g.Vo(a.element,[g.NO.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.YI(a.G,a.C,5);bVa(a);a.N=g.oh("ytp-cards-button",a.G.getRootNode());a.jb=g.oh("iv-drawer-close-button",a.C);a.isInitialized=!0},bVa=function(a){var b=g.oh("iv-drawer-close-button",a.C);
a.context.j.La(b,"click",a.LV,a);a.context.j.La(a.u,"touchend",function(){a.va.start()});
a.context.j.La(a.u,"scroll",a.XV,a);a.context.u.subscribe("onHideControls",function(){a.Ha=!0});
a.context.u.subscribe("onShowControls",function(){a.Ha=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ha=g.To(a.G.getRootNode(),"ytp-autohide")});
a.W.push(g.cu("iv-button-shown",a.uX,a));a.W.push(g.cu("iv-button-hidden",a.tX,a));a.W.push(g.cu("iv-teaser-shown",a.nU,a));a.W.push(g.cu("iv-teaser-hidden",a.vX,a));a.W.push(g.cu("iv-teaser-clicked",a.mU,a))},dVa=function(a,b){var c,d=null==(c=a.G.getVideoData())?void 0:c.multiMarkersPlayerBarRenderer;
if(null==d?0:d.markersMap){var e;for(c=0;(null==(e=d)?void 0:e.markersMap.length)>c;c++){var f=void 0,h=null==(f=d)?void 0:f.markersMap[c];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=h[0].markerRenderer)?void 0:d.timeRangeStartMillis)||0,a.Y=null,!0}}a.Y=b;return!1},h1=function(a,b){if(b.onClickCommand&&b.onClickCommand.changeEngagementPanelVisibilityAction&&"engagement-panel-error-corrections"===b.onClickCommand.changeEngagementPanelVisibilityAction.targetId){a.Y=
b;
var c=!0}else c=!1;if(!c||dVa(a,b))if(c=eVa(a,b)){var d={card:b,yF:c.element,WO:!1};if(!b.onClickCommand){a.isInitialized||cVa(a);$Ua(a,b.id);var e=fVa(a,d);g.cc(a.cards,e,0,d);c.xa(a.u,e);a.LA()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,k1(a),gVa(a,d),e1(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&hVa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){hVa(a,d)}),k1(a))}},eVa=function(a,b){switch(b.type){case "simple":a=
a.oa;
var c=b.displayDomain?{F:"div",L:"iv-card-image-text",Z:b.displayDomain}:void 0;var d=SUa(b);c={F:"div",Ba:["iv-card"],R:[{F:"a",L:"iv-click-target",T:{href:b.url?V0(b.url)||"":""},R:[Z0(b.imageUrl,c),{F:"div",L:"iv-card-content",R:[X0("h2",void 0,b.title),d]}]}]};c=new g.V(c);a1(a,g.nh("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.oa,c={F:"div",Ba:["iv-card","iv-card-channel"],R:[{F:"a",Ba:["iv-click-target"],T:{href:V0(b.url)||"","data-ytid":b.channelId},R:[Z0(b.profileImageUrl),
{F:"div",L:"iv-card-content",R:[Y0(b),{F:"h2",L:"iv-card-primary-link",Z:b.title},$0(b)]}]}]},c=new g.V(c),a1(a,g.nh("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.oa,c={F:"div",Ba:["iv-card","iv-card-playlist"],R:[{F:"a",L:"iv-click-target",T:{href:V0(b.url)||""},R:[Z0(b.Pz,{F:"div",L:"iv-card-image-overlay",R:[{F:"span",L:"iv-card-playlist-video-count",Z:b.playlistVideoCount}]}),{F:"div",L:"iv-card-content",R:[Y0(b),X0("h2","iv-card-primary-link",b.title),$0(b)]}]}]},c=new g.V(c),
a1(a,g.nh("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.oa;var e=!g.Tb(b.offers);c=["iv-card"];d="";var f=SUa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({F:"div",L:"iv-card-offer-price",Z:f.price}),f.merchant&&e.push({F:"div",L:"iv-card-offer-merchant",Z:f.merchant}),f={F:"div",R:e});e=b.url?V0(b.url)||"":"";c={F:"div",Ba:c,T:{tabindex:"0"},R:[{F:"a",Ba:["iv-card-image","iv-click-target"],T:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{F:"div",L:"iv-card-content",R:[b.sponsored?{F:"div",L:"iv-card-sponsored",R:["Sponsored",{F:"div",L:"iv-ad-info-container",R:[{F:"div",L:"iv-ad-info",Z:"{{adInfo}}"},{F:"div",L:"iv-ad-info-icon-container",R:[{F:"div",L:"iv-ad-info-icon"},{F:"div",L:"iv-ad-info-callout"}]}]}]}:"",{F:"a",L:"iv-click-target",T:{href:e},R:[X0("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.th("span");g.Ah(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Md(d,"adInfo");a1(a,g.nh("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.oa,d=b.videoDuration?{F:"span",L:"iv-card-video-duration",Z:b.videoDuration}:void 0,f=b.isLiveNow?{F:"span",Ba:["yt-badge","yt-badge-live"],Z:"LIVE NOW"}:null,e={F:"div",Ba:["iv-card","iv-card-video"],R:[{F:"a",L:"iv-click-target",T:{href:(null==(c=b.url)?void 0:V0(c))||""},R:[Z0(b.Pz,d),{F:"div",L:"iv-card-content",R:[Y0(b),X0("h2","iv-card-primary-link",b.title),$0(b),f]}]}]},c=new g.V(e),a1(a,g.nh("iv-click-target",
c.element),b,b.url),c;default:return null}},fVa=function(a,b){if(0===a.cards.length)return 0;
a=g.Qb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},iVa=function(a){return a.j?"productListing"===a.j.card.type:g.gl(a.cards,function(b){return"productListing"===b.card.type})},k1=function(a){g.M(a.G.getRootNode(),"ytp-cards-shopping-active",iVa(a))},hVa=function(a,b){if(!g.To(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.fv(),d=a.j?a.j.card.kf:a.kf;
c&&d&&g.ov(c,[d]);a.j=b;k1(a)}(c=a.isInitialized&&"none"==a.element.style.display)||(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=!(1===c||3===c||d));c||b.card.teaserDurationMs&&a.G.Hv(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs,onClickCommand:b.card.onClickCommand});a.eb.isActive()||((!a.B||!a.va.isActive()&&a.Ha)&&gVa(a,b),a.eb.start(910+b.card.teaserDurationMs))}},gVa=function(a,b){a.V.ob?(b=new D0([0,
a.u.scrollTop],[0,b.yF.offsetTop],600,rUa),a.context.B.La(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.La(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.sG(a.V,!0),a.u.scrollTop=b.yF.offsetTop,g.sG(a.V,!1))},l1=function(a){return a.j&&a.j.card?a.j.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},ZUa=function(a,b){return g.Pb(a.cards,function(c){return c.card.id===b})},m1=function(a,b,c){b1.call(this,a,b);
this.annotation=c;this.isActive=!1},jVa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},n1=function(a,b,c){m1.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.D=null},kVa=function(a,b){var c=void 0===c?0:c;
var d=pUa(b).width;g.dm(b,d);c=new F0(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,qUa);g.H(a,c);a.context.B.La(c,"begin",function(){g.jm(b,!0)});
c.play()},nVa=function(a,b){if(b.channel_name){var c=a.createElement({F:"div",
Ba:["iv-branding-context-name"],Z:b.channel_name}),d=a.createElement({F:"div",Ba:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.DK(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.G),a.j.xa(d));var f=a.createElement({F:"div",Ba:["iv-branding-context-subscribe-caret"]}),h=a.createElement({F:"div",Ba:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.jm(h,!1);var l=a.createElement({F:"div",Ba:["branding-context-container-outer"]});l.appendChild(h);g.Pl(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.K(function(){lVa(a,h,l)},500);
g.H(a,a.B);a.context.j.La(a.element,"mouseover",function(){mVa(a,h,l,f,b.image_height)});
a.context.j.La(a.element,"mouseout",function(){a.B.start()})}},mVa=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.im(b);a.j||(b.style.width=g.cm(f.width,!0),c.style.width=g.cm(f.width,!0));g.Pl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Pl(d,"right","1px");a.C=!0;g.jm(b,!0);a.D=new g.K(function(){g.Uo(this.element,"iv-branding-active")},0,a);
a.D.start()}},lVa=function(a,b,c){g.Wo(a.element,"iv-branding-active");
a.I=new g.K(function(){g.jm(b,!1);a.j||(c.style.width=g.cm(0,!0))},250);
a.I.start();a.C=!1},oVa=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.U=c;this.videoData=d;this.logger=e;this.G=f;this.u=h},o1=function(a,b,c){m1.call(this,a,b,c);
var d=this;this.N=this.isCollapsed=this.V=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({F:"div",Ba:["iv-promo-contents"]});this.D=new g.K(function(){d.j.setAttribute("aria-hidden","true");g.jm(d.B,!1);g.jm(d.u,!0)},700,this);
g.H(this,this.D)},pVa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=QUa(a.annotation),f=b.image_url;if(f){var h=a.createElement({F:"div",Ba:["iv-promo-img","iv-click-target"]});f=a.createElement({F:"img",T:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({F:"span",L:"iv-promo-video-duration",Z:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({F:"span",L:"iv-promo-playlist-length",Z:b.playlist_length.toString()}),h.appendChild(f));e&&c1(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({F:"a",L:"iv-promo-txt"}),g.Jg(f,V0(e)),a.j=f):a.j=a.createElement({F:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({F:"p",R:[{F:"strong",
Z:b.text_line_1}]});var m=a.createElement({F:"p",R:[{F:"span",L:"iv-promo-link",Z:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({F:"button",Ba:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({F:"button",Ba:["iv-button","iv-promo-button"],R:[{F:"span",L:"iv-button-content",Z:f}]});var p=a.createElement({F:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&c1(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.Uo(a.j,
"iv-click-target");e&&c1(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({F:"p",R:[{F:"span",Z:b.text_line_1}]}),m=a.createElement({F:"p",R:[{F:"strong",Z:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({F:"span",Ba:["yt-badge","iv-promo-badge-live"],Z:"LIVE NOW"})),g.Uo(a.j,"iv-click-target"),e&&c1(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);p&&
a.J.appendChild(p);c=a.createElement({F:"div",L:"iv-promo-actions"});a.u=a.createElement({F:"button",Ba:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.j.La(a.u,"click",function(q){p1(a,5E3,q)});
c.appendChild(a.u);g.jm(a.u,!1);a.context.j.La(a.element,"mouseover",a.EW,a);a.context.j.La(a.element,"mouseout",a.DW,a);a.context.j.La(a.element,"touchend",function(q){p1(a,5E3,q)});
a.B=a.createElement({F:"button",Ba:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.j.La(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.xW:a.wW,a);c.appendChild(a.B);g.Vo(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},p1=function(a,b,c){c.stopPropagation();
qVa(a);rVa(a,b);a.j.focus()},sVa=function(a){a.isCollapsed||a.N||a.C||(g.Uo(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},qVa=function(a){a.D.stop();
a.isCollapsed&&(g.Xo(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.jm(a.u,!1),g.jm(a.B,!0))},rVa=function(a,b){a.C||(a.C=g.Wh(function(){q1(this);
sVa(this)},b,a))},q1=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},tVa=function(a){this.G=a},aVa=function(a,b,c){b&&(c?r1(a,b.map(function(d){return g.Go(d,c)})):r1(a,b))},r1=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.r(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.ft(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},s1=function(a){g.lJ.call(this,a);
var b=this;this.loadNumber=0;this.I={};this.logger=new tVa(this.player);this.D=new g.Dz(this);this.C=this.Km=null;this.events=new g.Dz(this);this.J=this.j=null;this.N=[];g.H(this,this.D);this.D.P(this.player,"onVideoAreaChange",function(){b.X("onVideoAreaChange")});
this.D.P(this.player,"onHideControls",function(){b.X("onHideControls")});
this.D.P(this.player,"onShowControls",function(){b.X("onShowControls")});
this.D.P(this.player,"resize",function(d){b.X("resize",d)});
this.D.P(this.player,"presentingplayerstatechange",function(d){b.X("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.oU,this);this.subscribe("resize",this.BC,this);this.player.S().W.subscribe("vast_info_card_add",this.iQ,this);g.H(this,this.events);this.V=this.createElement({F:"div",L:"video-custom-annotations"});this.u=new g.V({F:"div",Ba:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.u);g.YI(this.player,this.u.element,4);this.u.hide();this.B=new g.V({F:"div",Ba:["ytp-iv-video-content"]});g.H(this,this.B);a=this.createElement({F:"div",L:"video-annotations"});
a.appendChild(this.V);this.B.element.appendChild(a);this.Ls()&&this.load();var c=this.createElement({F:"style"});(g.lh("HEAD")[0]||document.body).appendChild(c);g.sf(this,function(){g.xh(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},uVa=function(a){a=a.createElement({F:"div",
Ba:["annotation","annotation-type-custom"]});g.jm(a,!1);return a},vVa=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.sG(a.u,b);g.sG(a.B,b)},wVa=function(a,b){for(var c={},d=g.r(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Oa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(wVa(a,e))}return c},zVa=function(a){var b=a.player.getVideoData();
if(b.Sa){var c=a.player.S().W.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Iq(h)&&h.responseXML?h.responseXML:null)&&t1(a,h)}};
g.Qr()&&(d.onFinish=xVa(a,d.onFinish));d.postParams={ic_only:"1"};yVa(d,c);g.Oq(b.Sa,d)}}},yVa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.ox&&(a.postParams.ic_coll=b.ox);b.QA&&(a.postParams.ic_xml=b.QA);b.Sz&&(a.postParams.ic_track=b.Sz)},AVa=function(a){var b=new g.V({F:"div"});
g.jm(b.element,!1);var c=new g1(a.player,b.element,u1(a));g.H(c,b);b.xa(a.u.element);c.Dz();return c},u1=function(a){if(!a.J){var b=new G0(a);
g.H(a,b);var c=new g.Xj(a);g.H(a,c);a.J=new oVa(b,c,a.player.S(),a.player.getVideoData(),a.logger,a.player,a.Me)}return a.J},t1=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.fv();if(e){var f=g.ev();f&&g.jv(void 0,e,f,[g.Zu(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=wVa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=U0(f.type,BVa),p=U0(f.style,CVa),q=HUa(f.data),t=0!==q.length?JSON.parse(q):{};var v=f.action;f=NUa;if(null==v)var x=null;else if(g.Na(v)){l=[];for(var y=g.r(v),z=y.next();!z.done;z=y.next()){var E=f(z.value);
E&&l.push(E)}x=l}else{var I=f(v);x=I?[I]:[]}e=m&&n?new OUa(m,n,p,x,t):null}else e=null}catch(Z){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var J=uVa(f),L=null;switch(l.type){case "branding":if(f.player.S().Mc)break;f.u.element.appendChild(J);L=new n1(J,u1(f),l);break;case "promotion":g.YI(f.player,J,4),L=new o1(J,u1(f),l)}L&&L.Dz();if(f=L)g.H(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=AVa(a),g.H(a,a.j));if("card"===e.type){c=a.j;var ea=e&&e.data&&e.data.card_type;
f=e.data;if(ea)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,wR:l.teaser_impression,uD:l.teaser_click},J=f.tracking_params||{},L=null,ea){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ql:J.card?g.Zu(J.card):null,dj:J.teaser?g.Zu(J.teaser):null,kf:J.icon?g.Zu(J.icon):
null,channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:W0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};h1(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,
Ql:J.card?g.Zu(J.card):null,dj:J.teaser?g.Zu(J.teaser):null,kf:J.icon?g.Zu(J.icon):null,Pz:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:W0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};h1(c,e);break;case "productListing":f.signin_url&&(L=W0({target:"current",value:f.signin_url}));ea=[];for(var N=f.offers||[],za=0;za<N.length;za++)ea.push(new TUa(g.Yg(N[za].merchant),
g.Yg(N[za].price)));e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ql:J.card?g.Zu(J.card):null,dj:J.teaser?g.Zu(J.teaser):null,kf:J.icon?g.Zu(J.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,nx:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:W0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),rka:L,qka:f.signin_title?f.signin_title:void 0,pka:f.signin_message?f.signin_message:void 0,offers:ea,onClickCommand:null};h1(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ql:J.card?g.Zu(J.card):
null,dj:J.teaser?g.Zu(J.teaser):null,kf:J.icon?g.Zu(J.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,nx:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:W0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};h1(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ql:J.card?g.Zu(J.card):null,dj:J.teaser?g.Zu(J.teaser):null,kf:J.icon?g.Zu(J.icon):null,Pz:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:W0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},h1(c,e)}}else XUa(a.j,e);c=
!0}}c&&(y0(a.player),a.BC())},DVa=function(a,b){var c=!1;
a.j||(a.j=AVa(a),g.H(a,a.j));for(var d=g.r(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(YUa(a.j,e.cardRenderer),c=!0);c&&(c=a.j,d=b.headerText?g.iw(b.headerText):"",g.Ah(c.Ib,d),c.N&&c.N.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Da=b.trackingParams?g.Zu(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.Zu(b.closeButton.infoCardIconRenderer.trackingParams):null,c.kf=b.icon.infoCardIconRenderer.trackingParams?
g.Zu(b.icon.infoCardIconRenderer.trackingParams):null,y0(a.player),a.BC())},EVa=function(a,b,c,d,e){if(!a.player.S().Mc){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new KUa("openUrl","click",new IUa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.iw(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.iw(b.subscriberCountText))):(b.subscriberCountText&&(e=g.iw(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.iw(b.subscriberCountWithSubscribeText)));var m,n,p=(null==(l=b.signInEndpoint)?void 0:
null==(m=l.commandMetadata)?void 0:null==(n=m.webCommandMetadata)?void 0:n.url)||"";l={subscribeText:g.iw(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.iw(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=l}f=new OUa(c,"branding","branding",f,d);l=uVa(a);a.u.element.appendChild(l);f=new n1(l,u1(a),f);f.Dz();g.H(f,f);a.I[c]=f}},xVa=function(a,b){return function(){var c=
g.Ba.apply(0,arguments);
a.isDisposed()||a.N.push(g.Jo.Ug(function(){b.apply(null,g.u(c))}))}},FVa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.RI.prototype.Hv=g.ca(13,function(a,b){var c=g.DJ(this.ib());c&&c.Hv(a,b)});
var A0={},B0=null;g.Ua(D0,g.ep);g.k=D0.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.Lc())return!1;C0(this);this.startTime=a=g.Ta();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.wC();this.vj("play");-1==this.j&&this.vj("resume");this.j=1;var b=g.Qa(this);b in A0||(A0[b]=this);tUa();uUa(this,a);return!0};
g.k.stop=function(a){C0(this);this.j=0;a&&(this.progress=1);vUa(this,this.progress);this.vj("stop");this.Vy()};
g.k.pause=function(){this.Lc()&&(C0(this),this.j=-1,this.vj("pause"))};
g.k.ea=function(){0==this.j||this.stop(!1);this.vj("destroy");D0.Je.ea.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.HE=function(){this.vj("animate")};
g.k.vj=function(a){this.dispatchEvent(new wUa(a,this))};
g.Ua(wUa,g.tf);g.Ua(E0,D0);E0.prototype.C=function(){};
E0.prototype.HE=function(){this.C();E0.Je.HE.call(this)};
E0.prototype.Vy=function(){this.C();E0.Je.Vy.call(this)};
E0.prototype.wC=function(){this.C();E0.Je.wC.call(this)};
g.Ua(F0,E0);F0.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(G0,g.G);G0.prototype.La=function(a,b,c,d){c=(0,g.Ra)(c,d||this.u);a=g.Kt(a,b,c);this.j.push(a);return a};
G0.prototype.gC=function(a,b,c,d){c=(0,g.Ra)(c,d||this.u);a=g.Xoa(a,b,c);this.j.push(a);return a};
G0.prototype.vc=function(a){g.Lt(a);g.Wb(this.j,a)};
G0.prototype.ea=function(){g.Lt(this.j);this.j.length=0;g.G.prototype.ea.call(this)};g.w(K0,g.lJ);g.k=K0.prototype;g.k.load=function(){g.lJ.prototype.load.call(this);if(!L0(this)){var a=g.Wwa(this.player.getVideoData());a?(a=J0(a,yUa(this)),M0(this,a,!1)):zUa(this)}};
g.k.unload=function(){M0(this,null);this.B&&(this.B.abort(),this.B=null);g.lJ.prototype.unload.call(this)};
g.k.ag=function(a,b){return L0(this)?"loadCustomEndscreenRenderer"===a?(a=J0(b,"new"),M0(this,a),!0):null:null};
g.k.getOptions=function(){return L0(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.vb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<GVa.length;f++){var h=Math.abs(b.width-GVa[f]);if(-1===e||d>=h)e=f,d=h}d=HVa[e];this.u&&g.Pl(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.hm(e.element,Math.round(h.width*a.width),f);g.dm(e.element,m,n);g.Xo(e.element,IVa);m=h.left+h.width/2;h=h.top+l/2;g.Uo(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Xo(e.element,HVa);g.Uo(e.element,d);(e=g.mh(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.Pl(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())T0(this,this.endscreen.impressionUrls),(a=g.fv())&&this.endscreen.visualElement&&g.kv(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.Uo(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Uo(b,"ytp-ce-shown");T0(this,c.impressionUrls);(b=g.fv())&&g.kv(b,c.visualElement);this.player.S().B&&this.player.Ma("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.Wo(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Wo(b,"ytp-ce-shown");this.player.S().B&&this.player.Ma("endscreenelementhidden",a)}};
g.k.Q_=function(a){var b=this;a.target===window&&(new g.K(function(){for(var c=g.r(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Xo(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var GVa=[346,426,470,506,570,640,853,1280,1920],HVa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),IVa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var JUa={d7:"current",dda:"new"};var LUa={CLOSE:"close",xda:"openUrl",SUBSCRIBE:"subscribe"},MUa={N3:"click",CLOSE:"close",G8:"hidden",efa:"rollOut",ffa:"rollOver",cga:"shown"};var CVa={I2:"anchored",oS:"branding",CHANNEL:"channel",c7:"cta",J8:"highlightText",n$:"label",PLAYLIST:"playlist",sea:"popup",oga:"speech",SUBSCRIBE:"subscribe",Lga:"title",VIDEO:"video",ria:"website"},BVa={oS:"branding",A3:"card",v7:"drawer",I8:"highlight",Yaa:"marker",Cea:"promotion",TEXT:"text",Uia:"widget"};g.w(b1,g.G);g.k=b1.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.bw(a,b,{id:c,namespace:"annotations_module"});d&&this.Sa.set(a,d);e&&this.Ua.set(a,e);this.context.G.Yd([a])};
g.k.Dz=function(){this.context.u.subscribe("resize",this.LA,this)};
g.k.IE=function(a,b,c,d,e,f){if(this.gb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.xh(this.element)};
g.k.LA=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=V0(a);if(f){var h=VUa(f,a.target),l=function(){a.j&&e.context.G.pauseVideo();var m=e.context.videoData.D||!1,n=g.yq(f||"");m&&n&&(n.v||n.list)?e.context.G.ul(n.v,b,n.list,!1):g.DH(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);r1(this.context.logger,c,l,d);UUa(f)||(c=g.fv(),d=b.itct,c&&d&&g.xv(c,g.Zu(d)))}};
g.k.ea=function(){this.Sa.clear();this.Ua.clear();g.G.prototype.ea.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.H(this,a);return a.element};g.w(g1,b1);g.k=g1.prototype;g.k.Bp=function(){this.Y&&h1(this,this.Y)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.im(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.LA=function(){var a=this.isAvailable();g.jm(this.element,a);g.M(this.context.G.getRootNode(),g.NO.IV_DRAWER_ENABLED,a);y0(this.G)};
g.k.destroy=function(){this.G.Hv(!1);try{this.G.getRootNode().removeChild(this.C)}catch(a){}g.du(this.W);g.Lt(this.ma);this.Oa&&this.Oa.dispose();this.D&&this.D.dispose();b1.prototype.destroy.call(this)};
g.k.LV=function(){if(this.B){r1(this.context.logger,l1(this).tracking.close);var a=g.fv();a&&this.J&&g.xv(a,this.J);f1(this)}};
g.k.XV=function(){g.M(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.uX=function(){var a=g.fv(),b=l1(this);b=b?b.kf:this.kf;a&&b&&g.nv(a,[b])};
g.k.tX=function(){var a=g.fv(),b=l1(this);b=b?b.kf:this.kf;a&&b&&g.ov(a,[b])};
g.k.nU=function(){var a=l1(this);r1(this.context.logger,a.tracking.wR);var b=g.fv();b&&a&&g.nv(b,[a.dj,a.kf])};
g.k.vX=function(){var a=g.fv(),b=l1(this);a&&b&&g.ov(a,[b.dj])};
g.k.mU=function(a){var b=l1(this),c=g.fv();this.j?a?(a=this.context.logger,r1(a,b.tracking.uD),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.dj&&g.xv(c,b.dj)):(a=this.context.logger,r1(a,b.tracking.uD),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.kf&&g.xv(c,b.kf)):(a=this.context.logger,r1(a,b.tracking.uD),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.kf&&g.xv(c,this.kf))};g.w(m1,b1);m1.prototype.Dz=function(){b1.prototype.Dz.call(this);jVa(this)};
m1.prototype.show=function(){b1.prototype.show.call(this);var a=g.fv(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.nv(a,[g.Zu(b.itct)])};
m1.prototype.hide=function(){b1.prototype.hide.call(this);var a=g.fv(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.ov(a,[g.Zu(b.itct)])};g.w(n1,m1);
n1.prototype.show=function(){if(!this.isActive){m1.prototype.show.call(this);if(!this.J){g.Uo(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({F:"img",Ba:["branding-img","iv-click-target"],T:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.jm(this.u,!1);var b=this.context.U.K("html5_player_branding_button_killswitch")?this.createElement({F:"div",Ba:["branding-img-container"]}):this.createElement({F:"button",Ba:["branding-img-container",
"ytp-button"]});b.appendChild(this.u);this.element.appendChild(b);var c=QUa(this.annotation);c&&(b=this.context.U.K("html5_player_branding_button_killswitch")?this.u:b,c1(this,b,c,this.annotation.id,a.session_data));nVa(this,a);this.J=!0}g.jm(this.element,!0);this.isActive=!0;this.u&&kVa(this,this.u)}};
n1.prototype.hide=function(){this.isActive&&(m1.prototype.hide.call(this),g.jm(this.element,!1),this.isActive=!1)};
n1.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);m1.prototype.destroy.call(this)};g.w(o1,m1);g.k=o1.prototype;g.k.show=function(){this.isActive||(m1.prototype.show.call(this),this.V||(pVa(this),this.V=!0),g.jm(this.element,!0),g.Wh(function(){g.Wo(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,q1(this),qVa(this),rVa(this,this.I))};
g.k.hide=function(){this.isActive&&(g.Uo(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.IE=function(a,b,c,d,e,f){return this.isCollapsed?!1:m1.prototype.IE.call(this,a,b,c,d,e,f)};
g.k.EW=function(a){this.N=!0;p1(this,500,a)};
g.k.DW=function(){this.N=!1;sVa(this)};
g.k.wW=function(a){a.stopPropagation();this.hide()};
g.k.xW=function(a){a.stopPropagation();q1(this);this.isCollapsed=!0;g.Uo(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();m1.prototype.destroy.call(this)};g.w(s1,g.lJ);g.k=s1.prototype;g.k.ag=function(a,b){if(!FVa(this.player.S().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.PZ(b))&&t1(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&($Ua(this.j,b),y0(this.player)),!0}return null};
g.k.getOptions=function(){return FVa(this.player.S().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Ls=function(){var a=this.player.S(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.gP||a.W.get(b.videoId)||g.ND(b)||g.OD(b)?!0:!1};
g.k.BC=function(){if(this.B){var a=this.player.Wa().getVideoContentRect(!0);g.hm(this.B.element,a.width,a.height);g.dm(this.B.element,a.left,a.top)}if(this.j){var b=this.player.Gk();a=this.j;b=b.width;g.M(a.C,"iv-drawer-small",426>=b);g.M(a.C,"iv-drawer-big",1280<=b)}};
g.k.oU=function(a){vVa(this,a.state);g.U(a.state,2)&&(this.Qh()&&this.Pl()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Hv(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Iq(h)&&h.responseXML?h.responseXML:null)&&(t1(b,h),g.Uo(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.lJ.prototype.load.call(this);vVa(this,this.player.wb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Qr()&&(a=xVa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.S().W.get(d);f&&yVa(e,f);f=f&&(f.QA||f.ox);if(!c.Ym||f)c.Sa?this.C=g.Oq(c.Sa,e):(this.Km=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.Km));
g.YI(this.player,this.B.element,4);this.BC();(f=g.ND(c))&&DVa(this,f);(f=g.OD(c))&&f.featuredChannel&&EVa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Sa&&(this.Km&&(this.player.removeEventListener("videodatachange",this.Km),this.Km=null),this.C=g.Oq(b.Sa,a))};
g.k.unload=function(){this.player.Mf("annotations_module");for(var a=g.r(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.J=null;this.j&&(this.j.destroy(),this.j=null,y0(this.player));this.C&&(this.C.abort(),this.C=null);this.I={};this.u.hide();g.lJ.prototype.unload.call(this);this.B.detach();this.Km&&(this.player.removeEventListener("videodatachange",this.Km),this.Km=null)};
g.k.iQ=function(a){a===this.player.getVideoData().videoId&&(this.loaded?zVa(this):this.load())};
g.k.Qh=function(){return!!this.j&&this.j.isAvailable()};
g.k.Pl=function(){return!!this.j&&this.j.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Qh();this.j&&(a?c?e1(this.j,c,b):e1(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):f1(this.j))};
g.k.Hv=function(a,b){this.player.X(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ea=function(){this.player.S().W.unsubscribe("vast_info_card_add",this.iQ,this);g.Wo(this.player.getRootNode(),g.NO.IV_DRAWER_OPEN);for(var a=this.N,b=g.Jo,c=0,d=a.length;c<d;c++)b.tj(a[c]);this.N.length=0;g.lJ.prototype.ea.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.H(this,a);return a.element};g.kJ("annotations_module",s1);g.kJ("creatorendscreen",K0);})(_yt_player);
