(function(g){var window=this;'use strict';var gXa=function(a,b){a.Ma("onAutonavCoundownStarted",b)},Q2=function(a,b,c){g.M(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.zf(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.LC&&(b.lengthText?(e=b.lengthText||null,f=b.Tr||null):b.lengthSeconds&&(e=g.rH(b.lengthSeconds),f=g.rH(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.HC(d).type;var l=b instanceof g.LC?b.isLivePlayback:null,m=b instanceof g.LC?b.isUpcoming:null;c={title:b.title,author:b.author,author_and_views:b.shortViewCount?b.author+" \u2022 "+b.shortViewCount:b.author,aria_label:b.ariaLabel||g.cF("Watch $TITLE",{TITLE:b.title}),duration:e,
timestamp:f,url:b.gm(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:b.shortViewCount?b.shortViewCount+" \u2022 "+b.publishedTimeText:b.publishedTimeText,autoplayAlternativeHeader:b.Po};b instanceof g.KC&&(c.playlist_length=b.playlistLength);a.update(c)},R2=function(a){var b=a.S(),c=b.j;
g.V.call(this,{F:"a",L:"ytp-autonav-suggestion-card",T:{href:"{{url}}",target:c?b.J:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},R:[{F:"div",Ba:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],T:{style:"{{background}}"},R:[{F:"div",T:{"aria-label":"{{timestamp}}"},Ba:["ytp-autonav-timestamp"],Z:"{{duration}}"},{F:"div",Ba:["ytp-autonav-live-stamp"],Z:"Live"},{F:"div",
Ba:["ytp-autonav-upcoming-stamp"],Z:"Upcoming"},{F:"div",L:"ytp-autonav-list-overlay",R:[{F:"div",L:"ytp-autonav-mix-text",Z:"Mix"},{F:"div",L:"ytp-autonav-mix-icon"}]}]},{F:"div",Ba:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Z:"{{title}}"},{F:"div",Ba:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Z:"{{author}}"},{F:"div",Ba:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],Z:"{{views_and_publish_time}}"}]});this.G=a;this.suggestion=
null;this.j=c;this.La("click",this.onClick);this.La("keypress",this.onKeyPress)},T2=function(a,b){b=void 0===b?!1:b;
g.V.call(this,{F:"div",L:"ytp-autonav-endscreen-countdown-container"});var c=this;this.I=b;this.D=void 0;this.u=0;b=a.S();var d=b.j;this.G=a;this.suggestion=null;this.onVideoDataChange("newdata",this.G.getVideoData());this.P(a,"videodatachange",this.onVideoDataChange);this.j=new g.V({F:"div",L:"ytp-autonav-endscreen-upnext-container",T:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},R:[{F:"div",
L:"ytp-autonav-endscreen-upnext-header"},{F:"div",L:"ytp-autonav-endscreen-upnext-alternative-header",Z:"{{autoplayAlternativeHeader}}"},{F:"a",L:"ytp-autonav-endscreen-link-container",T:{href:"{{url}}",target:d?b.J:""},R:[{F:"div",L:"ytp-autonav-endscreen-upnext-thumbnail",T:{style:"{{background}}"},R:[{F:"div",T:{"aria-label":"{{timestamp}}"},Ba:["ytp-autonav-timestamp"],Z:"{{duration}}"},{F:"div",Ba:["ytp-autonav-live-stamp"],Z:"Live"},{F:"div",Ba:["ytp-autonav-upcoming-stamp"],Z:"Upcoming"}]},
{F:"div",L:"ytp-autonav-endscreen-video-info",R:[{F:"div",L:"ytp-autonav-endscreen-premium-badge"},{F:"div",L:"ytp-autonav-endscreen-upnext-title",Z:"{{title}}"},{F:"div",L:"ytp-autonav-endscreen-upnext-author",Z:"{{author}}"},{F:"div",L:"ytp-autonav-view-and-date",Z:"{{views_and_publish_time}}"},{F:"div",L:"ytp-autonav-author-and-view",Z:"{{author_and_views}}"}]}]}]});g.H(this,this.j);this.j.xa(this.element);d||this.P(this.j.ya("ytp-autonav-endscreen-link-container"),"click",this.AL);this.G.yb(this.element,
this,115127);this.G.yb(this.j.ya("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.V({F:"div",L:"ytp-autonav-overlay"});g.H(this,this.overlay);this.overlay.xa(this.element);this.B=new g.V({F:"div",L:"ytp-autonav-endscreen-button-container"});g.H(this,this.B);this.B.xa(this.element);this.cancelButton=new g.V({F:"button",Ba:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],T:{"aria-label":"Cancel auto-play"},Z:"Cancel"});g.H(this,this.cancelButton);
this.cancelButton.xa(this.B.element);this.cancelButton.La("click",this.wU,this);this.G.yb(this.cancelButton.element,this,115129);this.playButton=new g.V({F:"a",Ba:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],T:{href:"{{url}}",role:"button","aria-label":"Play next video"},Z:"Play now"});g.H(this,this.playButton);this.playButton.xa(this.B.element);this.playButton.La("click",this.AL,this);this.G.yb(this.playButton.element,this,115130);this.C=new g.K(function(){S2(c)},
500);
g.H(this,this.C);this.zL();this.P(a,"autonavvisibility",this.zL)},W2=function(a){var b=a.G.Gk(!0,a.G.isFullscreen());
g.M(a.element,"ytp-autonav-endscreen-small-mode",a.hg(b));g.M(a.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.qD);g.M(a.G.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.G.We());g.M(a.G.getRootNode(),"countdown-running",a.Vi());g.M(a.element,"ytp-player-content",a.G.We());g.Pl(a.overlay.element,{width:b.width+"px"});if(!a.Vi()){a.G.We()?U2(a,Math.round(V2(a)/1E3)):U2(a);b=!!a.suggestion&&!!a.suggestion.Po;var c=a.G.We()||!b;g.M(a.element,"ytp-autonav-endscreen-upnext-alternative-header-only",
!c&&b);g.M(a.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.sG(a.B,a.G.We())}},S2=function(a){var b=V2(a),c=Math,d=c.min;
var e=a.u?Date.now()-a.u:0;c=d.call(c,e,b);U2(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Vi()?a.select(!0):a.Vi()&&a.C.start()},V2=function(a){if(a.G.isFullscreen()){var b;
a=null==(b=a.G.getVideoData())?void 0:b.Yw;return-1===a||void 0===a?8E3:a}return 0<=a.G.ip()?a.G.ip():g.yA(a.G.S().experiments,"autoplay_time")||1E4},U2=function(a,b){b=void 0===b?-1:b;
a=a.j.ya("ytp-autonav-endscreen-upnext-header");g.vh(a);if(0<=b){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.uh("Up next in $SECONDS".slice(0,d)));var e=g.th("span");g.So(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Ah(e,b);a.appendChild(e);a.appendChild(g.uh("Up next in $SECONDS".slice(d+c.length)));return}}g.Ah(a,"Up next")},X2=function(a,b){g.V.call(this,{F:"div",
Ba:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},Y2=function(a){g.V.call(this,{F:"div",
Ba:["ytp-upnext","ytp-player-content"],T:{"aria-label":"{{aria_label}}"},R:[{F:"div",L:"ytp-cued-thumbnail-overlay-image",T:{style:"{{background}}"}},{F:"span",L:"ytp-upnext-top",R:[{F:"span",L:"ytp-upnext-header",Z:"Up Next"},{F:"span",L:"ytp-upnext-title",Z:"{{title}}"},{F:"span",L:"ytp-upnext-author",Z:"{{author}}"}]},{F:"a",L:"ytp-upnext-autoplay-icon",T:{role:"button",href:"{{url}}","aria-label":"Play next video"},R:[{F:"svg",T:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},R:[{F:"circle",
L:"ytp-svg-autoplay-circle",T:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{F:"circle",L:"ytp-svg-autoplay-ring",T:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{F:"path",L:"ytp-svg-fill",T:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{F:"span",L:"ytp-upnext-bottom",R:[{F:"span",L:"ytp-upnext-cancel"},{F:"span",L:"ytp-upnext-paused",Z:"Auto-play is paused"}]}]});
this.api=a;this.cancelButton=null;this.D=this.ya("ytp-svg-autoplay-ring");this.B=this.notification=this.j=this.suggestion=null;this.C=new g.K(this.TA,5E3,this);this.u=0;var b=this.ya("ytp-upnext-cancel");this.cancelButton=new g.V({F:"button",Ba:["ytp-upnext-cancel-button","ytp-button"],T:{tabindex:"0","aria-label":"Cancel auto-play"},Z:"Cancel"});g.H(this,this.cancelButton);this.cancelButton.La("click",this.xU,this);this.cancelButton.xa(b);this.cancelButton&&this.api.yb(this.cancelButton.element,
this,115129);g.H(this,this.C);this.api.yb(this.element,this,18788);b=this.ya("ytp-upnext-autoplay-icon");this.P(b,"click",this.yU);this.api.yb(b,this,115130);this.BL();this.P(a,"autonavvisibility",this.BL);this.P(a,"mdxnowautoplaying",this.iZ);this.P(a,"mdxautoplaycanceled",this.jZ);g.M(this.element,"ytp-upnext-mobile",this.api.S().isMobile)},hXa=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.Yw;return-1===a||void 0===a?8E3:a}return 0<=a.api.ip()?a.api.ip():g.yA(a.api.S().experiments,"autoplay_time")||1E4},Z2=function(a,b){b=hXa(a,b);
var c=Math,d=c.min;var e=(0,g.Q)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Vi()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Vi()&&a.j.start()},$2=function(a){X2.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.V({F:"div",L:"ytp-suggestion-panel",R:[{F:"div",Ba:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Z:"More videos"}]});this.J=new g.V({F:"div",L:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.I=!1;this.u=new T2(this.player);g.H(this,this.u);this.u.xa(this.element);a.getVideoData().rd?this.j=this.u:(this.j=new Y2(a),g.YI(this.player,this.j.element,4),g.H(this,this.j));this.overlay=new g.V({F:"div",L:"ytp-autonav-overlay-cancelled-state"});
g.H(this,this.overlay);this.overlay.xa(this.element);this.C=new g.Dz(this);g.H(this,this.C);g.H(this,this.table);this.table.xa(this.element);this.table.show();g.H(this,this.J);this.J.xa(this.table.element);this.hide()},a3=function(a){var b=a.We();
b!==a.D&&(a.D=b,a.player.X("autonavvisibility"),a.D?(a.u!==a.j&&a.u.hide(),a.table.hide()):(a.u!==a.j&&a.u.show(),a.table.show()))},b3=function(a){X2.call(this,a,"subscribecard-endscreen");
this.j=new g.V({F:"div",L:"ytp-subscribe-card",R:[{F:"img",L:"ytp-author-image",T:{src:"{{profilePicture}}"}},{F:"div",L:"ytp-subscribe-card-right",R:[{F:"div",L:"ytp-author-name",Z:"{{author}}"},{F:"div",L:"html5-subscribe-button-container"}]}]});g.H(this,this.j);this.j.xa(this.element);var b=a.getVideoData();this.subscribeButton=new g.DK("Subscribe",null,"Unsubscribe",null,!0,!1,b.hk,b.subscribed,"trailer-endscreen",null,null,a);g.H(this,this.subscribeButton);this.subscribeButton.xa(this.j.ya("html5-subscribe-button-container"));
this.P(a,"videodatachange",this.Ea);this.Ea();this.hide()},c3=function(a){var b=a.S(),c=g.Hz||g.HB?{style:"will-change: opacity"}:void 0,d=b.j,e=["ytp-videowall-still"];
b.isMobile&&e.push("ytp-videowall-show-text");g.V.call(this,{F:"a",Ba:e,T:{href:"{{url}}",target:d?b.J:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},R:[{F:"div",L:"ytp-videowall-still-image",T:{style:"{{background}}"}},{F:"span",L:"ytp-videowall-still-info",R:[{F:"span",L:"ytp-videowall-still-info-bg",R:[{F:"span",L:"ytp-videowall-still-info-content",T:c,R:[{F:"span",L:"ytp-videowall-still-info-title",Z:"{{title}}"},{F:"span",
L:"ytp-videowall-still-info-author",Z:"{{author_and_views}}"},{F:"span",L:"ytp-videowall-still-info-live",Z:"Live"},{F:"span",L:"ytp-videowall-still-info-duration",Z:"{{duration}}"}]}]}]},{F:"span",Ba:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],R:[{F:"span",L:"ytp-videowall-still-listlabel-icon"},"Playlist",{F:"span",L:"ytp-videowall-still-listlabel-length",R:[" (",{F:"span",Z:"{{playlist_length}}"},")"]}]},{F:"span",Ba:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
R:[{F:"span",L:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{F:"span",L:"ytp-videowall-still-listlabel-length",Z:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.j=new g.Dz(this);g.H(this,this.j);this.La("click",this.onClick);this.La("keypress",this.onKeyPress);this.j.P(a,"videodatachange",this.onVideoDataChange);a.Th(this.element,this);this.onVideoDataChange()},d3=function(a){X2.call(this,a,"videowall-endscreen");
var b=this;this.G=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.J=!1;this.N=null;this.u=new g.Dz(this);g.H(this,this.u);this.I=new g.K(function(){g.Uo(b.element,"ytp-show-tiles")},0);
g.H(this,this.I);var c=new g.V({F:"button",Ba:["ytp-button","ytp-endscreen-previous"],T:{"aria-label":"Previous"},R:[g.xG()]});g.H(this,c);c.xa(this.element);c.La("click",this.CU,this);this.table=new g.pG({F:"div",L:"ytp-endscreen-content"});g.H(this,this.table);this.table.xa(this.element);c=new g.V({F:"button",Ba:["ytp-button","ytp-endscreen-next"],T:{"aria-label":"Next"},R:[g.yG()]});g.H(this,c);c.xa(this.element);c.La("click",this.BU,this);a.getVideoData().rd?this.j=new T2(a,!0):this.j=new Y2(a);
g.H(this,this.j);g.YI(this.player,this.j.element,4);this.hide()},e3=function(a){return g.ZI(a.player)&&a.jx()&&!a.C},f3=function(a){var b=a.We();
b!==a.J&&(a.J=b,a.player.X("autonavvisibility"))},g3=function(a){g.lJ.call(this,a);
var b=this;this.endScreen=null;this.j=this.u=this.B=!1;this.listeners=new g.Dz(this);g.H(this,this.listeners);this.env=a.S();iXa(a)?(this.B=!0,jXa(this),this.j?this.endScreen=new $2(a):this.endScreen=new d3(this.player)):this.env.Oe?this.endScreen=new b3(this.player):this.endScreen=new X2(this.player);g.H(this,this.endScreen);g.YI(this.player,this.endScreen.element,4);kXa(this);this.listeners.P(a,"videodatachange",this.onVideoDataChange,this);this.listeners.P(a,g.dw("endscreen"),function(c){b.onCueRangeEnter(c)});
this.listeners.P(a,g.ew("endscreen"),function(c){b.onCueRangeExit(c)})},jXa=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Zh&&a.u===b.rd)return!1;a.j=b.Zh;a.u=b.rd;return!0},iXa=function(a){a=a.S();
return!a.C&&a.Jc&&!a.Oe},kXa=function(a){a.player.Mf("endscreen");
var b=a.player.getVideoData();b=new g.bw(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.bw(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.Yd([b,c])};
g.RI.prototype.ip=g.ca(4,function(){return this.app.ip()});
g.aT.prototype.ip=g.ca(3,function(){return this.getVideoData().aP});g.w(R2,g.V);R2.prototype.select=function(){(this.G.ul(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Ex||void 0)||this.G.K("web_player_endscreen_double_log_fix_killswitch"))&&this.G.rb(this.element)};
R2.prototype.onClick=function(a){g.LJ(a,this.G,this.j,this.suggestion.sessionData||void 0)&&this.select()};
R2.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.Rt(a)||(this.select(),g.Qt(a))}};g.w(T2,g.V);g.k=T2.prototype;g.k.zA=function(a){this.suggestion!==a&&(this.suggestion=a,Q2(this.j,a),this.playButton.Ia("url",this.suggestion.gm()),W2(this))};
g.k.Vi=function(){return 0<this.u};
g.k.Ov=function(){this.Vi()||(this.u=Date.now(),S2(this),gXa(this.G,V2(this)),g.M(this.G.getRootNode(),"countdown-running",this.Vi()))};
g.k.ws=function(){this.Ao();S2(this);var a=this.j.ya("ytp-autonav-endscreen-upnext-header");a&&g.Ah(a,"Up next")};
g.k.Ao=function(){this.Vi()&&(this.C.stop(),this.u=0)};
g.k.select=function(a){this.G.nextVideo(!1,void 0===a?!1:a);this.Ao()};
g.k.AL=function(a){g.LJ(a,this.G)&&(a.currentTarget===this.playButton.element?this.G.rb(this.playButton.element):a.currentTarget===this.j.ya("ytp-autonav-endscreen-link-container")&&(a=this.j.ya("ytp-autonav-endscreen-link-container"),this.G.Va(a,!0),this.G.rb(a)),this.select())};
g.k.wU=function(){this.G.rb(this.cancelButton.element);g.TI(this.G,!0);this.D&&this.G.Ma("innertubeCommand",this.D)};
g.k.onVideoDataChange=function(a,b){var c;this.D=null==(c=b.P1)?void 0:c.command};
g.k.zL=function(){var a=this.G.We();this.I&&this.ob!==a&&g.sG(this,a);W2(this);this.G.Va(this.element,a);this.G.Va(this.cancelButton.element,a);this.G.Va(this.j.ya("ytp-autonav-endscreen-link-container"),a);this.G.Va(this.playButton.element,a)};
g.k.hg=function(a){return 400>a.width||459>a.height};g.w(X2,g.V);g.k=X2.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.jx=function(){return!1};
g.k.We=function(){return!1};
g.k.DO=function(){return!1};g.w(Y2,g.V);g.k=Y2.prototype;g.k.TA=function(){this.notification&&(this.C.stop(),this.vc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.k.zA=function(a){this.suggestion=a;Q2(this,a,"hqdefault.jpg")};
g.k.BL=function(){g.sG(this,this.api.We());this.api.Va(this.element,this.api.We());this.api.Va(this.ya("ytp-upnext-autoplay-icon"),this.api.We());this.cancelButton&&this.api.Va(this.cancelButton.element,this.api.We())};
g.k.rZ=function(){window.focus();this.TA()};
g.k.Ov=function(a){var b=this;this.Vi()||(g.eu("a11y-announce","Up Next "+this.suggestion.title),this.u=(0,g.Q)(),this.j=new g.K(function(){Z2(b,a)},25),Z2(this,a),gXa(this.api,hXa(this,a)));
g.Wo(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.V.prototype.hide.call(this)};
g.k.Vi=function(){return!!this.j};
g.k.ws=function(){this.Ao();this.u=(0,g.Q)();Z2(this);g.Uo(this.element,"ytp-upnext-autoplay-paused")};
g.k.Ao=function(){this.Vi()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.S().K("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.TA(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.zf()}),this.B=this.P(this.notification,"click",this.rZ),this.C.start())}this.Ao();this.api.nextVideo(!1,a)};
g.k.yU=function(a){!g.zh(this.cancelButton.element,g.Mt(a))&&g.LJ(a,this.api)&&(this.api.We()&&this.api.rb(this.ya("ytp-upnext-autoplay-icon")),this.select())};
g.k.xU=function(){this.api.We()&&this.cancelButton&&this.api.rb(this.cancelButton.element);g.TI(this.api,!0)};
g.k.iZ=function(a){this.api.getPresentingPlayerType();this.show();this.Ov(a)};
g.k.jZ=function(){this.api.getPresentingPlayerType();this.Ao();this.hide()};
g.k.ea=function(){this.Ao();this.TA();g.V.prototype.ea.call(this)};g.w($2,X2);g.k=$2.prototype;g.k.create=function(){X2.prototype.create.call(this);this.C.P(this.player,"appresize",this.Ow);this.C.P(this.player,"onVideoAreaChange",this.Ow);this.C.P(this.player,"videodatachange",this.onVideoDataChange);this.C.P(this.player,"autonavchange",this.CL);this.C.P(this.player,"autonavcancel",this.zU);this.onVideoDataChange()};
g.k.show=function(){X2.prototype.show.call(this);(this.I||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.TI(this.player,!1);g.ZI(this.player)&&this.jx()&&!this.B?(a3(this),2===this.videoData.autonavState?this.player.S().K("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Ov():3===this.videoData.autonavState&&this.j.ws()):(g.TI(this.player,!0),a3(this));this.Ow()};
g.k.hide=function(){X2.prototype.hide.call(this);this.j.ws();a3(this)};
g.k.Ow=function(){var a=this.player.Gk(!0,this.player.isFullscreen());a3(this);W2(this.u);g.M(this.element,"ytp-autonav-cancelled-small-mode",this.hg(a));g.M(this.element,"ytp-autonav-cancelled-tiny-mode",this.ZB(a));g.M(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.Pl(this.overlay.element,{width:a.width+"px"});if(!this.D){a=g.r(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.r(b.value);b=c.next().value;c=c.next().value;g.M(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length){this.j.zA(a[0]);this.j!==this.u&&this.u.zA(a[0]);for(var b=0;b<lXa.length;++b){var c=lXa[b];if(a&&a[c]){this.videos[b]=new R2(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,Q2(d,c));g.H(this,this.videos[b]);this.videos[b].xa(this.J.element)}}}this.Ow()}};
g.k.CL=function(a){1===a?(this.I=!1,this.B=this.videoData.clientPlaybackNonce,this.j.Ao(),this.ob&&this.Ow()):(this.I=!0,this.We()&&(2===a?this.j.Ov():3===a&&this.j.ws()))};
g.k.zU=function(a){a?this.CL(1):(this.B=null,this.I=!1)};
g.k.jx=function(){return 1!==this.videoData.autonavState};
g.k.hg=function(a){return(910>a.width||459>a.height)&&!this.ZB(a)&&!(400>=a.width||360>=a.height)};
g.k.ZB=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.We=function(){return this.ob&&g.ZI(this.player)&&this.jx()&&!this.B};
var lXa=[1,3,2,4];g.w(b3,X2);b3.prototype.Ea=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.hk;var b=this.subscribeButton;a.subscribed?b.u():b.B()};g.w(c3,g.V);c3.prototype.select=function(){(this.api.ul(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Ex||void 0)||this.api.K("web_player_endscreen_double_log_fix_killswitch"))&&this.api.rb(this.element)};
c3.prototype.onClick=function(a){g.LJ(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
c3.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.Rt(a)||(this.select(),g.Qt(a))}};
c3.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.S();this.u=a.D?!1:b.j};g.w(d3,X2);g.k=d3.prototype;g.k.create=function(){X2.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Sm();this.u.P(this.player,"appresize",this.Sm);this.u.P(this.player,"onVideoAreaChange",this.Sm);this.u.P(this.player,"videodatachange",this.onVideoDataChange);this.u.P(this.player,"autonavchange",this.JE);this.u.P(this.player,"autonavcancel",this.AU);a=this.videoData.autonavState;a!==this.N&&this.JE(a);this.u.P(this.element,"transitionend",this.E_)};
g.k.destroy=function(){g.Du(this.u);g.rf(this.stills);this.stills=[];X2.prototype.destroy.call(this);g.Wo(this.element,"ytp-show-tiles");this.I.stop();this.N=this.videoData.autonavState};
g.k.jx=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){X2.prototype.show.call(this);g.Wo(this.element,"ytp-show-tiles");this.player.S().isMobile?g.Oo(this.I):this.I.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.TI(this.player,!1);e3(this)?(f3(this),2===this.videoData.autonavState?this.player.S().K("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Ov():3===this.videoData.autonavState&&this.j.ws()):(g.TI(this.player,!0),f3(this))};
g.k.hide=function(){X2.prototype.hide.call(this);this.j.ws();f3(this)};
g.k.E_=function(a){g.Mt(a)===this.element&&this.Sm()};
g.k.Sm=function(){if(this.videoData&&this.videoData.suggestions&&this.videoData.suggestions.length){g.Uo(this.element,"ytp-endscreen-paginate");var a=this.G.Gk(!0,this.G.isFullscreen()),b=g.OI(this.G);b&&(b=b.Hf()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.videoData.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var p=b/2,q=e/2,t=b<=f-2&&n>=q*m,v=e<=h-2&&n>=p*m;if((p+
1)/q*d/c>c/(p/(q+1)*d)&&v)n-=p*m,e+=2;else if(t)n-=q*m,b+=2;else if(v)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.hm(a,m,n);g.Pl(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.j.zA(this.videoData.suggestions[0]);this.j instanceof T2&&W2(this.j);g.M(this.element,"ytp-endscreen-takeover",e3(this));f3(this);m+=4;n+=4;for(f=
c=0;f<b;f++)for(h=0;h<e;h++)if(q=c,p=0,d&&f>=b-2&&h>=e-2?p=1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(p=2):p=2),q=g.Ng(q+this.B,l),0!==p){t=this.stills[c];t||(t=new c3(this.player),this.stills[c]=t,a.appendChild(t.element));v=Math.floor(n*h/e);var x=Math.floor(m*f/b),y=Math.floor(n*(h+p)/e)-v-4,z=Math.floor(m*(f+p)/b)-x-4;g.dm(t.element,x,v);g.hm(t.element,z,y);g.Pl(t.element,"transitionDelay",(h+f)/20+"s");g.M(t.element,"ytp-videowall-still-mini",1===p);g.M(t.element,"ytp-videowall-still-large",
2<p);p=t;q=this.videoData.suggestions[q];p.suggestion!==q&&(p.suggestion=q,t=p.api.S(),v=g.To(p.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",Q2(p,q,v),g.JB(t)&&(v=q.gm(),x={},t.oa&&g.jI(x,t.loaderUrl),v=g.zi(v,g.iI(x,"emb_rel_end")),p.Ia("url",v)),(q=(q=q.sessionData)&&q.itct)&&p.api.bl(p.element,q));c++}g.M(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.xh(e.element),g.qf(e);this.stills.length=c}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.Sm())};
g.k.BU=function(){this.B+=this.stills.length;this.Sm()};
g.k.CU=function(){this.B-=this.stills.length;this.Sm()};
g.k.DO=function(){return this.j.Vi()};
g.k.JE=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Ao(),this.ob&&this.Sm()):(this.D=!0,this.ob&&e3(this)&&(2===a?this.j.Ov():3===a&&this.j.ws()))};
g.k.AU=function(a){if(a){for(a=0;a<this.stills.length;a++)this.G.Va(this.stills[a].element,!0);this.JE(1)}else this.C=null,this.D=!1;this.Sm()};
g.k.We=function(){return this.ob&&e3(this)};g.w(g3,g.lJ);g.k=g3.prototype;g.k.Ls=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!iXa(this.player)||b;var c=a.qf||g.UB(a.u),d=this.player.Lx();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.We=function(){return this.endScreen.We()};
g.k.iX=function(){return this.We()?this.endScreen.DO():!1};
g.k.ea=function(){this.player.Mf("endscreen");g.lJ.prototype.ea.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.RO;if(b&&b.videoId){var c=this.player.ib().Wd.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].videoId&&!a.PL?a=!1:(this.player.ul(b.videoId,void 0,void 0,!0,!0,b),c&&c.hC("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.lJ.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.lJ.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Ls()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){kXa(this);this.B&&jXa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new $2(this.player):this.endScreen=new d3(this.player),g.H(this,this.endScreen),g.YI(this.player,this.endScreen.element,4))};g.kJ("endscreen",g3);})(_yt_player);
