(function(g){var window=this;'use strict';var aYa=function(a,b){var c=[];return g.Cs(a,{query:b},function(d){c.push(d.getValue());return d.continue()}).then(function(){return c})},V3=function(a,b){return"getAll"in IDBIndex.prototype?g.ps(a.j.getAll(b,void 0)):aYa(a,b)},bYa=function(a,b){return g.ws(a,["captions"],{mode:"readonly",
Cc:!0},function(c){return g.Ina(c.objectStore("captions"),b)})},cYa=function(a){var b=new g.bx("und",new g.Cz("Default","und",!0));
b.captionTracks=a.captionTracks;return b},dYa=function(a){return new g.Mh(function(b,c){var d=a.length,e=[];
if(d)for(var f=function(n,p){d--;e[n]=p;0==d&&b(e)},h=function(n){c(n)},l=0,m;l<a.length;l++)m=a[l],g.pca(m,g.Sa(f,l),h);
else b(e)})},W3=function(a){this.j=a},X3=function(){W3.apply(this,arguments)},Y3=function(){X3.apply(this,arguments)},Z3=function(){X3.apply(this,arguments)},$3=function(){X3.apply(this,arguments)},a4=function(){W3.apply(this,arguments)},b4=function(){X3.apply(this,arguments)},c4=function(){X3.apply(this,arguments)},d4=function(){X3.apply(this,arguments)},e4=function(){X3.apply(this,arguments)},f4=function(){X3.apply(this,arguments)},g4=function(){X3.apply(this,arguments)},h4=function(){X3.apply(this,
arguments)},i4=function(){X3.apply(this,arguments)},j4=function(){X3.apply(this,arguments)},k4=function(){X3.apply(this,arguments)},l4=function(){X3.apply(this,arguments)},m4=function(){X3.apply(this,arguments)},n4=function(){W3.apply(this,arguments)},o4=function(){X3.apply(this,arguments)},p4=function(){X3.apply(this,arguments)},q4=function(){X3.apply(this,arguments)},r4=function(){X3.apply(this,arguments)},s4=function(){X3.apply(this,arguments)},t4=function(){X3.apply(this,arguments)},u4=function(){X3.apply(this,
arguments)},v4=function(){X3.apply(this,arguments)},w4=function(){X3.apply(this,arguments)},x4=function(){X3.apply(this,arguments)},y4=function(){X3.apply(this,arguments)},z4=function(){X3.apply(this,arguments)},A4=function(){X3.apply(this,arguments)},B4=function(){X3.apply(this,arguments)},C4=function(){X3.apply(this,arguments)},D4=function(){X3.apply(this,arguments)},E4=function(){X3.apply(this,arguments)},F4=function(){X3.apply(this,arguments)},G4=function(){X3.apply(this,arguments)},H4=function(){X3.apply(this,
arguments)},I4=function(){X3.apply(this,arguments)},J4=function(){X3.apply(this,arguments)},K4=function(){X3.apply(this,arguments)},L4=function(){X3.apply(this,arguments)},M4=function(){X3.apply(this,arguments)},N4=function(){X3.apply(this,arguments)},O4=function(){X3.apply(this,arguments)},P4=function(){X3.apply(this,arguments)},Q4=function(){X3.apply(this,arguments)},R4=function(){X3.apply(this,arguments)},eYa=function(a){var b=g.OC();
b=Object.assign({},b);a=Object.assign({},a);for(var c in b)a[c]?(4!==b[c]&&(b[c]=a[c]),delete a[c]):2!==b[c]&&(b[c]=4);Object.assign(b,a);g.Hva(b);JSON.stringify(b);return b},fYa=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,g.Ms(),2);if(3!=d.j)return(b=d.u)?g.A(d,g.RC(b),3):d.return();c=d.u;return d.return(g.ws(c,["index","media","captions"],{mode:"readwrite",Cc:!0},function(e){var f=IDBKeyRange.bound(a+"|",a+"~");e=[e.objectStore("index").delete(f),e.objectStore("media").delete(f),e.objectStore("captions").delete(f)];return g.ns.all(e).then(function(){})}))})},gYa=function(){var a,b;
return g.B(function(c){if(1==c.j)return g.A(c,g.Ms(),2);if(3!=c.j){a=c.u;if(!a)throw g.ls("rvdfd");return g.A(c,g.RC(a),3)}b=c.u;return c.return(g.ws(b,["index","media"],{mode:"readwrite",Cc:!0},function(d){var e={};return g.As(d.objectStore("index"),{},function(f){var h=f.getKey().match(/^([\w\-_]+)\|(a|v)$/),l=g.ns.resolve(void 0);if(h){var m=h[1];h=h[2];e[m]=e[m]||{};var n;e[m][h]=g.Mva(null==(n=f.getValue())?void 0:n.fmts)}else l=f.delete().then(function(){});
return g.ns.all([f.continue(),l]).then(function(p){return g.r(p).next().value})}).then(function(){for(var f={},h=g.r(Object.keys(e)),l=h.next();!l.done;l=h.next()){l=l.value;
var m=e[l].v;f[l]=e[l].a&&m?1:2}var n=eYa(f);return g.Lna(d.objectStore("media"),{},function(p){var q=p.getKey().match(g.Qva);q&&f[q[1]]||d.objectStore("media").delete(p.getKey());return p.continue()}).then(function(){return n})})}))})},hYa=function(a,b){var c,d;
return g.B(function(e){if(1==e.j)return g.A(e,g.Ms(),2);if(3!=e.j){c=e.u;if(!c)throw g.ls("wct");return g.A(e,g.RC(c),3)}d=e.u;return g.A(e,g.ws(d,["captions"],{mode:"readwrite",Cc:!0},function(f){var h=[];f=f.objectStore("captions");for(var l=0;l<b.length;l++){var m=g.xs(f,b[l],a+"|"+b[l].metadata.vss_id);h.push(m)}return g.ns.all(h)}),0)})},iYa=function(a){var b,c,d;
return g.B(function(e){if(1==e.j)return b=IDBKeyRange.bound(a+"|",a+"~"),g.A(e,g.Ms(),2);if(3!=e.j){c=e.u;if(!c)throw g.ls("gactfv");return g.A(e,g.RC(c),3)}d=e.u;return e.return(bYa(d,b))})},jYa=function(a){return g.B(function(b){g.QC(a,0);
return b.return(fYa(a))})},kYa=function(a){return{context:g.PF(),
videoIds:a}},S4=function(a){a=a.key||a.id;
if(!a)throw Error("Entity key is missing");return a},lYa=function(){if(T4)return T4();
var a={};T4=g.$s("PersistentEntityStoreDb",{Zr:(a.EntityStore={Oo:1},a.EntityAssociationStore={Oo:2},a),Ez:!1,upgrade:function(b,c){c(1)&&g.zs(g.us(b,"EntityStore",{keyPath:"key"}),"entityType","entityType");c(2)&&(b=g.us(b,"EntityAssociationStore",{keyPath:["parentEntityKey","childEntityKey"]}),g.zs(b,"byParentEntityKey","parentEntityKey"),g.zs(b,"byChildEntityKey","childEntityKey"))},
version:3});return T4()},mYa=function(a){return g.Fs(lYa(),a)},U4=function(a,b){b=void 0===b?{}:b;
g.bs.call(this,g.ZTa[a],Object.assign({},{name:"PESEncoderError",type:a},b));this.type=a;this.level="WARNING";Object.setPrototypeOf(this,U4.prototype)},nYa=function(a){return new U4("WRONG_DATA_TYPE",{bW:a})},oYa=function(a){return a instanceof Error?new U4("UNKNOWN_ENCODE_ERROR",{originalMessage:a.message}):new U4("UNKNOWN_ENCODE_ERROR")},pYa=function(a){return a instanceof Error?new U4("UNKNOWN_DECODE_ERROR",{originalMessage:a.message}):new U4("UNKNOWN_DECODE_ERROR")},qYa=function(a,b){a=a instanceof
U4?a:b(a);
g.R(a);throw a;},rYa=function(){},sYa=function(a,b,c){try{return a.B(b,c)}catch(d){qYa(d,oYa)}},V4=function(a){a=(new TextEncoder).encode(a).subarray(0,16);
var b=new Uint8Array(16);b.set(a);return b},W4=function(a){this.j=a},uYa=function(a){var b=tYa[a];
if(b)return b;g.Wu(new g.bs("Entity model not found.",{entityType:a}))},vYa=function(a,b){this.j=a;
this.u=b;this.B={}},Y4=function(a,b){a:{a=X4(a.u,b.version);
try{var c=a.u(b.data,b.key);break a}catch(d){qYa(d,pYa)}c=void 0}return c},Z4=function(a,b,c){return a.j.objectStore("EntityStore").get(b).then(function(d){if(d){if(c&&d.entityType!==c)throw Error("Incorrect entity type");
return Y4(a,d)}})},$4=function(a,b,c){return c?(c=c.map(function(d){return Z4(a,d,b)}),g.ns.all(c)):V3(a.j.objectStore("EntityStore").index("entityType"),IDBKeyRange.only(b)).then(function(d){return d.map(function(e){return Y4(a,e)})})},b5=function(a,b,c){var d=S4(b),e=X4(a.u,1),f=Object.assign({},b);
return a.j.objectStore("EntityStore").get(d).then(function(h){if(h){if(h.entityType!==c)throw Error("Incorrect entity type");f.entityMetadata||(h=Y4(a,h),f.entityMetadata=h.entityMetadata)}}).then(function(){var h={key:d,
entityType:c,data:sYa(e,f,d),version:1};return g.ns.all([g.xs(a.j.objectStore("EntityStore"),h),wYa(a,f,c)])}).then(function(){a5(a,d,c);
return d})},c5=function(a,b,c){b=b.map(function(d){return b5(a,d,c)});
return g.ns.all(b)},d5=function(a,b,c){if(null==c?0:c.zF){var d=new Set;
return xYa(a,b,d).then(function(){for(var f=[],h=g.r(d),l=h.next();!l.done;l=h.next())f.push(d5(a,l.value));return g.ns.all(f).then(function(){})})}var e=g.EI(b).entityType;
return g.ns.all([a.j.objectStore("EntityStore").delete(b),e5(a,b)]).then(function(){a5(a,b,e)})},yYa=function(a,b){return g.Cs(a.j.objectStore("EntityStore").index("entityType"),{query:IDBKeyRange.only(b)},function(c){return g.ns.all([c.delete(),
e5(a,c.EB())]).then(function(){a5(a,c.EB(),b);return c.continue()})})},zYa=function(a,b,c,d){var e=X4(a.u,1);
return Z4(a,b,d).then(function(f){if(f){f=g.oI(f,c);var h={key:b,entityType:d,data:sYa(e,f,b),version:1};return g.ns.all([g.xs(a.j.objectStore("EntityStore"),h),wYa(a,f,d)])}}).then(function(){a5(a,b,d);
return b})},a5=function(a,b,c){var d=a.B[c];
d||(d=new Set,a.B[c]=d);d.add(b)},AYa=function(a,b,c){var d=S4(b);
c=uYa(c);if(!c)return g.ns.resolve([]);c=new c(b);a=a.j.objectStore("EntityAssociationStore");b=[];c=g.r(c.u());for(var e=c.next();!e.done;e=c.next())b.push(g.xs(a,{parentEntityKey:d,childEntityKey:e.value}));return g.ns.all(b).then(function(f){return f.map(function(h){return h[1]})})},e5=function(a,b){return a.j.objectStore("EntityAssociationStore").index("byParentEntityKey").delete(IDBKeyRange.only(b))},wYa=function(a,b,c){var d=S4(b);
return e5(a,d).then(function(){return AYa(a,b,c)})},xYa=function(a,b,c){if(c.has(b))return g.ns.resolve(void 0);
c.add(b);return BYa(a,b).then(function(d){return a.j.objectStore("EntityAssociationStore").index("byParentEntityKey").delete(IDBKeyRange.only(b)).then(function(){return d})}).then(function(d){var e=g.ns.resolve(void 0),f={};
d=g.r(d);for(var h=d.next();!h.done;f={RD:f.RD},h=d.next())f.RD=h.value,e=e.then(function(l){return function(){return xYa(a,l.RD,c)}}(f));
return e}).then(function(){})},BYa=function(a,b){var c=a.j.objectStore("EntityAssociationStore");
return V3(c.index("byParentEntityKey"),IDBKeyRange.only(b)).then(function(d){var e=[];d=g.r(d);for(var f=d.next();!f.done;f=d.next())f=f.value,e.push(V3(c.index("byChildEntityKey"),f.childEntityKey));return g.ns.all(e)}).then(function(d){var e=[];
d=g.r(d);for(var f=d.next();!f.done;f=d.next())f=f.value,1===f.length&&e.push(f[0].childEntityKey);return e})},f5=function(){},CYa=function(){this.j={};
this.j[0]=new f5;if(!g.P("aes_pes_encoder_killswitch")){var a=this.j;try{var b=g.cs();var c=V4(b);var d=new W4(new g.TA(c),new g.SA(c))}catch(e){throw a=e instanceof Error?new U4("KEY_CREATION_FAILED",{originalMessage:e.message}):new U4("KEY_CREATION_FAILED"),g.R(a),a;}a[1]=d}},X4=function(a,b){b=void 0===b?0:b;
a=a.j[b];if(!a)throw b=new U4("INVALID_ENCODER_VERSION",{bW:b}),g.R(b),b;return a},g5=function(a,b){g.G.call(this);
this.token=a;this.u=b;this.j=[];a=new g.C.BroadcastChannel("PERSISTENT_ENTITY_STORE_SYNC:"+g.cs());a.onmessage=this.B.bind(this);this.channel=a},h5=function(a,b,c){var d,e,f,h;
return g.B(function(l){if(1==l.j)return g.A(l,mYa(a.token),2);if(3!=l.j)return d=l.u,g.A(l,g.ws(d,["EntityStore","EntityAssociationStore"],b,function(m){e=new vYa(m,a.u);return c(e)}),3);
f=l.u;e&&(h=e.B,0<Object.keys(h).length&&(a.channel.postMessage(h),DYa(a,h)));return l.return(f)})},i5=function(a,b){a.j.push(b);
return function(){var c=a.j.indexOf(b);0<=c&&a.j.splice(c,1)}},j5=function(a,b,c){return h5(a,{mode:"readwrite",
Cc:!0},function(d){return b5(d,b,c)})},EYa=function(a,b){return h5(a,{mode:"readwrite",
Cc:!0},function(c){return c5(c,b,"offlineOrchestrationActionWrapperEntity")})},FYa=function(a,b){return h5(a,{mode:"readwrite",
Cc:!0},function(c){return d5(c,b)})},k5=function(a,b,c){return h5(a,{mode:"readonly",
Cc:!0},function(d){return Z4(d,b,c)})},l5=function(a,b,c){return h5(a,{mode:"readonly",
Cc:!0},function(d){return $4(d,b,c)})},DYa=function(a,b){a=g.r(a.j);
for(var c=a.next();!c.done;c=a.next())c=c.value,c(b)},GYa=function(){var a,b,c;
return g.B(function(d){if(1==d.j)return g.ta(d,2),g.A(d,g.Ms(),4);if(2!=d.j){a=d.u;if(!a||!g.ds()||"undefined"===typeof g.C.BroadcastChannel)return d.return();b=new CYa;return d.return(new g5(a,b))}c=g.va(d);c instanceof Error&&g.R(c);return d.return()})},n5=function(){m5||(m5=GYa());
return m5},HYa=function(a){var b;
a=null==(b=a.options)?void 0:b.persistenceOption;return"ENTITY_PERSISTENCE_OPTION_PERSIST"===a||"ENTITY_PERSISTENCE_OPTION_INMEMORY_AND_PERSIST"===a},IYa=function(a){var b;
return g.B(function(c){return 1==c.j?g.A(c,n5(),2):(b=c.u)?g.A(c,h5(b,"readwrite",function(d){for(var e={},f={},h=g.r(a),l=h.next();!l.done;f={hh:f.hh,vt:f.vt},l=h.next())f.hh=l.value,f.hh.entityKey&&HYa(f.hh)&&(f.vt=g.Df(f.hh.payload),l=void 0,"ENTITY_MUTATION_TYPE_REPLACE"===f.hh.type&&(l=function(m){return function(){return b5(d,m.hh.payload[m.vt],m.vt)}}(f)),"ENTITY_MUTATION_TYPE_DELETE"===f.hh.type&&(l=function(m){return function(){return d5(d,m.hh.entityKey)}}(f)),"ENTITY_MUTATION_TYPE_UPDATE"===
f.hh.type&&(l=function(m){return function(){return zYa(d,m.hh.entityKey,m.hh.payload[m.vt],m.vt)}}(f)),l&&(e[f.hh.entityKey]=e[f.hh.entityKey]?e[f.hh.entityKey].then(l):l()));
return g.ns.all(Object.values(e))}),0):c.return()})},JYa=function(a){var b;
return g.B(function(c){if(1==c.j){b=a.mutations;if(!b||0>=b.length)return c.return();if(g.e0){var d={type:"ENTITY_LOADED"};void 0!==b&&(d.payload=b);g.e0.dispatch(d)}return g.A(c,IYa(b),2)}b.length=0;g.sa(c)})},KYa=function(a){return void 0!==a},o5=function(a,b,c){g.Wu(new g.bs("Woffle: "+a,c?{cotn:c}:""));
b instanceof Error&&g.Wu(b)},LYa=function(a){var b,c,d,e,f,h,l,m,n,p,q,t,v,x,y,z,E;
return g.B(function(I){if(1==I.j)return g.A(I,h5(a,{mode:"readonly",Cc:!0},function(J){return $4(J,"playbackData").then(function(L){var ea=L.map(function(za){return za.transfer}).filter(function(za){return!!za}),N=L.map(function(za){return za.offlineVideoPolicy}).filter(function(za){return!!za});
ea=$4(J,"transfer",ea);N=$4(J,"offlineVideoPolicy",N);return g.ns.all([ea,N]).then(function(za){var Z=g.r(za);za=Z.next().value;Z=Z.next().value;return[L,za,Z]})})}),2);
b=I.u;c=g.r(b);d=c.next().value;e=c.next().value;f=c.next().value;h=d;l=e;m=f;n={};p={};q=g.r(l);for(t=q.next();!t.done;t=q.next())(v=t.value)&&(n[v.key]=v);x=g.r(m);for(y=x.next();!y.done;y=x.next())(z=y.value)&&(p[z.key]=z);E=h.map(function(J){var L=n[J.transfer],ea=p[J.offlineVideoPolicy];J=g.EI(ea.key).entityId;if("OFFLINE_VIDEO_POLICY_ACTION_DISABLE"===ea.action){var N="OFFLINE_VIDEO_STATE_DISABLED";ea.expirationTimestamp&&Number(ea.expirationTimestamp)<Date.now()/1E3&&(N="OFFLINE_VIDEO_STATE_EXPIRED");
ea=N}else if("OFFLINE_VIDEO_POLICY_ACTION_DOWNLOAD_FAILED"===ea.action)ea="OFFLINE_VIDEO_STATE_OFFLINE_FAILED";else{switch(null==L?void 0:L.transferState){case "TRANSFER_STATE_TRANSFER_IN_QUEUE":N="OFFLINE_VIDEO_STATE_PENDING";break;case "TRANSFER_STATE_TRANSFERRING":N="OFFLINE_VIDEO_STATE_TRANSFERRING";break;case "TRANSFER_STATE_PAUSED_BY_USER":N="OFFLINE_VIDEO_STATE_PAUSED_TRANSFER";break;case "TRANSFER_STATE_FAILED":N="OFFLINE_VIDEO_STATE_OFFLINE_FAILED";break;case "TRANSFER_STATE_COMPLETE":N=
"OFFLINE_VIDEO_STATE_PLAYABLE";break;case "TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH":N="OFFLINE_VIDEO_STATE_STREAMS_OUT_OF_DATE";break;default:N="OFFLINE_VIDEO_STATE_UNKNOWN"}if("OFFLINE_VIDEO_STATE_OFFLINE_FAILED"===N)switch(null==L?void 0:L.failureReason){case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":N="OFFLINE_VIDEO_STATE_OUT_OF_STORAGE_ERROR";break;case "TRANSFER_FAILURE_REASON_STREAM_MISSING":N="OFFLINE_VIDEO_STATE_STREAMS_MISSING";
break;case "TRANSFER_FAILURE_REASON_NETWORK":case "TRANSFER_FAILURE_REASON_NETWORK_LOST":N="OFFLINE_VIDEO_STATE_NETWORK_ERROR"}ea=N}J={id:J,videoState:ea};if(null==L?0:L.cotn)J.cotn=L.cotn;if(null==L?0:L.maximumDownloadQuality)J.selectedVideoQuality=null==L?void 0:L.maximumDownloadQuality;return J});
return I.return({offlineVideos:E})})},MYa=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,LYa(a),2);b=c.u;g.Xr("offlineStateSnapshot",b);g.sa(c)})},p5=function(a){g.G.call(this);
this.api=a;"undefined"!==typeof g.C.BroadcastChannel&&(this.j=new g.C.BroadcastChannel("PLAYER_OFFLINE_ERROR_SYNC:"+g.cs()),this.j.onmessage=this.B.bind(this),this.u=new g.C.BroadcastChannel("PLAYER_OFFLINE_PAUSE_SYNC:"+g.cs()),this.u.onmessage=this.C.bind(this))},q5=function(a,b){a.api.Ma("onOfflineOperationFailure",b);
var c;null==(c=a.j)||c.postMessage(b)},NYa=function(){this.locks=navigator.locks},OYa=function(){try{var a=g.Ka("ytglobal.locks_");
if(a)return a;var b;if(b=navigator){var c=navigator;b="locks"in c&&!!c.locks}if(b)return g.C.localStorage&&g.C.localStorage.getItem("noop"),a=new NYa,g.Ja("ytglobal.locks_",a),a}catch(d){}},QYa=function(a,b,c,d){var e=this;
this.N=a;this.V=b;this.visibility=c;this.K=d;this.C=this.I=this.D=this.u=this.j=!1;this.J=new g.K(function(){PYa(e)});
this.visibility.subscribe("visibilitystatechange",function(){e.uf()})},RYa=function(a){if(!a.u&&!a.j){var b=OYa();
if(b){a.u=!0;var c=g.cs("OfflineLockManager");b.request("woffle_orchestration_leader:"+c,{},function(){var d,e,f,h;return g.B(function(l){switch(l.j){case 1:return g.ta(l,2),a.B=new g.Yi,a.j=!0,a.u=!1,g.A(l,a.N(),4);case 4:return g.A(l,a.B.promise,5);case 5:g.ua(l,0);break;case 2:d=g.va(l),(null==(f=(e=a).K)?0:f.call(e,"wo_relinquish_leadership_on_lock_request_error"))||PYa(a),d instanceof Error&&(h=d,h.args=[{name:"WoLockManagerError",IC:d.name}],g.R(h)),g.sa(l)}})})}}},SYa=function(a){a.j&&(a.C=
!0,r5(a))},TYa=function(a,b){a.j&&(a.D=b,r5(a))},UYa=function(a,b){a.j&&(a.I=b,r5(a))},r5=function(a){a.I&&a.D&&a.C&&a.visibility.isBackground()?g.No(a.J,6E4):a.J.stop()},PYa=function(a){a.B&&a.B.resolve();
a.j=!1;a.u=!1;a.V()},s5=function(a,b){var c=b.gj;
a.encryptedVideoId=b.videoId;a.cotn=c.cotn;a.offlineabilityFormatType=c.maximumDownloadQuality;var d;a.isRefresh=null!=(d=c.isRefresh)?d:!1;var e;a.softErrorCount=null!=(e=c.transferRetryCount)?e:0;g.Xr("offlineTransferStatusChanged",a)},VYa=function(a,b,c,d){b=Math.floor(b/1024).toFixed();
s5({transferStatusType:"TRANSFER_STATUS_TYPE_PROCESSING",statusType:"OFFLINING_STARTED",transferFirstStarted:!!d,alreadyDownloadedKbytes:b,totalFetchedKbytes:b,totalContentKbytes:Math.floor(c/1024).toFixed()},a)},WYa=function(a){s5({transferStatusType:"TRANSFER_STATUS_TYPE_DEQUEUED_BY_USER_PAUSE",
statusType:"SUSPENDED"},a)},XYa=function(a){switch(a){case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":return"OFFLINE_DATABASE_ERROR";
case "TRANSFER_FAILURE_REASON_PLAYABILITY":return"NOT_PLAYABLE";case "TRANSFER_FAILURE_REASON_TOO_MANY_RETRIES":return"TOO_MANY_RETRIES";case "TRANSFER_FAILURE_REASON_INTERNAL":return"OFFLINE_DOWNLOAD_CONTROLLER_ERROR";case "TRANSFER_FAILURE_REASON_STREAM_MISSING":return"STREAM_VERIFICATION_FAILED";case "TRANSFER_FAILURE_REASON_SERVER":case "TRANSFER_FAILURE_REASON_SERVER_PROPERTY_MISSING":return"OFFLINE_REQUEST_FAILURE";case "TRANSFER_FAILURE_REASON_NETWORK":return"OFFLINE_NETWORK_ERROR";default:return"UNKNOWN_FAILURE_REASON"}},
t5=function(){},u5=function(){},v5=function(a){if(a.includes(":"))throw Error("Invalid user cache name: "+a);
return a+":"+g.cs("CacheStorage get")},YYa=function(){return g.B(function(a){if(void 0!==w5)return a.return(w5);
w5=new Promise(function(b){var c;return g.B(function(d){switch(d.j){case 1:return g.ta(d,2),g.A(d,x5.open("test-only"),4);case 4:return g.A(d,x5.delete("test-only"),5);case 5:g.ua(d,3);break;case 2:if(c=g.va(d),c instanceof Error&&"SecurityError"===c.name)return b(!1),d.return();case 3:b("caches"in window),g.sa(d)}})});
return a.return(w5)})},z5=function(){return g.B(function(a){if(1==a.j)return g.A(a,YYa(),2);
if(!a.u)return a.return(void 0);y5||(y5=new u5);return a.return(y5)})},ZYa=function(){var a;
return g.B(function(b){return 1==b.j?g.A(b,z5(),2):(a=b.u)?b.return(a.delete("yt-player-local-img")):b.return(!0)})},$Ya=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,z5(),2);if(3!=d.j){b=d.u;if(!b)throw Error("Cache API not supported");return a.length?g.A(d,b.open("yt-player-local-img"),3):d.return()}c=d.u;return g.A(d,Promise.all(a.map(function(e){return c.delete(e)})),0)})},A5=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,z5(),2);if(3!=d.j){b=d.u;if(!b)throw Error("Cache API not supported");return a.length?g.A(d,b.open("yt-player-local-img"),3):d.return()}c=d.u;return g.A(d,c.addAll(a),0)})},B5=function(a){var b,c,d;
return 0<(null!=(d=null==(b=a.actionMetadata)?void 0:null==(c=b.retryScheduleIntervalsInSeconds)?void 0:c.length)?d:0)},C5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD"===a.actionType&&!!a.entityKey},D5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"===a.actionType&&!!a.entityKey},aZa=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_DELETE"===a.actionType&&!!a.entityKey},F5=function(a,b,c,d){var e,f,h,l,m,n,p,q,t,v,x,y,z,E,I,J,L,ea,N,za,Z,Ca,Ha,ub,mc,ld,Lb,vd;
return g.B(function(wc){switch(wc.j){case 1:return e=g.FI(a,"ytMainVideoEntity"),f=g.FI(a,"mainVideoEntity"),h=g.FI(a,"ytMainChannelEntity"),l=g.FI(a,"transfer"),g.A(wc,h5(b,{mode:"readonly",Cc:!0},function(Oc){return g.ns.all([Z4(Oc,e,"ytMainVideoEntity"),Z4(Oc,f,"mainVideoEntity"),Z4(Oc,h,"ytMainChannelEntity"),Z4(Oc,l,"transfer"),$4(Oc,"ytMainChannelEntity"),$4(Oc,"offlineOrchestrationActionWrapperEntity")])}),2);
case 2:m=wc.u;n=g.r(m);p=n.next().value;q=n.next().value;t=n.next().value;v=n.next().value;x=n.next().value;y=n.next().value;z=p;E=q;I=t;J=v;L=x;ea=y;if(!(z||E||I)){wc.Ra(3);break}N=z?E5(z.thumbnail):E?E5(E.thumbnail):[];if(!I){za=[];wc.Ra(4);break}return g.A(wc,bZa(I,L),5);case 5:za=wc.u;case 4:return Z=za,g.A(wc,$Ya(N.concat(Z)),3);case 3:Ca=[];Ha=g.FI(a,"ytMainDownloadedVideoEntity");ub=g.FI(a,"mainVideoEntity");mc=g.r(ea);for(ld=mc.next();!ld.done;ld=mc.next())Lb=ld.value,vd=g.EI(Lb.key).entityId,
vd!==a||cZa(c,Lb.actionProto)||Ca.push(Lb.key);return g.A(wc,h5(b,{mode:"readwrite",Cc:!0},function(Oc){var ne=Ca.map(function(Mb){return d5(Oc,Mb)});
ne.push(d5(Oc,Ha,{zF:!0}));ne.push(d5(Oc,ub,{zF:!0}));return g.ns.all(ne)}),7);
case 7:dZa(J),q5(d,{entityKey:Ha,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"}),q5(d,{entityKey:ub,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"}),g.sa(wc)}})},fZa=function(a,b,c){var d,e,f,h,l,m;
return g.B(function(n){if(1==n.j)return g.A(n,h5(a,{mode:"readwrite",Cc:!0},function(p){var q=$4(p,"transfer"),t=$4(p,"offlineOrchestrationActionWrapperEntity");return g.ns.all([q,t]).then(function(v){v=g.r(v);var x=v.next().value,y=v.next().value;v=eZa.map(function(J){return yYa(p,J)});
y=g.r(y);for(var z=y.next();!z.done;z=y.next()){z=z.value;var E="ytMainDownloadedVideoEntity"===g.EI(z.actionProto.entityKey).entityType,I="OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD"===z.actionProto.actionType;cZa(b,z.actionProto)||E&&(!E||I)||v.push(d5(p,z.key,{zF:!0}))}return g.ns.all(v).then(function(){return x})})}),2);
d=n.u;e=g.r(d);for(f=e.next();!f.done;f=e.next())h=f.value,dZa(h),l=g.EI(h.key).entityId,m=g.FI(l,"ytMainDownloadedVideoEntity"),q5(c,{entityKey:m,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"});return g.A(n,ZYa(),0)})},cZa=function(a,b){return a.actionType===b.actionType&&a.entityKey===b.entityKey},dZa=function(a){if(a&&"TRANSFER_STATE_COMPLETE"!==a.transferState&&"TRANSFER_STATE_FAILED"!==a.transferState){var b=g.EI(a.key).entityId;
s5({transferStatusType:"TRANSFER_STATUS_TYPE_TERMINATED_BY_USER",statusType:"CANCELLED"},{videoId:b,gj:a})}},E5=function(a){if(!a||!a.thumbnails)return[];
var b=[];a=g.r(a.thumbnails);for(var c=a.next();!c.done;c=a.next())c=c.value,c.url&&b.push(c.url);return b},bZa=function(a,b){var c,d,e,f,h,l,m,n;
return g.B(function(p){c=E5(a.avatar);d=g.r(b);for(e=d.next();!e.done;e=d.next())if(f=e.value,f.id!==a.id)for(h=g.r(E5(f.avatar)),l=h.next();!l.done;l=h.next())m=l.value,n=c.indexOf(m),-1!==n&&c.splice(n,1);return p.return(c)})},G5=function(a){this.j=a},gZa=function(a,b){var c,d,e,f,h,l,m;
return g.B(function(n){switch(n.j){case 1:c=new Map,d=g.r(b),e=d.next();case 2:if(e.done){n.Ra(4);break}f=e.value;h=c;l=h.set;m=f;return g.A(n,a.u(f),5);case 5:l.call(h,m,n.u);e=d.next();n.Ra(2);break;case 4:return n.return(c)}})},H5=function(a,b,c,d){this.status=a;
this.j=b;this.u=c;this.failureReason=d},I5=function(a,b,c){this.j=a;
this.U=b;this.B=c},jZa=function(a,b){var c,d,e,f,h,l,m;
return g.B(function(n){switch(n.j){case 1:c=b.entityKey;f=null==(d=b.actionMetadata)?void 0:null==(e=d.playbackDataActionMetadata)?void 0:e.isEnqueuedForExpiredStreamUrlRefetch;g.ta(n,2);var p;var q=null!=(p=b.actionMetadata)&&p.playbackDataActionMetadata?{maximumDownloadQuality:b.actionMetadata.playbackDataActionMetadata.maximumDownloadQuality}:void 0;return g.A(n,hZa(a,c,{isEnqueuedForExpiredStreamUrlRefetch:f,aS:q}),4);case 4:return(h=n.u)?g.A(n,iZa(a,h,b),5):n.return(J5(b,!1,void 0,"OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED"));
case 5:return n.return(J5(b,!0,h.orchestrationActions));case 2:return l=g.va(n),m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",l instanceof g.gs&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),o5("PDE handleAdd error"),n.return(J5(b,!1,void 0,m))}})},kZa=function(a,b){var c,d,e,f,h,l,m,n,p,q,t,v,x,y,z;
return g.B(function(E){switch(E.j){case 1:return c=b.entityKey,g.A(E,h5(a.j,{mode:"readonly",Cc:!0},function(I){var J=Z4(I,c,"playbackData"),L=Z4(I,g.FI(g.EI(b.entityKey).entityId,"offlineVideoPolicy"),"offlineVideoPolicy");I=Z4(I,g.FI(g.EI(b.entityKey).entityId,"transfer"),"transfer");return g.ns.all([J,L,I])}),2);
case 2:d=E.u;e=g.r(d);f=e.next().value;h=e.next().value;l=e.next().value;m=f;n=h;p=l;if(!m||!n)return E.return(J5(b,!0));q={lastPlayerResponseTimestampSeconds:m.playerResponseTimestamp,offlineToken:n.offlineToken};t={};if(null==(v=p)?0:v.maximumDownloadQuality)t.maximumDownloadQuality=p.maximumDownloadQuality;g.ta(E,3);return g.A(E,hZa(a,c,{refreshData:q,aS:t}),5);case 5:return(x=E.u)?g.A(E,iZa(a,x,b),6):E.return(J5(b,!1,void 0,"OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED"));case 6:return E.return(J5(b,
!0,x.orchestrationActions));case 3:return y=g.va(E),z="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",y instanceof g.gs&&"QUOTA_EXCEEDED"===y.type&&(z="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),E.return(J5(b,!1,void 0,z))}})},hZa=function(a,b,c){var d,e,f;
return g.B(function(h){d=g.ZH();var l=a.U,m=c.refreshData,n=c.isEnqueuedForExpiredStreamUrlRefetch,p=c.aS,q={entityKey:b};m&&(q.refreshData=m);n&&(q.isExpiredStreamUrlRefetch=n);p&&(q.downloadParameters=p);e={context:g.kI(l),signatureTimestamp:19124,videos:[q]};f=g.KH(lZa);return h.return(g.VF(d,e,f))})},iZa=function(a,b,c){var d;
return g.B(function(e){if(1==e.j){if(!b.frameworkUpdates||!b.frameworkUpdates.entityBatchUpdate)return e.return();if(!(b.frameworkUpdates.entityBatchUpdate.mutations&&0<b.frameworkUpdates.entityBatchUpdate.mutations.length&&"ENTITY_MUTATION_TYPE_DELETE"===b.frameworkUpdates.entityBatchUpdate.mutations[0].type))return e.Ra(2);d=g.EI(b.frameworkUpdates.entityBatchUpdate.mutations[0].entityKey).entityId;return g.A(e,F5(d,a.j,c,a.B),2)}return g.A(e,JYa(b.frameworkUpdates.entityBatchUpdate),0)})},J5=function(a,
b,c,d){return new H5(b?"OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS":"OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",B5(a),c,d)},K5=function(){G5.apply(this,arguments)},nZa=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=B5(b),g.A(e,k5(a.j,b.entityKey,"transfer"),2);case 2:if(d=e.u)return e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.ta(e,3);return g.A(e,mZa(a,b),5);case 5:g.ua(e,4);break;case 3:return g.va(e),e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},oZa=function(a,b){var c,
d;
return g.B(function(e){switch(e.j){case 1:return c=B5(b),g.A(e,k5(a.j,b.entityKey,"transfer"),2);case 2:d=e.u;if(!d||"TRANSFER_STATE_COMPLETE"!==d.transferState)return e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.ta(e,3);return g.A(e,mZa(a,b,!0),5);case 5:g.ua(e,4);break;case 3:return g.va(e),e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",
c))}})},mZa=function(a,b,c){c=void 0===c?!1:c;
var d,e,f,h,l,m;return g.B(function(n){if(1==n.j)return e=null==(d=b.actionMetadata)?void 0:d.transferEntityActionMetadata,l={key:b.entityKey,transferState:"TRANSFER_STATE_TRANSFER_IN_QUEUE",cotn:g.bv(16),enqueuedTimestampMs:Date.now().toString(),maximumDownloadQuality:null==(f=e)?void 0:f.maximumDownloadQuality,preferredAudioTrack:null==(h=e)?void 0:h.preferredAudioTrack,transferRetryCount:0,isRefresh:c,hasLoggedFirstStarted:!1},m=g.EI(l.key).entityId,g.A(n,h5(a.j,{mode:"readwrite",Cc:!0},function(p){var q=
[];c&&q.push(d5(p,g.FI(m,"offlineVideoStreams")));q.push(b5(p,l,"transfer"));return g.ns.all(q)}),2);
s5({transferStatusType:"TRANSFER_STATUS_TYPE_ENQUEUED",statusType:"ADDED_TO_QUEUE"},{videoId:m,gj:l});g.sa(n)})},pZa=function(a,b,c){return new g.kD(a,{cotn:b,
raw_player_response:c,download_media:!0,start:Infinity,disable_watch_next:!0})},qZa=function(){return{priority:1,
retryScheduleIntervalsInSeconds:[1,2,4]}},L5=function(a,b,c,d,e,f,h,l,m,n,p){this.entityType=a;
this.actionId=b;this.action=c;this.parentActionId=d;this.rootActionId=void 0===e?b:e;this.childActionIds=f;this.prereqActionId=h;this.postreqActionIds=l;this.hasChildActionFailed=n;this.retryScheduleIndex=0;this.j=p||Date.now();this.retryScheduleIndex=m||0},M5=function(a){return{key:g.FI(a.actionId,"offlineOrchestrationActionWrapperEntity"),
actionProto:a.action,parentActionId:a.parentActionId,rootActionId:a.rootActionId,childActionIds:a.childActionIds,prereqActionId:a.prereqActionId,postreqActionIds:a.postreqActionIds,retryScheduleIndex:a.retryScheduleIndex,hasChildActionFailed:a.hasChildActionFailed,enqueueTimeSec:(a.j/1E3).toFixed()}},rZa=function(){this.j=new Map},sZa=function(){N5||(N5=new rZa);
return N5},tZa=function(a,b){return{eventType:{flowEventNamespace:"FLOW_EVENT_NAMESPACE_OFFLINE_ORCHESTRATION",
flowEventType:a},metadata:b,statusCode:void 0,csn:void 0,can:void 0}},uZa=function(a,b,c){if(!c){var d=void 0===d?!1:d;
c=a.j.get("FLOW_TYPE_OFFLINE_ORCHESTRATION");if(!c||d)c=g.bv(16),a.j.set("FLOW_TYPE_OFFLINE_ORCHESTRATION",c)}a={flowNonce:c,flowType:"FLOW_TYPE_OFFLINE_ORCHESTRATION",flowEventType:b.eventType};b.metadata&&(a.flowMetadata=b.metadata);void 0!==b.statusCode&&(a.flowEventStatus=b.statusCode);b.csn&&(a.csn=b.csn);b.can&&(a.can=b.can);g.Xr("flowEvent",a,void 0)},vZa=function(a,b,c){if(!a.action.entityKey)throw Error("entityKey is missing.");
var d=g.EI(a.action.entityKey);a={entityType:d.eW,entityId:d.entityId,offlineOrchestrationActionType:a.action.actionType,orchestrationAction:{orchestrationActionId:a.actionId}};b&&(a.offlineOrchestrationActionResult=b.status,a.isRetryable=b.j);c&&(a.additionalOrchestrationActions=c.map(function(e){return{orchestrationActionId:e.actionId}}));
return a},O5=function(a,b){var c={offlineOrchestrationContext:vZa(a)};
b=tZa(b,c);uZa(sZa(),b,a.rootActionId)},P5=function(a,b,c){c=void 0===c?[]:c;
b={offlineOrchestrationContext:vZa(a,b,c)};b=tZa(3,b);uZa(sZa(),b,a.rootActionId)},wZa=function(){this.actions=[]},xZa=function(a,b){b=g.r(b);
for(var c=b.next();!c.done;c=b.next())c=c.value,O5(c,1),a.actions.push(c);a.actions.sort(a.j)},yZa=function(a,b){a=g.r(a.actions);
for(var c=a.next();!c.done;c=a.next())if(c.value.actionId===b)return!0;return!1},Q5=function(a,b,c,d){g.G.call(this);
var e=this;this.u=a;this.Y=b;this.V=c;this.D=d;this.j=new wZa;this.N=new g.nt;this.C=new g.K(function(){e.retry()});
this.I=NaN;g.H(this,this.C);this.J=i5(this.u,this.W.bind(this))},AZa=function(a,b,c,d){var e;
return g.B(function(f){if(1==f.j)return e=new Q5(a,b,c,d),g.A(f,zZa(e),2);e.B?Promise.resolve():R5(e);return f.return(e)})},R5=function(a){var b,c,d,e,f,h,l,m,n,p,q,t,v,x,y;
return g.B(function(z){switch(z.j){case 1:if(a.B)throw Error("Already processing an action");if(a.isDisposed())return z.return();b=a.j.actions.shift();TYa(a.V,!b);if(void 0===b)return z.return();for(c=[b];;)if((d=a.j.actions[0])&&0===d.retryScheduleIndex&&d.entityType===b.entityType)c.push(a.j.actions.shift());else break;a.B=c;if(e=a.Y[b.entityType]){z.Ra(2);break}a.B=void 0;return g.A(z,R5(a),3);case 3:return z.return();case 2:f=g.r(c);for(h=f.next();!h.done;h=f.next())l=h.value,O5(l,2);g.ta(z,4,
5);return g.A(z,gZa(e,c.map(function(E){return E.action})),7);
case 7:m=z.u,n=g.r(c),h=n.next();case 8:if(h.done){z.Ra(5);break}p=h.value;q=m.get(p.action);return g.A(z,BZa(a,p,q),9);case 9:h=n.next();z.Ra(8);break;case 5:g.wa(z);a.B=void 0;g.xa(z,6);break;case 4:return t=g.va(z),o5("Orchestration error",t),g.ta(z,12),g.A(z,CZa(a,c),14);case 14:g.ua(z,5);break;case 12:v=g.va(z);o5("Orchestration retry error",v);x=g.r(c);for(h=x.next();!h.done;h=x.next())y=h.value,3>y.retryScheduleIndex&&xZa(a.j,[y]);z.Ra(5);break;case 6:return g.A(z,R5(a),0)}})},BZa=function(a,
b,c){var d,e,f,h,l,m;
return g.B(function(n){if(1==n.j){if("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS"===c.status){h=void 0;try{h=null==(l=c.u)?void 0:l.map(function(p){return a.createAction(p,b)})}catch(p){return P5(b,c),m={entityKey:b.action.entityKey,
failureReason:"OFFLINE_OPERATION_FAILURE_REASON_UNSUPPORTED_ENTITY_FAILED"},q5(a.D,m),o5("Orchestration subactions creation error",p),n.return()}P5(b,c,h);return g.A(n,h5(a.u,{mode:"readwrite",Cc:!0},function(p){var q=[];if(h){var t=h.map(function(v){return M5(v)});
q.push(c5(p,t,"offlineOrchestrationActionWrapperEntity"))}t=M5(b);q.push(d5(p,t.key));return g.ns.all(q)}),9)}if("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE"!==c.status)return n.Ra(0);
P5(b,c);if(c.j&&3>b.retryScheduleIndex+1)return g.A(n,CZa(a,[b]),0);e=(null==(d=c)?0:d.failureReason)?c.failureReason:"OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN";f={entityKey:b.action.entityKey,failureReason:e};q5(a.D,f);o5("Orchestration result is not retryable, deleting action");return g.A(n,FYa(a.u,M5(b).key),0)}O5(b,4);g.sa(n)})},S5=function(a,b){var c,d,e,f,h,l,m,n,p,q,t,v;
return g.B(function(x){c=[];d=Infinity;e=4E3;f=g.r(b);for(h=f.next();!h.done;h=f.next())l=h.value,m=Number(l.enqueueTimeSec),n=DZa(m),p=l.retryScheduleIndex,q=null!=p&&0<p,0<n&&q?(d=Math.min(d,m),e=Math.min(n,e)):c.push(l);isFinite(d)&&(!a.C.isActive()||d<a.I)&&(a.I=d,a.C.start(e));a.N.tf()||(t=c.length,c=c.filter(function(y){var z;y=(null==(z=y.actionProto)?void 0:z.actionType)||"OFFLINE_ORCHESTRATION_ACTION_TYPE_UNKNOWN";return!EZa.includes(y)}),v=c.length<t,!a.C.isActive()&&v&&a.C.start(1));
0<c.length&&FZa(a,c);return g.A(x,a.B?Promise.resolve():R5(a),0)})},HZa=function(a){var b,c,d,e,f,h,l;
return g.B(function(m){if(1==m.j)return g.A(m,GZa(a),2);b=m.u;c=[];d=g.r(b);for(e=d.next();!e.done;e=d.next())f=e.value,h=g.EI(f.key),l=h.entityId,yZa(a.j,l)||c.push(f);return g.A(m,S5(a,c),0)})},DZa=function(a){a=1E3*a-Date.now();
return 4E3<a?4E3:a},CZa=function(a,b){var c,d,e;
return g.B(function(f){c=g.r(b);for(d=c.next();!d.done;d=c.next()){e=d.value;var h=void 0,l=void 0,m=(null==(l=e.action)?void 0:null==(h=l.actionMetadata)?void 0:h.retryScheduleIntervalsInSeconds)||[1,2,4];h=1;e.retryScheduleIndex<m.length&&(h=m[e.retryScheduleIndex]);e.j=1E3*h+Date.now();e.retryScheduleIndex++}return g.A(f,IZa(a,b),0)})},zZa=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,l5(a.u,"offlineOrchestrationActionWrapperEntity"),2);b=c.u;return g.A(c,S5(a,b),0)})},FZa=function(a,b){0!==b.length&&b.forEach(function(c){if(!c.key)throw Error("Entity key is required.");
if(!c.actionProto)throw Error("OfflineOrchestrationAction is required.");var d=g.EI(c.key),e=g.EI(c.actionProto.entityKey);c=new L5(e.entityType,d.entityId,c.actionProto,c.parentActionId,c.rootActionId,c.childActionIds,c.prereqActionId,c.postreqActionIds,c.retryScheduleIndex,c.hasChildActionFailed,1E3*Number(c.enqueueTimeSec));3>c.retryScheduleIndex&&xZa(a.j,[c])})},GZa=function(a,b){var c;
return g.B(function(d){if(1==d.j)return g.A(d,l5(a.u,"offlineOrchestrationActionWrapperEntity",b),2);c=d.u;return d.return(c.filter(KYa))})},IZa=function(a,b){if(0===b.length)return Promise.resolve([]);
b=b.map(function(c){return M5(c)});
return EYa(a.u,b)},JZa=function(){this.j=void 0},LZa=function(a,b){var c,d,e,f,h;
return g.B(function(l){c=b.videoId;d=b.S();e=!0;if(b.captionTracks.length)f=cYa(b),a.j=new g.pJ(d,b,f);else if(b.Jc)h=g.bxa(b),a.j=new g.rJ(d,b.Jc,c,h,b.wl),e=b.wl;else return l.return();return l.return(new Promise(function(m){var n;null==(n=a.j)||n.Vu(function(){return g.B(function(p){if(1==p.j)return g.A(p,KZa(a,c,e),2);m();g.sa(p)})})}))})},KZa=function(a,b,c){c=void 0===c?!0:c;
var d,e,f,h,l,m,n,p,q,t,v,x,y,z;return g.B(function(E){switch(E.j){case 1:if(!a.j)return E.return();d=[];e=g.mJ(a.j.u,c);f=[];h={};l=g.r(e.entries());for(m=l.next();!m.done;h={ND:h.ND},m=l.next())n=m.value,p=g.r(n),q=p.next().value,t=p.next().value,h.ND=q,v=t,x=a.j.Br(v,"json3"),y=g.Rq(x,{withCredentials:!0,format:"RAW"},3,500).then(function(I){return function(J){J={metadata:g.WC(e[I.ND]),trackData:J.xhr.responseText};f.push(J)}}(h)).Hi(function(I){o5("Caption fetch error",I)}),d.push(y);
return g.A(E,dYa(d),2);case 2:return g.ta(E,3),g.A(E,hYa(b,f),5);case 5:g.ua(E,0);break;case 3:z=g.va(E),o5("Caption DB transaction error",z),g.sa(E)}})},MZa=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,iYa(a),2);b=c.u;return c.return(!!b&&0<b.length)})},NZa=function(a,b){this.api=a;
this.j=b;this.logger=new g.EO("woffle");this.u=!1},OZa=function(a){return g.B(function(b){return b.return(jYa(a))})},PZa=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,g.Nva(a),2);b=c.u;return c.return(b.filter(function(d){return!!d.url}).map(function(d){return d.url}))})},T5=function(a,b){var c=g.PC(b);
if(1===c||0===c)return Promise.resolve();(c=QZa(a,b))&&c.stopVideo();a.B=0;return OZa(b)},U5=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?!0:d;var e="string"===typeof b?b:b.videoDetails.videoId;2===g.PC(e)&&((b=QZa(a,e))?b.stopVideo():a.logger.info(function(){return"Corresponding player for "+e+" not found. Pausing anyway"}),g.QC(e,2),a.B=2,c?RZa(a.j):d&&SZa(a.j))},QZa=function(a,b){var c;
return(null==(c=a.player)?void 0:c.getVideoData().videoId)===b?a.player:null},TZa=function(a){switch(a){case "HD_1080":return"hd1080";
case "HD":return"hd720";case "SD":return"large";case "LD":return"tiny";default:return"hd720"}},V5=function(a){g.G.call(this);
this.j=a;this.u=i5(this.j,this.B.bind(this))},UZa=function(a,b){var c,d,e,f,h,l,m;
return g.B(function(n){switch(n.j){case 1:if(0===b.length)return n.return([]);c=b.map(function(p){return g.FI(p,"transfer")});
return g.A(n,l5(a.j,"transfer",c),2);case 2:d=n.u;e=d.filter(KYa).map(function(p){return g.EI(p.key).entityId});
f=b.filter(function(p){return-1===e.indexOf(p)});
if(0===f.length)return n.return([]);h=g.r(f);l=h.next();case 3:if(l.done){n.Ra(5);break}m=l.value;return g.A(n,OZa(m),4);case 4:l=h.next();n.Ra(3);break;case 5:return n.return(f)}})},WZa=function(a,b,c,d,e,f){var h,l,m;
return g.B(function(n){h="STREAM_TYPE_UNKNOWN";c.video&&c.audio?(h="STREAM_TYPE_AUDIO_AND_VIDEO",o5("unexpected stream type")):c.video&&!c.audio?h="STREAM_TYPE_VIDEO":!c.video&&c.audio&&(h="STREAM_TYPE_AUDIO");l=g.FI(b,"offlineVideoStreams");m={numBytesDownloaded:e.toFixed(),numTotalBytes:f.toFixed(),streamType:h,streamState:"DOWNLOAD_STREAM_STATE_IN_PROGRESS",formatStreamBytes:JSON.stringify(d),itag:"STREAM_TYPE_AUDIO_AND_VIDEO"===h?Number(c.Vb()):void 0};return g.A(n,h5(a,{mode:"readwrite",Cc:!0},
function(p){var q=Z4(p,l,"offlineVideoStreams"),t=Z4(p,g.FI(b,"transfer"),"transfer");return g.ns.all([q,t]).then(function(v){var x=g.r(v);v=x.next().value;x=x.next().value;if(!x)return d5(p,l).then(function(){});
v=[b5(p,VZa(v,d,m,l),"offlineVideoStreams")];x.offlineVideoStreams||(x.offlineVideoStreams=[]);-1===x.offlineVideoStreams.indexOf(l)&&(x.offlineVideoStreams.push(l),v.push(b5(p,x,"transfer")));return g.ns.all(v)})}),0)})},XZa=function(a,b){var c,d,e,f,h;
return g.B(function(l){if(1==l.j)return c=g.FI(b,"offlineVideoStreams"),g.A(l,k5(a,c,"offlineVideoStreams"),2);d=l.u;if(!d||!d.streamsProgress)return l.return();e=g.r(d.streamsProgress);for(f=e.next();!f.done;f=e.next())h=f.value,h.streamState="DOWNLOAD_STREAM_STATE_COMPLETE",h.numTotalBytes!==h.numBytesDownloaded&&(h.numBytesDownloaded=h.numTotalBytes);return g.A(l,j5(a,d,"offlineVideoStreams"),0)})},VZa=function(a,b,c,d){if(a&&a.streamsProgress){d=a;
a:{b=b.itag+";"+b.xtags;for(var e=a.streamsProgress,f=0;f<e.length;f++){var h=JSON.parse(e[f].formatStreamBytes);if(h.itag+";"+h.xtags===b){e[f]=c;c=e;break a}}e.push(c);c=e}d.streamsProgress=c}else a={key:d,streamsProgress:[c]};return a},W5=function(a,b,c,d){g.G.call(this);
var e=this;this.u=a;this.api=b;this.va=c;this.ma=d;this.D=new g.nt;this.C=new g.K(function(){e.j&&"TRANSFER_STATE_TRANSFERRING"===e.j.transferState&&e.D.tf()&&(3>(e.j.transferRetryCount||0)?U5(e.I,e.B,!1,!1):T5(e.I,e.B.videoDetails.videoId),e.ls("TRANSFER_FAILURE_REASON_TIMEOUT_NO_PROGRESS"))});
this.V=0;this.oa=new g.Dz(this);this.J=i5(this.u,this.HU.bind(this));this.I=new NZa(b,this);this.Fa=new JZa;this.N=new V5(this.u);this.Y=this.D.La("publicytnetworkstatus-online",this.xz.bind(this));this.W=this.D.La("publicytnetworkstatus-offline",this.W_.bind(this));g.H(this,this.oa);this.oa.P(b,"offlinetransferpause",this.X_);this.Da=g.yA(this.api.S().experiments,"web_player_transfer_timeout_threshold_ms")},YZa=function(a){return g.B(function(b){if(1==b.j)b=g.A(b,gYa(),2);
else{var c=a.N;var d=g.OC();d=Object.keys(d);c=UZa(c,d);b=g.A(b,c,0)}return b})},Y5=function(a,b){b=void 0===b?!1:b;
var c;return g.B(function(d){if(1==d.j){if(a.j)throw Error("Already downloading a video");return g.A(d,ZZa(a),2)}return 4!=d.j?(c=d.u,UYa(a.va,!c),c&&a.D.tf()?b?g.A(d,new Promise(function(e){g.Jq(e,1E3)}),4):d.Ra(4):(!c&&a.j&&X5(a),d.Ra(0))):g.A(d,$Za(a,c),0)})},a_a=function(a){return g.B(function(b){if(1==b.j)return a.B?g.A(b,T5(a.I,a.B.videoDetails.videoId),3):b.Ra(0);
X5(a);g.sa(b)})},b_a=function(a,b){var c,d,e;
return g.B(function(f){switch(f.j){case 1:return g.ta(f,2),(c=!!b.captionTracks.length||!!b.Jc)?g.A(f,MZa(b.videoId),4):f.return();case 4:return(d=f.u)?f.return():g.A(f,LZa(a.Fa,b),5);case 5:g.ua(f,0);break;case 2:e=g.va(f),o5("Caption downloading error",e,b.cotn),g.sa(f)}})},$Za=function(a,b){var c,d,e,f,h;
return g.B(function(l){switch(l.j){case 1:return a.j=b,c=g.EI(a.j.key),"TRANSFER_STATE_TRANSFERRING"===a.j.transferState&&s5({transferStatusType:"TRANSFER_STATUS_TYPE_RESUME_PROCESSING",statusType:"OFFLINING_RETRIED"},{videoId:c.entityId,gj:a.j}),g.A(l,Z5(a),2);case 2:return d=null,g.ta(l,3),g.A(l,c_a(a,b),5);case 5:d=l.u;a.B=d;g.ua(l,4);break;case 3:return e=g.va(l),o5("error getting player response",e,b.cotn),g.A(l,a.ls("TRANSFER_FAILURE_REASON_INTERNAL"),6);case 6:return l.return();case 4:return f=
pZa(a.api.S(),b.cotn,d),g.A(l,b_a(a,f),7);case 7:return h=f,g.A(l,PZa(f.videoId),8);case 8:h.Tm=l.u;var m=a.I,n=b.maximumDownloadQuality;f.getPlayerResponse();g.QC(f.videoId,2);m.B=2;m.u=!1;var p;null==(p=m.player)||p.dispose();m.player=m.api.Vo(9,f);p={};g.Fu(m.player,(p.localmediachange=m.AC,p.signatureexpired=m.gI,p.statechange=m.PY,p),m);n=TZa(n);m.K("hoffle_lmqf_killswitch")||g.oMa(m.player,g.ex(n,n,!0,"m"),!1);g.UN(m.player,!1);$5(a);g.sa(l)}})},ZZa=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,l5(a.u,"transfer"),2);b=d.u;c=b.filter(d_a).sort(e_a);return 0===c.length?d.return():d.return(c[0])})},Z5=function(a){return g.B(function(b){$5(a);
return g.A(b,a6(a,"TRANSFER_STATE_TRANSFERRING"),0)})},RZa=function(a){var b;
g.B(function(c){if(1==c.j)return a.C.stop(),g.A(c,a6(a,"TRANSFER_STATE_PAUSED_BY_USER"),2);b=g.EI(a.j.key);WYa({videoId:b.entityId,gj:a.j});X5(a);Y5(a);g.sa(c)})},SZa=function(a){g.B(function(b){if(1==b.j)return a.C.stop(),g.A(b,a6(a,"TRANSFER_STATE_TRANSFER_IN_QUEUE"),2);
X5(a);g.sa(b)})},f_a=function(a){var b,c,d;
g.B(function(e){switch(e.j){case 1:a.C.stop();if(!a.j||!a.B){e.Ra(2);break}b=pZa(a.api.S(),a.j.cotn,a.B);return g.A(e,b_a(a,b),2);case 2:return g.A(e,a6(a,"TRANSFER_STATE_COMPLETE","DOWNLOAD_STREAM_STATE_COMPLETE"),4);case 4:return c=g.EI(a.j.key),d=c.entityId,g.A(e,XZa(a.u,d),5);case 5:s5({transferStatusType:"TRANSFER_STATUS_TYPE_COMPLETED",statusType:"SUCCESS"},{videoId:d,gj:a.j}),X5(a),Y5(a),g.sa(e)}})},h_a=function(a,b,c){var d;
g.B(function(e){switch(e.j){case 1:if("TRANSFER_STATE_TRANSFERRING"===a.j.transferState){e.Ra(2);break}return g.A(e,Z5(a),2);case 2:d=Date.now();if(!(1E3<d-a.V)){e.Ra(4);break}a.V=d;return g.A(e,WZa(a.u,c.videoId,c.u,c.formatStream,c.bytesDownloaded,c.j),5);case 5:if(a.j.hasLoggedFirstStarted){VYa({videoId:b,gj:a.j},c.bytesDownloaded,c.j);e.Ra(4);break}a.j.hasLoggedFirstStarted=!0;return g.A(e,g_a(a),7);case 7:VYa({videoId:b,gj:a.j},c.bytesDownloaded,c.j,!0);case 4:$5(a),g.sa(e)}})},i_a=function(a){var b=
3>(a.j.transferRetryCount||0);
b&&(a=a.j,a.transferRetryCount=(a.transferRetryCount||0)+1);return b},j_a=function(a,b){b=void 0===b?"TRANSFER_FAILURE_REASON_UNKNOWN":b;
var c,d;return g.B(function(e){if(1==e.j)return c="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN","TRANSFER_FAILURE_REASON_NETWORK"===b?c="OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED":"TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE"===b&&(c="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),g.A(e,a6(a,"TRANSFER_STATE_FAILED","DOWNLOAD_STREAM_STATE_ERROR_STREAMS_MISSING",b),2);q5(a.ma,{entityKey:a.j.key,failureReason:c});d=g.EI(a.j.key).entityId;var f={videoId:d,gj:a.j},h=b,l={transferStatusType:"TRANSFER_STATUS_TYPE_TERMINATED_WITH_FAILURE",
statusType:"FAILED"};h&&(l.transferFailureReason=h,l.failureReason=XYa(h));s5(l,f);g.sa(e)})},a6=function(a,b,c,d){var e;
return g.B(function(f){if(1==f.j)return a.j.transferState=b,a.j.failureReason=d,g.ta(f,2),g.A(f,g_a(a,function(h){return c?$4(h,"offlineVideoStreams",a.j.offlineVideoStreams).then(function(l){for(var m=g.r(l),n=m.next();!n.done;n=m.next())if((n=n.value)&&n.streamsProgress){n=g.r(n.streamsProgress);for(var p=n.next();!p.done;p=n.next())p.value.streamState=c}return c5(h,l.filter(function(q){return!!q}),"offlineVideoStreams")}):g.ns.resolve(void 0)}),4);
if(2!=f.j)return g.ua(f,0);e=g.va(f);return e instanceof g.gs&&"QUOTA_EXCEEDED"===e.type?g.A(f,a.ls("TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE"),0):f.Ra(0)})},g_a=function(a,b){var c;
return g.B(function(d){if(!a.j)return d.return();c=a.j;return g.A(d,h5(a.u,{mode:"readwrite",Cc:!0},function(e){var f=[b5(e,c,"transfer")];b&&f.push(b(e));return g.ns.all(f)}),0)})},X5=function(a){a.j=void 0;
a.B=void 0;a.C.stop()},c_a=function(a,b){var c,d,e,f,h;
return g.B(function(l){if(1==l.j)return c=g.EI(b.key),d=c.entityId,e=g.FI(d,"playbackData"),g.A(l,k5(a.u,e,"playbackData"),2);f=l.u;if(null==(h=f)?0:h.playerResponseJson)return l.return(JSON.parse(f.playerResponseJson));throw Error("No PlayerResponse found");})},$5=function(a){a.C.start(a.Da||18E5)},d_a=function(a){return void 0!==b6[a.transferState]},e_a=function(a,b){var c=b6[a.transferState],d=b6[b.transferState];
return c!==d?c-d:Number(a.enqueuedTimestampMs)-Number(b.enqueuedTimestampMs)},c6=function(a,b){var c=this;
this.U=a;this.api=b;this.N=new g.nt;this.B=new QYa(function(){return k_a(c)},function(){l_a(c)},this.api.zp(),this.api.K.bind(this.api));
this.u=new p5(this.api);this.C=new g.Yi;RYa(this.B)},k_a=function(a){return g.B(function(b){a.api.Ma("onOrchestrationBecameLeader");
a.j&&a.D||m_a(a).then(a.C.resolve).catch(a.C.reject);var c=a.C.promise;return g.A(b,c,0)})},m_a=function(a){var b,c,d;
return g.B(function(e){if(1==e.j)return g.A(e,n5(),2);if(3!=e.j){b=e.u;if(!b)return o5("PES is undefined"),e.return();a.j=new W5(b,a.api,a.B,a.u);c=a.Px(b);d=a;return g.A(e,AZa(b,c,a.B,a.u),3)}d.D=e.u;return g.A(e,n_a(a),0)})},n_a=function(a){var b;
return g.B(function(c){switch(c.j){case 1:if(!a.j)return o5("transferManager is undefined"),c.return();if(a.j.j){c.Ra(2);break}return g.A(c,Y5(a.j),2);case 2:return g.A(c,a.rz(),4);case 4:return a.J=g.Kq(function(){a.rz()},9E5),g.Nr(g.Pr(),function(){return a.YI()}),g.A(c,n5(),5);
case 5:return b=c.u,g.A(c,MYa(b),6);case 6:SYa(a.B),g.sa(c)}})},l_a=function(a){var b,c;
g.B(function(d){if(1==d.j)return a.j||a.D?g.A(d,a.C.promise,2):d.return();void 0!==a.J&&(window.clearInterval(a.J),a.J=void 0);null==(b=a.j)||b.dispose();a.j=void 0;null==(c=a.D)||c.dispose();a.D=void 0;a.api.Ma("onOrchestrationLostLeader");a.C=new g.Yi;g.sa(d)})},o_a=function(){var a,b,c,d,e,f;
return g.B(function(h){switch(h.j){case 1:return g.A(h,n5(),2);case 2:a=h.u;if(!a)return h.return([]);b=Date.now()/1E3;return g.A(h,l5(a,"offlineVideoPolicy"),3);case 3:c=h.u,d=g.r(c),e=d.next();case 4:if(e.done){h.Ra(6);break}f=e.value;if(!(f.expirationTimestamp&&Number(f.expirationTimestamp)<b)){h.Ra(5);break}f.action="OFFLINE_VIDEO_POLICY_ACTION_DISABLE";return g.A(h,j5(a,f,"offlineVideoPolicy"),5);case 5:e=d.next();h.Ra(4);break;case 6:return h.return(c.map(function(l){return l.key}))}})},d6=
function(a,b,c,d,e){var f,h,l;
return g.B(function(m){if(1==m.j)return g.A(m,n5(),2);f=m.u;if(!f)return m.return([]);h=b.map(function(n){var p=g.FI(n,c);p={actionType:d,entityKey:p,actionMetadata:Object.assign({},qZa(),e)};"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"!==d&&(p.actionMetadata.priority=0);n=new L5(c,n,p);return M5(n)});
l=EYa(f,h);RYa(a.B);return m.return(l)})},e6=function(a){var b,c,d,e,f;
return g.B(function(h){switch(h.j){case 1:return b=g.ZH(),c=kYa(a),d=g.KH(p_a),g.ta(h,2),g.A(h,g.VF(b,c,d),4);case 4:e=h.u;g.ua(h,3);break;case 2:throw f=g.va(h),o5("GetOffline fetch request error",f),Error("GetOffline fetch request error");case 3:if(!e)throw Error("Network request failed");if(!e.videos||!e.videos.length)throw Error("No data");return h.return(e.videos.map(function(l){return l.offlineVideoData}))}})},f6=function(a,b,c){this.j=a;
this.U=b;this.B=c},s_a=function(a,b){var c,d,e,f,h,l,m,n;
return g.B(function(p){switch(p.j){case 1:return c=B5(b),d=g.EI(b.entityKey),e=d.entityId,g.ta(p,2),g.A(p,q_a(a,e,void 0,null==(f=b.actionMetadata)?void 0:null==(h=f.mainVideoEntityActionMetadata)?void 0:h.offlineVideoData),4);case 4:g.ua(p,3);break;case 2:return l=g.va(p),m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",l instanceof g.gs&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),p.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,m));
case 3:var q;var t=null!=(q=b.actionMetadata)&&q.mainVideoEntityActionMetadata?{playbackDataActionMetadata:{maximumDownloadQuality:b.actionMetadata.mainVideoEntityActionMetadata.maximumDownloadQuality}}:void 0;n=r_a("OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",e,t);return p.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,[n]))}})},t_a=function(a,b){var c,d,e,f,h,l,m,n,p;
return g.B(function(q){switch(q.j){case 1:return c=B5(b),d=g.EI(b.entityKey),e=d.entityId,g.A(q,k5(a.j,b.entityKey,"mainVideoEntity"),2);case 2:f=q.u;if(!f){h=void 0;q.Ra(3);break}return g.A(q,k5(a.j,f.downloadState,"mainVideoDownloadStateEntity"),4);case 4:h=q.u;case 3:l=h;if(!f||!l)return q.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.ta(q,5);return g.A(q,q_a(a,e,l.addedTimestampMillis),7);case 7:m=r_a("OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH",e);g.ua(q,6);break;case 5:return n=
g.va(q),n instanceof Error&&"No data"===n.message?g.A(q,F5(e,a.j,b,a.B),6):(p="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",n instanceof g.gs&&"QUOTA_EXCEEDED"===n.type&&(p="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),q.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,p)));case 6:return q.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,m?[m]:void 0))}})},u_a=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=B5(b),g.ta(e,2),d=g.EI(b.entityKey).entityId,"!*$_ALL_ENTITIES_!*$"===d?g.A(e,fZa(a.j,b,a.B),5):g.A(e,F5(d,a.j,b,a.B),5);case 5:g.ua(e,3);break;case 2:return g.va(e),e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 3:return e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},q_a=function(a,b,c,d){var e,f,h,l,m,n;
return g.B(function(p){switch(p.j){case 1:if(e=d){p.Ra(2);break}return g.A(p,e6([b]),3);case 3:f=p.u,e=f[0];case 2:return g.A(p,v_a(a,e,c),4);case 4:h=p.u;l=h.mainVideoEntity;m=h.channelEntity;g.ta(p,5);var q=E5(l.thumbnail),t=E5(m.avatar);return g.A(p,A5(q.concat(t)),7);case 7:g.ua(p,0);break;case 5:n=g.va(p);if(!a.U.K("woffle_disable_thumbnails"))throw n;g.sa(p)}})},v_a=function(a,b,c){var d,e,f,h,l;
return g.B(function(m){if(1==m.j){if(!(b&&b.channel&&b.channel.offlineChannelData&&b.videoId))throw Error("Invalid OfflineVideoData");c||(c=Date.now().toString());e=null==(d=b.channel)?void 0:d.offlineChannelData;f={id:g.FI(b.videoId,"ytMainChannelEntity"),channelId:e.channelId,title:e.title,avatar:e.thumbnail};h={key:g.FI(b.videoId,"mainVideoDownloadStateEntity"),playbackData:g.FI(b.videoId,"playbackData"),addedTimestampMillis:c};l={key:g.FI(b.videoId,"mainVideoEntity"),videoId:b.videoId,title:b.title,
thumbnail:b.thumbnail,localizedStrings:{viewCount:b.shortViewCountText},lengthSeconds:b.lengthSeconds?Number(b.lengthSeconds):void 0,publishedTimestampMillis:b.publishedTimestamp?(1E3*Number(b.publishedTimestamp)).toString():void 0,formattedDescription:b.description,owner:f.id,downloadState:h.key};return g.A(m,h5(a.j,{mode:"readwrite",Cc:!0},function(n){var p=b5(n,f,"ytMainChannelEntity"),q=b5(n,h,"mainVideoDownloadStateEntity");n=b5(n,l,"mainVideoEntity");return g.ns.all([p,q,n])}),2)}return m.return({mainVideoEntity:l,
channelEntity:f})})},r_a=function(a,b,c){b=g.FI(b,"playbackData");
c=Object.assign({},c,{priority:1,retryScheduleIntervalsInSeconds:w_a});return{actionType:a,entityKey:b,actionMetadata:c}},g6=function(a,b,c){this.j=a;
this.U=b;this.B=c},z_a=function(a,b){var c,d,e,f,h,l;
return g.B(function(m){switch(m.j){case 1:return c=B5(b),d=g.EI(b.entityKey),e=d.entityId,g.ta(m,2),g.A(m,x_a(a,e),4);case 4:g.ua(m,3);break;case 2:return f=g.va(m),h="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",f instanceof g.gs&&"QUOTA_EXCEEDED"===f.type&&(h="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),m.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,h));case 3:var n;var p=null!=(n=b.actionMetadata)&&n.ytMainDownloadedVideoEntityActionMetadata?{playbackDataActionMetadata:{maximumDownloadQuality:b.actionMetadata.ytMainDownloadedVideoEntityActionMetadata.maximumDownloadQuality}}:
void 0;l=y_a("OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",e,p);return m.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,[l]))}})},A_a=function(a,b){var c,d,e,f,h,l,m;
return g.B(function(n){switch(n.j){case 1:return c=B5(b),d=g.EI(b.entityKey),e=d.entityId,g.A(n,k5(a.j,b.entityKey,"ytMainDownloadedVideoEntity"),2);case 2:f=n.u;if(!f)return n.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.ta(n,3);return g.A(n,x_a(a,e,f.addedTimestampMillis),5);case 5:h=y_a("OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH",e);g.ua(n,4);break;case 3:return l=g.va(n),l instanceof Error&&"No data"===l.message?g.A(n,F5(e,a.j,b,a.B),4):(m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",
l instanceof g.gs&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),n.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,m)));case 4:return n.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,h?[h]:void 0))}})},B_a=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=B5(b),g.ta(e,2),d=g.EI(b.entityKey).entityId,"!*$_ALL_ENTITIES_!*$"===d?g.A(e,fZa(a.j,b,a.B),5):g.A(e,F5(d,a.j,b,a.B),5);case 5:g.ua(e,3);break;case 2:return g.va(e),e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 3:return e.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},x_a=function(a,b,c){var d,e,f,h,l,m;
return g.B(function(n){switch(n.j){case 1:return g.A(n,e6([b]),2);case 2:return d=n.u,e=d[0],g.A(n,C_a(a,e,c),3);case 3:f=n.u;h=f.videoEntity;l=f.channelEntity;g.ta(n,4);var p=E5(h.thumbnail),q=E5(l.avatar);return g.A(n,A5(p.concat(q)),6);case 6:g.ua(n,0);break;case 4:m=g.va(n);if(!a.U.K("woffle_disable_thumbnails"))throw m;g.sa(n)}})},C_a=function(a,b,c){var d,e,f,h,l,m,n;
return g.B(function(p){if(1==p.j){if(!(b&&b.channel&&b.channel.offlineChannelData&&b.videoId))throw Error("Invalid OfflineVideoData");c||(c=Date.now().toString());e=null==(d=b.channel)?void 0:d.offlineChannelData;f={id:g.FI(b.videoId,"ytMainChannelEntity"),channelId:e.channelId,title:e.title,avatar:e.thumbnail};h={id:g.FI(b.videoId,"ytMainVideoEntity"),videoId:b.videoId,title:b.title,thumbnail:b.thumbnail,localizedStrings:{viewCount:b.shortViewCountText},lengthSeconds:b.lengthSeconds?Number(b.lengthSeconds):
void 0,publishedTimestampMillis:b.publishedTimestamp?(1E3*Number(b.publishedTimestamp)).toString():void 0,formattedDescription:b.description,channelOwner:f.id};l={id:g.FI(b.videoId,"ytMainDownloadedVideoEntity"),video:h.id,playbackData:g.FI(b.videoId,"playbackData"),offlineVideoPolicy:g.FI(b.videoId,"offlineVideoPolicy"),addedTimestampMillis:c};return a.U.K("woffle_entity_migration")?(m={key:g.FI(b.videoId,"mainVideoDownloadStateEntity"),playbackData:g.FI(b.videoId,"playbackData"),addedTimestampMillis:c},
n={key:g.FI(b.videoId,"mainVideoEntity"),videoId:b.videoId,title:b.title,thumbnail:b.thumbnail,localizedStrings:{viewCount:b.shortViewCountText},lengthSeconds:b.lengthSeconds?Number(b.lengthSeconds):void 0,publishedTimestampMillis:b.publishedTimestamp?(1E3*Number(b.publishedTimestamp)).toString():void 0,formattedDescription:b.description,owner:f.id,downloadState:m.key},g.A(p,h5(a.j,{mode:"readwrite",Cc:!0},function(q){var t=b5(q,f,"ytMainChannelEntity"),v=b5(q,h,"ytMainVideoEntity"),x=b5(q,l,"ytMainDownloadedVideoEntity"),
y=b5(q,m,"mainVideoDownloadStateEntity");q=b5(q,n,"mainVideoEntity");return g.ns.all([t,v,x,y,q])}),3)):g.A(p,h5(a.j,{mode:"readwrite",
Cc:!0},function(q){var t=b5(q,f,"ytMainChannelEntity"),v=b5(q,h,"ytMainVideoEntity");q=b5(q,l,"ytMainDownloadedVideoEntity");return g.ns.all([t,v,q])}),3)}return p.return({videoEntity:h,
channelEntity:f,vja:l})})},y_a=function(a,b,c){b=g.FI(b,"playbackData");
c=Object.assign({},c,{priority:1,retryScheduleIntervalsInSeconds:D_a});return{actionType:a,entityKey:b,actionMetadata:c}},h6=function(){c6.apply(this,arguments);
this.I="ytMainDownloadedVideoEntity"},E_a=function(){var a;
return g.B(function(b){return 1==b.j?g.A(b,n5(),2):(a=b.u)?g.A(b,h5(a,{mode:"readwrite",Cc:!0},function(c){var d=$4(c,"ytMainDownloadedVideoEntity"),e=$4(c,"ytMainVideoEntity"),f=$4(c,"mainVideoEntity");return g.ns.all([d,e,f]).then(function(h){h=g.r(h);var l=h.next().value,m=h.next().value,n=h.next().value;h={};l=g.r(l);for(var p=l.next();!p.done;p=l.next()){p=p.value;var q=g.EI(p.id).entityId;h[q]=p}l={};m=g.r(m);for(p=m.next();!p.done;p=m.next())p=p.value,q=g.EI(p.id).entityId,l[q]=p;m={};n=g.r(n);
for(p=n.next();!p.done;p=n.next())p=p.value,q=g.EI(p.key).entityId,m[q]=p;n=[];p=g.r(Object.keys(h));for(q=p.next();!q.done;q=p.next())if(q=q.value,!m[q]&&l[q]){var t=h[q],v=l[q];t={key:g.FI(q,"mainVideoDownloadStateEntity"),playbackData:g.FI(q,"playbackData"),addedTimestampMillis:t.addedTimestampMillis};q=[{key:g.FI(q,"mainVideoEntity"),videoId:q,title:v.title,thumbnail:v.thumbnail,localizedStrings:v.localizedStrings,lengthSeconds:v.lengthSeconds,publishedTimestampMillis:v.publishedTimestampMillis,
formattedDescription:v.formattedDescription,owner:v.channelOwner,downloadState:t.key},t];n.push(b5(c,q[0],"mainVideoEntity"),b5(c,q[1],"mainVideoDownloadStateEntity"))}return g.ns.all(n)})}),0):b.return()})},i6=function(a,b){this.j=a;
this.U=b},H_a=function(a,b){var c,d,e,f,h,l;
return g.B(function(m){switch(m.j){case 1:return c=B5(b),d=g.EI(b.entityKey),e=d.entityId,g.ta(m,2),g.A(m,F_a(a,e),4);case 4:g.ua(m,3);break;case 2:return f=g.va(m),h="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",f instanceof g.gs&&"QUOTA_EXCEEDED"===f.type&&(h="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),m.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,h));case 3:var n;var p=null!=(n=b.actionMetadata)&&n.musicTrackEntityActionMetadata?{playbackDataActionMetadata:{maximumDownloadQuality:b.actionMetadata.musicTrackEntityActionMetadata.maximumDownloadQuality}}:
void 0;n=g.FI(e,"playbackData");p=Object.assign({},p,{priority:1,retryScheduleIntervalsInSeconds:G_a});l={actionType:"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",entityKey:n,actionMetadata:p};return m.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,[l]))}})},F_a=function(a,b){var c,d,e,f,h,l;
return g.B(function(m){switch(m.j){case 1:return g.A(m,e6([b]),2);case 2:return c=m.u,d=c[0],g.A(m,I_a(a,d),3);case 3:e=m.u;f=e.musicTrackEntity;h=e.musicArtistEntity;g.ta(m,4);var n=E5(f.thumbnailDetails),p=E5(h.thumbnailDetails);return g.A(m,A5(n.concat(p)),6);case 6:g.ua(m,0);break;case 4:l=g.va(m);if(!a.U.K("woffle_disable_thumbnails"))throw l;g.sa(m)}})},I_a=function(a,b){var c=void 0,d,e,f,h,l,m,n,p,q,t,v,x,y,z;
return g.B(function(E){if(1==E.j){if(!(b&&b.channel&&b.channel.offlineChannelData&&b.videoId&&b.additionalMetadatas))throw Error("Invalid OfflineVideoData");c||(c=Date.now().toString());e=g.r(b.additionalMetadatas);for(f=e.next();!f.done;f=e.next())h=f.value,h.offlineMusicVideoData&&(d=h.offlineMusicVideoData);if(!d)throw Error("Invalid OfflineMusicVideoData");m=null==(l=b.channel)?void 0:l.offlineChannelData;n={id:g.FI(b.videoId,"musicArtist"),externalChannelId:m.channelId,name:m.title,thumbnailDetails:m.thumbnail};
p={id:g.FI(b.videoId,"musicTrackDownloadMetadataEntity"),playbackData:g.FI(b.videoId,"playbackData"),addedTimestampMillis:c};z={id:g.FI(b.videoId,"musicTrack"),videoId:b.videoId,title:b.title,thumbnailDetails:b.thumbnail,lengthMs:String(1E3*Number(b.lengthSeconds)),albumTitle:null==(q=d)?void 0:q.releaseTitle,musicVideoType:null==(t=d)?void 0:t.musicVideoType,contentRating:{explicitType:null==(v=d)?void 0:v.explicitType},artists:[n.id],artistNames:(null==(x=d)?void 0:x.byline)||(null==(y=d)?void 0:
y.channelName),downloadMetadata:p.id};return g.A(E,h5(a.j,{mode:"readwrite",Cc:!0},function(I){var J=b5(I,n,"musicArtist"),L=b5(I,p,"musicTrackDownloadMetadataEntity");I=b5(I,z,"musicTrack");return g.ns.all([J,L,I])}),2)}return E.return({musicTrackEntity:z,
musicArtistEntity:n})})},j6=function(){c6.apply(this,arguments);
this.I="musicTrack"},k6=function(){g.lJ.apply(this,arguments)};
g.w(X3,W3);g.fa.Object.defineProperties(X3.prototype,{entityMetadata:{configurable:!0,enumerable:!0,get:function(){return this.j.entityMetadata},
set:function(a){this.j.entityMetadata=a}}});
g.w(Y3,X3);Y3.prototype.u=function(){return[]};
g.w(Z3,X3);Z3.prototype.u=function(){var a=[];this.j.alternateChannel&&a.push(this.j.alternateChannel);this.j.alternateChannelList&&a.push.apply(a,g.u(this.j.alternateChannelList));this.j.oneofChannelEntity&&a.push(this.j.oneofChannelEntity);return[].concat(g.u(new Set(a)))};
g.w($3,X3);$3.prototype.u=function(){var a=[];this.j.entryCollection&&a.push(this.j.entryCollection);return[].concat(g.u(new Set(a)))};
g.w(a4,W3);a4.prototype.u=function(){var a=[];this.j.video&&a.push(this.j.video);return[].concat(g.u(new Set(a)))};
g.w(b4,X3);b4.prototype.u=function(){var a=[];this.j.parentPlaylist&&a.push(this.j.parentPlaylist);if(this.j.entries)for(var b=g.r(this.j.entries),c=b.next();!c.done;c=b.next())a.push.apply(a,g.u((new a4(c.value)).u()));return[].concat(g.u(new Set(a)))};
g.w(c4,X3);c4.prototype.u=function(){var a=[];this.j.descriptionEntity&&a.push(this.j.descriptionEntity);this.j.creators&&a.push.apply(a,g.u(this.j.creators));this.j.theBiggestFan&&a.push(this.j.theBiggestFan);return[].concat(g.u(new Set(a)))};
g.w(d4,X3);d4.prototype.u=function(){return[]};
g.w(e4,X3);e4.prototype.u=function(){return[]};
g.w(f4,X3);f4.prototype.u=function(){return[]};
g.w(g4,X3);g4.prototype.u=function(){return[]};
g.w(h4,X3);h4.prototype.u=function(){var a=[];this.j.playbackData&&a.push(this.j.playbackData);this.j.localImageEntities&&a.push.apply(a,g.u(this.j.localImageEntities));return[].concat(g.u(new Set(a)))};
g.w(i4,X3);i4.prototype.u=function(){return[]};
g.w(j4,X3);j4.prototype.u=function(){var a=[];this.j.fakeChildren&&a.push.apply(a,g.u(this.j.fakeChildren));return[].concat(g.u(new Set(a)))};
g.w(k4,X3);k4.prototype.u=function(){var a=[];this.j.video&&a.push(this.j.video);this.j.playbackData&&a.push(this.j.playbackData);this.j.offlineVideoPolicy&&a.push(this.j.offlineVideoPolicy);return[].concat(g.u(new Set(a)))};
g.w(l4,X3);l4.prototype.u=function(){var a=[];this.j.channelOwner&&a.push(this.j.channelOwner);this.j.videos&&a.push.apply(a,g.u(this.j.videos));this.j.collaboratorChannels&&a.push.apply(a,g.u(this.j.collaboratorChannels));return[].concat(g.u(new Set(a)))};
g.w(m4,X3);m4.prototype.u=function(){var a=[];this.j.video&&a.push(this.j.video);this.j.channelContributor&&a.push(this.j.channelContributor);return[].concat(g.u(new Set(a)))};
g.w(n4,W3);n4.prototype.u=function(){var a=[];this.j.playbackPosition&&a.push(this.j.playbackPosition);return[].concat(g.u(new Set(a)))};
g.w(o4,X3);o4.prototype.u=function(){var a=[];this.j.owner&&a.push(this.j.owner);this.j.downloadState&&a.push(this.j.downloadState);this.j.userState&&a.push.apply(a,g.u((new n4(this.j.userState)).u()));return[].concat(g.u(new Set(a)))};
g.w(p4,X3);p4.prototype.u=function(){return[]};
g.w(q4,X3);q4.prototype.u=function(){var a=[];this.j.channelOwner&&a.push(this.j.channelOwner);this.j.playbackPosition&&a.push(this.j.playbackPosition);this.j.localImageEntities&&a.push.apply(a,g.u(this.j.localImageEntities));this.j.downloadStatus&&a.push(this.j.downloadStatus);return[].concat(g.u(new Set(a)))};
g.w(r4,X3);r4.prototype.u=function(){return[]};
g.w(s4,X3);s4.prototype.u=function(){return[]};
g.w(t4,X3);t4.prototype.u=function(){var a=[];this.j.trackDownloadMetadatas&&a.push.apply(a,g.u(this.j.trackDownloadMetadatas));return[].concat(g.u(new Set(a)))};
g.w(u4,X3);u4.prototype.u=function(){var a=[];this.j.playbackData&&a.push(this.j.playbackData);this.j.localImageEntities&&a.push.apply(a,g.u(this.j.localImageEntities));return[].concat(g.u(new Set(a)))};
g.w(v4,X3);v4.prototype.u=function(){var a=[];this.j.musicLibraryStatusEntity&&a.push(this.j.musicLibraryStatusEntity);this.j.primaryArtists&&a.push.apply(a,g.u(this.j.primaryArtists));this.j.details&&a.push(this.j.details);this.j.userDetails&&a.push(this.j.userDetails);this.j.tracks&&a.push.apply(a,g.u(this.j.tracks));this.j.share&&a.push(this.j.share);this.j.downloadMetadata&&a.push(this.j.downloadMetadata);return[].concat(g.u(new Set(a)))};
g.w(w4,X3);w4.prototype.u=function(){var a=[];this.j.albumRelease&&a.push(this.j.albumRelease);this.j.tracks&&a.push.apply(a,g.u(this.j.tracks));return[].concat(g.u(new Set(a)))};
g.w(x4,X3);x4.prototype.u=function(){var a=[];this.j.albumRelease&&a.push(this.j.albumRelease);return[].concat(g.u(new Set(a)))};
g.w(y4,X3);y4.prototype.u=function(){var a=[];this.j.details&&a.push(this.j.details);this.j.userDetails&&a.push(this.j.userDetails);return[].concat(g.u(new Set(a)))};
g.w(z4,X3);z4.prototype.u=function(){var a=[];this.j.parentArtist&&a.push(this.j.parentArtist);return[].concat(g.u(new Set(a)))};
g.w(A4,X3);A4.prototype.u=function(){var a=[];this.j.parentArtist&&a.push(this.j.parentArtist);return[].concat(g.u(new Set(a)))};
g.w(B4,X3);B4.prototype.u=function(){return[]};
g.w(C4,X3);C4.prototype.u=function(){return[]};
g.w(D4,X3);D4.prototype.u=function(){return[]};
g.w(E4,X3);
E4.prototype.u=function(){var a=[];this.j.musicLibraryStatusEntity&&a.push(this.j.musicLibraryStatusEntity);this.j.artists&&a.push.apply(a,g.u(this.j.artists));this.j.audioModeVersion&&a.push(this.j.audioModeVersion);this.j.videoModeVersion&&a.push(this.j.videoModeVersion);this.j.userDetails&&a.push(this.j.userDetails);this.j.details&&a.push(this.j.details);this.j.albumRelease&&a.push(this.j.albumRelease);this.j.share&&a.push(this.j.share);this.j.libraryEdit&&a.push(this.j.libraryEdit);this.j.downloadMetadata&&
a.push(this.j.downloadMetadata);return[].concat(g.u(new Set(a)))};
g.w(F4,X3);F4.prototype.u=function(){var a=[];this.j.parentTrack&&a.push(this.j.parentTrack);return[].concat(g.u(new Set(a)))};
g.w(G4,X3);G4.prototype.u=function(){var a=[];this.j.parentTrack&&a.push(this.j.parentTrack);return[].concat(g.u(new Set(a)))};
g.w(H4,X3);H4.prototype.u=function(){return[]};
g.w(I4,X3);I4.prototype.u=function(){return[]};
g.w(J4,X3);J4.prototype.u=function(){return[]};
g.w(K4,X3);K4.prototype.u=function(){return[]};
g.w(L4,X3);L4.prototype.u=function(){var a=[];this.j.transfer&&a.push(this.j.transfer);this.j.adsPlaybackData&&a.push.apply(a,g.u(this.j.adsPlaybackData));this.j.drmLicense&&a.push(this.j.drmLicense);this.j.offlineVideoPolicy&&a.push(this.j.offlineVideoPolicy);return[].concat(g.u(new Set(a)))};
g.w(M4,X3);M4.prototype.u=function(){var a=[];this.j.offlineVideoStreams&&a.push.apply(a,g.u(this.j.offlineVideoStreams));this.j.captionTrack&&a.push.apply(a,g.u(this.j.captionTrack));return[].concat(g.u(new Set(a)))};
g.w(N4,X3);N4.prototype.u=function(){return[]};
g.w(O4,X3);O4.prototype.u=function(){return[]};
g.w(P4,X3);P4.prototype.u=function(){return[]};
g.w(Q4,X3);Q4.prototype.u=function(){return[]};
g.w(R4,X3);R4.prototype.u=function(){return[]};
var p_a=["offline"],lZa=["offline/get_playback_data_entity"],J_a={z3:"captionTrack",g7:"ytMainDownloadedVideoEntity",h7:"ytMainVideoEntity",V$:"ytMainChannelEntity",W$:"mainPlaylistEntity",X$:"mainPlaylistVideoEntity",Y$:"mainVideoEntity",Z$:"mainVideoDownloadStateEntity",jca:"musicAlbumReleaseDetail",kca:"musicAlbumReleaseDownloadMetadataEntity",lca:"musicAlbumRelease",mca:"musicAlbumReleaseUserDetail",nca:"musicArtistDetail",oca:"musicArtist",qca:"musicArtistUserDetail",zca:"musicLibraryEdit",Aca:"musicLibraryStatusEntity",
Kca:"musicShare",Pca:"musicTrackDetail",Qca:"musicTrackDownloadMetadataEntity",Rca:"musicTrack",Sca:"musicTrackUserDetail",jda:"offlineOrchestrationActionWrapperEntity",tda:"offlineVideoPolicy",uda:"offlineVideoStreams",fea:"playbackData",gfa:"orchestrationWebSamplingEntity",Vga:"transfer"},T4;g.w(U4,g.bs);g.w(W4,rYa);W4.prototype.B=function(a,b){b=V4(b);a=(new TextEncoder).encode(JSON.stringify(a));return this.j.encrypt(a,b)};
W4.prototype.u=function(a,b){if(!(a instanceof Uint8Array))throw nYa(1);var c=new TextDecoder;b=V4(b);a=this.j.decrypt(a,b);return JSON.parse(c.decode(a))};
var tYa={buttonEntity:N4,captionTrack:H4,channelHandle:Y3,commerceCartListEntity:P4,downloadQualityPickerEntity:g4,fakeChannel:Z3,fakePlaylist:$3,fakePlaylistEntryCollection:b4,fakeVideo:c4,fakeVideoDescription:d4,iconBadgeEntity:Q4,liveChatPollStateEntity:f4,logoEntity:e4,mainPlaylistEntity:l4,mainPlaylistVideoEntity:m4,mainVideoDownloadStateEntity:h4,mainVideoEntity:o4,markersVisibilityOverrideEntity:r4,musicAlbumReleaseDetail:w4,musicAlbumReleaseDownloadMetadataEntity:t4,musicAlbumRelease:v4,musicAlbumReleaseUserDetail:x4,
musicArtistDetail:z4,musicArtist:y4,musicArtistUserDetail:A4,musicLibraryEdit:B4,musicLibraryStatusEntity:C4,musicShare:D4,musicTrackDetail:F4,musicTrackDownloadMetadataEntity:u4,musicTrack:E4,musicTrackUserDetail:G4,offlineOrchestrationActionWrapperEntity:I4,offlineVideoPolicy:J4,offlineVideoStreams:K4,offlineabilityEntity:i4,orchestrationWebSamplingEntity:j4,pinnedProductEntity:s4,playbackData:L4,quantityIncrementerEntity:R4,transfer:M4,videoPlaybackPositionEntity:O4,ytMainChannelEntity:p4,ytMainDownloadedVideoEntity:k4,
ytMainVideoEntity:q4};g.w(f5,rYa);f5.prototype.B=function(a){return a};
f5.prototype.u=function(a){if(a instanceof Uint8Array)throw nYa(0);return a};
g.w(g5,g.G);g5.prototype.B=function(a){DYa(this,a.data)};
g5.prototype.ea=function(){this.channel.close()};
var m5;g.w(p5,g.G);p5.prototype.B=function(a){this.api.Ma("onOfflineOperationFailure",a.data)};
p5.prototype.C=function(a){this.api.X("offlinetransferpause",a.data)};
p5.prototype.ea=function(){var a;null==(a=this.j)||a.close();var b;null==(b=this.u)||b.close()};NYa.prototype.request=function(a,b,c){b=void 0===b?{}:b;return this.locks.request(a,b,function(d){return c(d)})};QYa.prototype.uf=function(){this.j&&r5(this)};var x5=g.C.caches,w5,y5;t5.prototype.open=function(a){return x5.open(v5(a))};
t5.prototype.has=function(a){return x5.has(v5(a))};
t5.prototype.delete=function(a){return x5.delete(v5(a))};
t5.prototype.match=function(a,b){var c=this,d,e,f,h,l,m;return g.B(function(n){switch(n.j){case 1:return g.A(n,c.keys(),2);case 2:d=n.u,e=g.r(d),f=e.next();case 3:if(f.done){n.Ra(5);break}h=f.value;return g.A(n,c.open(h),6);case 6:return l=n.u,g.A(n,l.match(a,b),7);case 7:if(m=n.u)return n.return(m);f=e.next();n.Ra(3);break;case 5:return n.return()}})};
g.w(u5,t5);u5.prototype.keys=function(){var a,b,c,d,e,f,h,l,m;return g.B(function(n){if(1==n.j)return a=[],b=g.cs("CacheStorage keys"),g.A(n,x5.keys(),2);c=n.u;d=g.r(c);for(e=d.next();!e.done;e=d.next()){f=e.value;var p=f.indexOf(":");h=-1===p?{IC:f}:{IC:f.substring(0,p),datasyncId:f.substring(p+1)};l=h.IC;m=h.datasyncId;m===b&&a.push(l)}return n.return(a)})};Object.keys(J_a).map(function(a){return J_a[a]});
var eZa="captionTrack ytMainDownloadedVideoEntity ytMainVideoEntity ytMainChannelEntity mainVideoEntity mainVideoDownloadStateEntity offlineVideoPolicy offlineVideoStreams playbackData transfer".split(" ");g.w(I5,G5);I5.prototype.u=function(a){return C5(a)?jZa(this,a):D5(a)?kZa(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};g.w(K5,G5);K5.prototype.u=function(a){return C5(a)?nZa(this,a):D5(a)?oZa(this,a):"OFFLINE_ORCHESTRATION_ACTION_TYPE_UPDATE"===a.actionType&&a.entityKey?this.handleUpdate(a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
K5.prototype.handleUpdate=function(a){var b=this,c,d,e;return g.B(function(f){switch(f.j){case 1:return c=B5(a),g.A(f,k5(b.j,a.entityKey,"transfer"),2);case 2:d=f.u;if(!d||"TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH"!==d.transferState)return f.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.ta(f,3);d.transferState="TRANSFER_STATE_TRANSFER_IN_QUEUE";return g.A(f,j5(b.j,d,"transfer"),5);case 5:e=g.EI(d.key).entityId;s5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_PLAYER_RESPONSE_REFRESH",
statusType:"ADDED_TO_QUEUE"},{videoId:e,gj:d});g.ua(f,4);break;case 3:return g.va(f),f.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return f.return(new H5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})};var EZa=["OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD","OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"];var N5;wZa.prototype.j=function(a,b){var c=a.action.actionMetadata.priority-b.action.actionMetadata.priority;0===c&&(a.j<b.j?c=-1:a.j>b.j&&(c=1));return c};g.w(Q5,g.G);Q5.prototype.ea=function(){this.J&&this.J();g.G.prototype.ea.call(this)};
Q5.prototype.createAction=function(a,b){var c=g.EI(a.entityKey).entityType,d=g.bv(16);return new L5(c,d,a,b.actionId,b.rootActionId)};
Q5.prototype.W=function(a){var b=this,c,d,e,f,h,l,m,n,p;return g.B(function(q){if(1==q.j){if(b.isDisposed())return q.return();d=null!=(c=a.offlineOrchestrationActionWrapperEntity)?c:new Set;e=[];f=g.r(d);for(h=f.next();!h.done;h=f.next())l=h.value,m=g.EI(l),n=m.entityId,yZa(b.j,n)||e.push(l);return g.A(q,GZa(b,e),2)}p=q.u;return g.A(q,S5(b,p),0)})};
Q5.prototype.retry=function(){var a=this;return g.B(function(b){return g.A(b,HZa(a),0)})};g.k=NZa.prototype;
g.k.PY=function(a){var b=this,c,d,e,f;return g.B(function(h){if(!g.U(a.state,128))return h.Ra(0);var l=null==(c=a.state.getData())?void 0:c.errorCode,m=null==(d=a.state.getData())?void 0:d.II,n=null==(e=a.state.getData())?void 0:e.fB;f=b.K("html5_eliminate_net_retryexhausted_error")&&"net.connect"===l&&1===n||"net.retryexhausted"===l&&(null==m?0:m.includes("net.connect"))?"TRANSFER_FAILURE_REASON_NETWORK_LOST":(null==l?0:l.startsWith("net."))?"TRANSFER_FAILURE_REASON_NETWORK":"TRANSFER_FAILURE_REASON_INTERNAL";return g.A(h,
b.ls(b.player.getVideoData().videoId,f),0)})};
g.k.ls=function(a,b){var c=this;return g.B(function(d){if(1==d.j){if(c.u)return d.return();c.u=!0;return"TRANSFER_FAILURE_REASON_NETWORK_LOST"===b?(U5(c,a,!1,!0),d.Ra(0)):g.A(d,T5(c,a),3)}g.QC(a,4);return g.A(d,c.j.ls(b),0)})};
g.k.AC=function(a){2===a.status?(a.status!==this.B&&(Z5(this.j),g.QC(a.videoId,2)),a.kz&&h_a(this.j,a.videoId,a.kz)):4===a.status?(T5(this,a.videoId),this.ls(a.videoId,a.OB?"TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":"TRANSFER_FAILURE_REASON_INTERNAL")):1===a.status&&f_a(this.j);this.B=a.status;this.api.Ma("localmediachange",{videoId:a.videoId,status:a.status})};
g.k.gI=function(){var a=this,b;return g.B(function(c){if(1==c.j){if(a.u)return c.return();a.u=!0;b=a.player.getVideoData().videoId;return g.A(c,T5(a,b),2)}return g.A(c,a.j.gI(),0)})};
g.k.K=function(a){return this.api.S().K(a)};g.w(V5,g.G);V5.prototype.ea=function(){this.u&&this.u();g.G.prototype.ea.call(this)};
V5.prototype.B=function(a){var b=this,c,d,e,f,h,l,m,n;return g.B(function(p){d=null!=(c=a.transfer)?c:new Set;e=[];f=g.r(d);for(h=f.next();!h.done;h=f.next())l=h.value,m=g.EI(l),n=m.entityId,e.push(n);return 0===e.length?p.return():g.A(p,UZa(b,e),0)})};g.w(W5,g.G);g.k=W5.prototype;g.k.ea=function(){this.J&&this.J();this.N.dispose();this.C.dispose();this.Y&&g.Tf(this.D.B,this.Y);this.W&&g.Tf(this.D.B,this.W);g.G.prototype.ea.call(this)};
g.k.X_=function(a){var b=this,c,d;return g.B(function(e){if(1==e.j)return c=g.FI(a,"transfer"),b.j&&c===b.j.key?(U5(b.I,b.B,!0),b.C.stop(),e.Ra(0)):g.A(e,h5(b.u,{mode:"readwrite",Cc:!0},function(f){return Z4(f,c,"transfer").then(function(h){if(h&&"TRANSFER_STATE_COMPLETE"!==h.transferState&&"TRANSFER_STATE_FAILED"!==h.transferState)return h.transferState="TRANSFER_STATE_PAUSED_BY_USER",b5(f,h,"transfer").then(function(){return h})})}),3);
(d=e.u)&&WYa({videoId:a,gj:d});g.sa(e)})};
g.k.W_=function(){this.j&&this.B&&U5(this.I,this.B,!1);this.C.stop()};
g.k.xz=function(){this.j?$Za(this,this.j):Y5(this)};
g.k.HU=function(a){var b=this,c;return g.B(function(d){switch(d.j){case 1:if(!b.j){d.Ra(2);break}if("TRANSFER_STATE_COMPLETE"===b.j.transferState||"TRANSFER_STATE_FAILED"===b.j.transferState||!a.transfer||!a.transfer.has(b.j.key)){d.Ra(3);break}c=b;return g.A(d,k5(b.u,b.j.key,"transfer"),4);case 4:c.j=d.u;if(b.j){d.Ra(3);break}return g.A(d,a_a(b),3);case 3:if(b.j)return d.return();case 2:return g.A(d,Y5(b),0)}})};
g.k.ls=function(a,b){var c=this,d,e;return g.B(function(f){if(1==f.j){a:switch(a){case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_PLAYABILITY":case "TRANSFER_FAILURE_REASON_TOO_MANY_RETRIES":var h=!1;break a;default:h=!0}return h&&i_a(c)?g.A(f,a6(c,"TRANSFER_STATE_TRANSFER_IN_QUEUE"),5):g.A(f,j_a(c,a),3)}3!=f.j&&(d=g.EI(c.j.key).entityId,s5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_RETRY",statusType:"ADDED_TO_QUEUE"},
{videoId:d,gj:c.j}));X5(c);e=Y5(c,!0);b&&b(e);g.sa(f)})};
g.k.gI=function(a){var b=this,c,d,e,f,h,l;return g.B(function(m){if(1==m.j)return i_a(b)?g.A(m,a6(b,"TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH"),5):g.A(m,j_a(b,"TRANSFER_FAILURE_REASON_STREAM_MISSING"),3);if(3!=m.j)return c=g.EI(b.j.key).entityId,s5({transferStatusType:"TRANSFER_STATUS_TYPE_DEQUEUED_BY_PLAYER_RESPONSE_EXPIRATION",statusType:"ADDED_TO_QUEUE"},{videoId:c,gj:b.j}),d=qZa(),d.playbackDataActionMetadata={isEnqueuedForExpiredStreamUrlRefetch:!0},e=g.FI(c,"playbackData"),f={actionType:"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",
entityKey:e,actionMetadata:d},h=M5(new L5("playbackData",c,f)),g.A(m,j5(b.u,h,"offlineOrchestrationActionWrapperEntity"),3);X5(b);l=Y5(b,!0);a&&a(l);g.sa(m)})};
var l6={},b6=(l6.TRANSFER_STATE_TRANSFERRING=1,l6.TRANSFER_STATE_TRANSFER_IN_QUEUE=2,l6);g.k=c6.prototype;g.k.Px=function(a){var b={};return b.playbackData=new I5(a,this.U,this.u),b.transfer=new K5(a),b};
g.k.YI=function(){var a=this;return g.B(function(b){return a.j?g.A(b,YZa(a.j),0):b.Ra(0)})};
g.k.isOrchestrationLeader=function(){return this.B.j};
g.k.vI=function(a){var b=this.u;b.api.X("offlinetransferpause",a);var c;null==(c=b.u)||c.postMessage(a)};
g.k.xz=function(a){var b,c;return g.B(function(d){if(1==d.j)return g.A(d,n5(),2);b=d.u;if(!b)return d.return();c=g.FI(a,"transfer");return g.A(d,h5(b,{mode:"readwrite",Cc:!0},function(e){return Z4(e,c,"transfer").then(function(f){return f&&"TRANSFER_STATE_PAUSED_BY_USER"===f.transferState?(f.transferState="TRANSFER_STATE_TRANSFER_IN_QUEUE",b5(e,f,"transfer").then(function(){s5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_USER_RESUME",statusType:"USER_RESUMED"},{videoId:a,gj:f});return g.ns.resolve(null)})):
g.ns.resolve(null)})}),0)})};
g.k.rz=function(a){a=void 0===a?43200:a;var b=this,c,d,e,f,h,l,m,n;return g.B(function(p){if(1==p.j)return b.N.tf()?g.A(p,n5(),2):p.return(o_a());if(3!=p.j){c=p.u;if(!c)return p.return([]);d=Date.now()/1E3;return g.A(p,l5(c,"offlineVideoPolicy"),3)}e=p.u;f=[];h=g.r(e);for(l=h.next();!l.done;l=h.next())m=l.value,Number(m.lastUpdatedTimestampSeconds)+a<=d&&(n=g.EI(m.key).entityId,f.push(n));return f.length?p.return(d6(b,f,b.I,"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH")):p.return([])})};
g.k.deleteAll=function(){return d6(this,["!*$_ALL_ENTITIES_!*$"],this.I,"OFFLINE_ORCHESTRATION_ACTION_TYPE_DELETE")};g.w(f6,G5);f6.prototype.u=function(a){return C5(a)?s_a(this,a):D5(a)?t_a(this,a):aZa(a)?u_a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var w_a=[10];g.w(g6,G5);g6.prototype.u=function(a){return C5(a)?z_a(this,a):D5(a)?A_a(this,a):aZa(a)?B_a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var D_a=[10];g.w(h6,c6);h6.prototype.Px=function(a){var b=c6.prototype.Px.call(this,a);b.ytMainDownloadedVideoEntity=new g6(a,this.U,this.u);b.mainVideoEntity=new f6(a,this.U,this.u);return b};
h6.prototype.YI=function(){var a=this;return g.B(function(b){return 1==b.j?g.A(b,c6.prototype.YI.call(a),2):a.U.K("woffle_entity_migration")?g.A(b,E_a(),0):b.Ra(0)})};g.w(i6,G5);i6.prototype.u=function(a){return C5(a)?H_a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var G_a=[10];g.w(j6,c6);j6.prototype.Px=function(a){var b=c6.prototype.Px.call(this,a);b.musicTrack=new i6(a,this.U);return b};g.w(k6,g.lJ);g.k=k6.prototype;g.k.create=function(){var a=this.player.S();g.iC(a)?this.j=new h6(a,this.player):g.SB(a)&&(this.j=new j6(a,this.player))};
g.k.bj=function(){return!1};
g.k.JI=function(a,b,c,d){var e=this;return g.B(function(f){return e.j?f.return(d6(e.j,a,b,c,d)):f.return(Promise.reject())})};
g.k.deleteAll=function(){return this.j.deleteAll()};
g.k.rz=function(a){return this.j.rz(a)};
g.k.vI=function(a){this.j.vI(a)};
g.k.xz=function(a){return this.j.xz(a)};
g.k.isOrchestrationLeader=function(){return this.j.isOrchestrationLeader()};g.kJ("offline",k6);})(_yt_player);
